package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	goerr "github.com/m-mizutani/goerr/v2"
	"github.com/secmon-lab/warren/pkg/domain/model/alert"
	"github.com/secmon-lab/warren/pkg/domain/model/auth"
	diagnosismodel "github.com/secmon-lab/warren/pkg/domain/model/diagnosis"
	graphql1 "github.com/secmon-lab/warren/pkg/domain/model/graphql"
	hitlModel "github.com/secmon-lab/warren/pkg/domain/model/hitl"
	knowledgeModel "github.com/secmon-lab/warren/pkg/domain/model/knowledge"
	"github.com/secmon-lab/warren/pkg/domain/model/session"
	"github.com/secmon-lab/warren/pkg/domain/model/slack"
	"github.com/secmon-lab/warren/pkg/domain/model/ticket"
	"github.com/secmon-lab/warren/pkg/domain/types"
	hitlService "github.com/secmon-lab/warren/pkg/service/hitl"
	"github.com/secmon-lab/warren/pkg/utils/logging"
	"github.com/secmon-lab/warren/pkg/utils/user"
)

// User is the resolver for the user field.
func (r *activityResolver) User(ctx context.Context, obj *graphql1.Activity) (*graphql1.User, error) {
	if obj.UserID == nil || *obj.UserID == "" {
		return nil, nil
	}

	// Use DataLoader to efficiently fetch user
	return GetUser(ctx, *obj.UserID)
}

// Alert is the resolver for the alert field.
func (r *activityResolver) Alert(ctx context.Context, obj *graphql1.Activity) (*alert.Alert, error) {
	if obj.AlertID == nil || *obj.AlertID == "" {
		return nil, nil
	}

	alertID := types.AlertID(*obj.AlertID)

	// Use DataLoader to efficiently fetch alert
	return GetAlert(ctx, alertID)
}

// Ticket is the resolver for the ticket field.
func (r *activityResolver) Ticket(ctx context.Context, obj *graphql1.Activity) (*ticket.Ticket, error) {
	if obj.TicketID == nil || *obj.TicketID == "" {
		return nil, nil
	}

	ticketID := types.TicketID(*obj.TicketID)

	// Use DataLoader to efficiently fetch ticket
	return GetTicket(ctx, ticketID)
}

// ID is the resolver for the id field.
func (r *alertResolver) ID(ctx context.Context, obj *alert.Alert) (string, error) {
	return string(obj.ID), nil
}

// Schema is the resolver for the schema field.
func (r *alertResolver) Schema(ctx context.Context, obj *alert.Alert) (string, error) {
	return string(obj.Schema), nil
}

// Data is the resolver for the data field.
func (r *alertResolver) Data(ctx context.Context, obj *alert.Alert) (string, error) {
	// Convert obj.Data to JSON string
	jsonBytes, err := json.Marshal(obj.Data)
	if err != nil {
		return "", goerr.Wrap(err, "failed to marshal alert data to JSON")
	}
	return string(jsonBytes), nil
}

// Attributes is the resolver for the attributes field.
func (r *alertResolver) Attributes(ctx context.Context, obj *alert.Alert) ([]*graphql1.AlertAttribute, error) {
	attributes := make([]*graphql1.AlertAttribute, len(obj.Attributes))
	for i, attr := range obj.Attributes {
		var link *string
		if attr.Link != "" {
			link = &attr.Link
		}
		attributes[i] = &graphql1.AlertAttribute{
			Key:   attr.Key,
			Value: attr.Value,
			Link:  link,
			Auto:  attr.Auto,
		}
	}
	return attributes, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *alertResolver) CreatedAt(ctx context.Context, obj *alert.Alert) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// Ticket is the resolver for the ticket field.
func (r *alertResolver) Ticket(ctx context.Context, obj *alert.Alert) (*ticket.Ticket, error) {
	if obj.TicketID == types.EmptyTicketID {
		return nil, nil
	}
	return r.repo.GetTicket(ctx, obj.TicketID)
}

// TagObjects is the resolver for the tagObjects field.
func (r *alertResolver) TagObjects(ctx context.Context, obj *alert.Alert) ([]*graphql1.TagObject, error) {
	if r.uc == nil || len(obj.TagIDs) == 0 {
		return []*graphql1.TagObject{}, nil
	}

	// Get tag IDs as slice
	tagIDSlice := make([]string, 0, len(obj.TagIDs))
	for tagID := range obj.TagIDs {
		tagIDSlice = append(tagIDSlice, tagID)
	}

	// Get tag metadata using tag getter
	tags, err := r.createTagGetter()(ctx, tagIDSlice)
	if err != nil {
		return nil, err
	}

	// Convert to GraphQL TagObject
	tagObjects := make([]*graphql1.TagObject, 0, len(tags))
	for _, tag := range tags {
		tagObjects = append(tagObjects, &graphql1.TagObject{
			ID:   tag.ID,
			Name: tag.Name,
		})
	}

	return tagObjects, nil
}

// Severity is the resolver for the severity field.
func (r *findingResolver) Severity(ctx context.Context, obj *ticket.Finding) (string, error) {
	return string(obj.Severity), nil
}

// Author is the resolver for the author field.
func (r *knowledgeResolver) Author(ctx context.Context, obj *graphql1.Knowledge) (*graphql1.User, error) {
	if obj.AuthorID == "" {
		return &graphql1.User{ID: "system", Name: "system"}, nil
	}
	return GetUser(ctx, obj.AuthorID)
}

// ResolveTicket is the resolver for the resolveTicket field.
func (r *mutationResolver) ResolveTicket(ctx context.Context, id string, conclusion string, reason string) (*ticket.Ticket, error) {
	alertConclusion := types.AlertConclusion(conclusion)
	if err := alertConclusion.Validate(); err != nil {
		return nil, goerr.Wrap(err, "invalid conclusion", goerr.V("conclusion", conclusion))
	}

	updatedTicket, err := r.uc.ResolveTicket(ctx, types.TicketID(id), alertConclusion, reason)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to resolve ticket")
	}

	return updatedTicket, nil
}

// ReopenTicket is the resolver for the reopenTicket field.
func (r *mutationResolver) ReopenTicket(ctx context.Context, id string) (*ticket.Ticket, error) {
	updatedTicket, err := r.uc.ReopenTicket(ctx, types.TicketID(id))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to reopen ticket")
	}

	return updatedTicket, nil
}

// ArchiveTicket is the resolver for the archiveTicket field.
func (r *mutationResolver) ArchiveTicket(ctx context.Context, id string) (*ticket.Ticket, error) {
	updatedTicket, err := r.uc.ArchiveTicket(ctx, types.TicketID(id))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to archive ticket")
	}

	return updatedTicket, nil
}

// ArchiveTickets is the resolver for the archiveTickets field.
func (r *mutationResolver) ArchiveTickets(ctx context.Context, ids []string) ([]*ticket.Ticket, error) {
	ticketIDs := make([]types.TicketID, len(ids))
	for i, id := range ids {
		ticketID := types.TicketID(id)
		if err := ticketID.Validate(); err != nil {
			return nil, goerr.Wrap(err, "invalid ticket ID", goerr.V("id", id))
		}
		ticketIDs[i] = ticketID
	}

	tickets, err := r.uc.ArchiveTickets(ctx, ticketIDs)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to archive tickets")
	}

	return tickets, nil
}

// ArchiveAllResolvedTickets is the resolver for the archiveAllResolvedTickets field.
func (r *mutationResolver) ArchiveAllResolvedTickets(ctx context.Context) (*graphql1.ArchiveAllResolvedResult, error) {
	count, err := r.uc.ArchiveAllResolvedTickets(ctx)
	if err != nil {
		return nil, err
	}
	return &graphql1.ArchiveAllResolvedResult{ArchivedCount: count}, nil
}

// UnarchiveTicket is the resolver for the unarchiveTicket field.
func (r *mutationResolver) UnarchiveTicket(ctx context.Context, id string) (*ticket.Ticket, error) {
	updatedTicket, err := r.uc.UnarchiveTicket(ctx, types.TicketID(id))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to unarchive ticket")
	}

	return updatedTicket, nil
}

// UpdateTicketConclusion is the resolver for the updateTicketConclusion field.
func (r *mutationResolver) UpdateTicketConclusion(ctx context.Context, id string, conclusion string, reason string) (*ticket.Ticket, error) {
	// Validate conclusion value
	alertConclusion := types.AlertConclusion(conclusion)
	if err := alertConclusion.Validate(); err != nil {
		return nil, goerr.Wrap(err, "invalid conclusion", goerr.V("conclusion", conclusion))
	}

	// Call the use case to update ticket conclusion with Slack notification
	updatedTicket, err := r.uc.UpdateTicketConclusion(ctx, types.TicketID(id), alertConclusion, reason)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to update ticket conclusion")
	}

	return updatedTicket, nil
}

// UpdateTicket is the resolver for the updateTicket field.
func (r *mutationResolver) UpdateTicket(ctx context.Context, id string, title string, description *string) (*ticket.Ticket, error) {
	// Extract user information from authentication context
	token, err := auth.TokenFromContext(ctx)
	if err != nil {
		return nil, goerr.Wrap(err, "authentication required")
	}

	// Create user from authentication token
	user := &slack.User{
		ID:   token.Sub,
		Name: token.Name,
	}

	// Set default value for description if not provided
	desc := ""
	if description != nil {
		desc = *description
	}

	// Call the use case to update ticket
	updatedTicket, err := r.uc.UpdateTicket(ctx, types.TicketID(id), title, desc, user)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to update ticket")
	}

	return updatedTicket, nil
}

// CreateTicket is the resolver for the createTicket field.
func (r *mutationResolver) CreateTicket(ctx context.Context, title string, description string, isTest *bool) (*ticket.Ticket, error) {
	// Extract user information from authentication context
	token, err := auth.TokenFromContext(ctx)
	if err != nil {
		return nil, goerr.Wrap(err, "authentication required")
	}

	// Create user from authentication token
	user := &slack.User{
		ID:   token.Sub,
		Name: token.Name,
	}

	// Set default value for isTest if not provided
	testFlag := false
	if isTest != nil {
		testFlag = *isTest
	}

	// Call the use case to create manual ticket
	newTicket, err := r.uc.CreateManualTicketWithTest(ctx, title, description, user, testFlag)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to create ticket")
	}

	return newTicket, nil
}

// CreateTicketFromAlerts is the resolver for the createTicketFromAlerts field.
func (r *mutationResolver) CreateTicketFromAlerts(ctx context.Context, alertIds []string, title *string, description *string) (*ticket.Ticket, error) {
	// Extract user information from authentication context
	token, err := auth.TokenFromContext(ctx)
	if err != nil {
		return nil, goerr.Wrap(err, "authentication required")
	}

	// Create user from authentication token
	user := &slack.User{
		ID:   token.Sub,
		Name: token.Name,
	}

	// Convert string IDs to typed IDs
	alertIDsTyped := make([]types.AlertID, len(alertIds))
	for i, id := range alertIds {
		alertIDsTyped[i] = types.AlertID(id)
	}

	// Prepare title and description
	titleStr := ""
	if title != nil {
		titleStr = *title
	}
	descStr := ""
	if description != nil {
		descStr = *description
	}

	// For auto-generation when title is empty
	if titleStr == "" {
		createdTicket, err := r.uc.CreateTicketFromAlerts(ctx, alertIDsTyped, user, nil)
		if err != nil {
			return nil, goerr.Wrap(err, "failed to create ticket from alerts")
		}
		return createdTicket, nil
	}

	// When title is provided, create a manual ticket first, then bind alerts
	createdTicket, err := r.uc.CreateManualTicket(ctx, titleStr, descStr, user)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to create manual ticket")
	}

	// Bind alerts to the created ticket
	err = r.uc.BindAlertsToTicket(ctx, createdTicket.ID, alertIDsTyped)
	if err != nil {
		// If binding fails, we should ideally delete the ticket, but for now just return error
		return nil, goerr.Wrap(err, "failed to bind alerts to ticket")
	}

	// Get the updated ticket with alerts
	updatedTicket, err := r.repo.GetTicket(ctx, createdTicket.ID)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get updated ticket")
	}

	return updatedTicket, nil
}

// BindAlertsToTicket is the resolver for the bindAlertsToTicket field.
func (r *mutationResolver) BindAlertsToTicket(ctx context.Context, ticketID string, alertIds []string) (*ticket.Ticket, error) {
	// Convert string IDs to typed IDs
	alertIDsTyped := make([]types.AlertID, len(alertIds))
	for i, id := range alertIds {
		alertIDsTyped[i] = types.AlertID(id)
	}

	// Bind alerts to ticket using UseCase
	err := r.uc.BindAlertsToTicket(ctx, types.TicketID(ticketID), alertIDsTyped)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to bind alerts to ticket")
	}

	// Get updated ticket
	updatedTicket, err := r.repo.GetTicket(ctx, types.TicketID(ticketID))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get updated ticket")
	}

	return updatedTicket, nil
}

// UpdateAlertTags is the resolver for the updateAlertTags field.
func (r *mutationResolver) UpdateAlertTags(ctx context.Context, alertID string, tagIds []string) (*alert.Alert, error) {
	if r.uc.TagUC == nil {
		return nil, goerr.New("tag service not configured")
	}

	a, err := r.uc.TagUC.UpdateAlertTagsByID(ctx, types.AlertID(alertID), tagIds)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to update alert tags")
	}

	return a, nil
}

// UpdateTicketTags is the resolver for the updateTicketTags field.
func (r *mutationResolver) UpdateTicketTags(ctx context.Context, ticketID string, tagIds []string) (*ticket.Ticket, error) {
	if r.uc.TagUC == nil {
		return nil, goerr.New("tag service not configured")
	}

	t, err := r.uc.TagUC.UpdateTicketTagsByID(ctx, types.TicketID(ticketID), tagIds)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to update ticket tags")
	}

	return t, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, name string) (*graphql1.TagMetadata, error) {
	if r.uc.TagUC == nil {
		return nil, goerr.New("tag service not configured")
	}

	tag, err := r.uc.TagUC.CreateTag(ctx, name)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to create tag")
	}

	var desc *string
	if tag.Description != "" {
		desc = &tag.Description
	}

	return &graphql1.TagMetadata{
		ID:          tag.ID,
		Name:        string(tag.Name),
		Description: desc,
		Color:       tag.Color,
		CreatedAt:   tag.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt:   tag.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id string) (bool, error) {
	if r.uc.TagUC == nil {
		return false, goerr.New("tag service not configured")
	}

	err := r.uc.TagUC.DeleteTagByID(ctx, id)
	if err != nil {
		return false, goerr.Wrap(err, "failed to delete tag")
	}

	return true, nil
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, input graphql1.UpdateTagInput) (*graphql1.TagMetadata, error) {
	if r.uc.TagUC == nil {
		return nil, goerr.New("tag service not configured")
	}

	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	tag, err := r.uc.TagUC.UpdateTag(ctx, input.ID, input.Name, input.Color, description)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to update tag")
	}

	var desc *string
	if tag.Description != "" {
		desc = &tag.Description
	}

	return &graphql1.TagMetadata{
		ID:          tag.ID,
		Name:        tag.Name,
		Description: desc,
		Color:       tag.Color,
		CreatedAt:   tag.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt:   tag.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}

// DeclineAlerts is the resolver for the declineAlerts field.
func (r *mutationResolver) DeclineAlerts(ctx context.Context, ids []string) ([]*alert.Alert, error) {
	alertIDs := make([]types.AlertID, len(ids))
	for i, id := range ids {
		alertIDs[i] = types.AlertID(id)
	}

	results, err := r.uc.DeclineAlerts(ctx, alertIDs)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to decline alerts")
	}

	return results, nil
}

// ResolveHITLRequest is the resolver for the resolveHITLRequest field.
//
// Persists the user's answer into the hitl.Request row keyed by id,
// which unblocks the hitl.Service.RequestAndWait goroutine that the
// agent pipeline is blocked on. The updated record is returned so the
// caller can reflect RespondedAt / Status back in its UI without a
// second round-trip.
//
// Multi-instance correctness: the Firestore row transition fans out
// through the existing HITL watcher, so the resolution reaches the
// waiting instance regardless of which node served this mutation.
func (r *mutationResolver) ResolveHITLRequest(ctx context.Context, id string, approved bool, answer *string, comment *string) (*graphql1.HITLRequest, error) {
	reqID := types.HITLRequestID(id)
	existing, err := r.repo.GetHITLRequest(ctx, reqID)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to load HITL request", goerr.V("id", id))
	}
	if existing == nil {
		return nil, goerr.New("HITL request not found", goerr.V("id", id))
	}
	if existing.Status != hitlModel.StatusPending {
		return nil, goerr.New("HITL request is not pending; cannot respond",
			goerr.V("id", id), goerr.V("status", existing.Status))
	}

	respondedBy := string(types.UserID(user.FromContext(ctx)))
	status := hitlModel.StatusDenied
	if approved {
		status = hitlModel.StatusApproved
	}
	response := map[string]any{}
	if answer != nil {
		response["answer"] = *answer
	}
	if comment != nil {
		response["comment"] = *comment
	}

	svc := hitlService.New(r.repo)
	if err := svc.Respond(ctx, reqID, status, respondedBy, response); err != nil {
		return nil, goerr.Wrap(err, "failed to record HITL response", goerr.V("id", id))
	}

	updated, err := r.repo.GetHITLRequest(ctx, reqID)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to reload HITL request", goerr.V("id", id))
	}
	if updated == nil {
		return nil, goerr.New("HITL request disappeared after respond", goerr.V("id", id))
	}
	return hitlRequestToGraphQL(updated), nil
}

// RunDiagnosis is the resolver for the runDiagnosis field.
func (r *mutationResolver) RunDiagnosis(ctx context.Context) (*graphql1.Diagnosis, error) {
	diag, err := r.uc.RunDiagnosis(ctx)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to run diagnosis")
	}
	counts, err := r.uc.CountDiagnosisIssues(ctx, diag.ID)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to count diagnosis issues", goerr.V("id", diag.ID))
	}
	return diagnosisToGraphQL(diag, counts), nil
}

// FixDiagnosis is the resolver for the fixDiagnosis field.
func (r *mutationResolver) FixDiagnosis(ctx context.Context, id string) (*graphql1.Diagnosis, error) {
	diagID := types.DiagnosisID(id)
	diag, err := r.uc.FixDiagnosis(ctx, diagID)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to fix diagnosis", goerr.V("id", id))
	}
	counts, err := r.uc.CountDiagnosisIssues(ctx, diag.ID)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to count diagnosis issues", goerr.V("id", id))
	}
	return diagnosisToGraphQL(diag, counts), nil
}

// ReprocessQueuedAlert is the resolver for the reprocessQueuedAlert field.
func (r *mutationResolver) ReprocessQueuedAlert(ctx context.Context, id string) (*alert.ReprocessJob, error) {
	job, err := r.uc.ReprocessQueuedAlert(ctx, types.QueuedAlertID(id))
	if err != nil {
		return nil, err
	}
	return job, nil
}

// DiscardQueuedAlerts is the resolver for the discardQueuedAlerts field.
func (r *mutationResolver) DiscardQueuedAlerts(ctx context.Context, ids []string) (bool, error) {
	queuedAlertIDs := make([]types.QueuedAlertID, len(ids))
	for i, id := range ids {
		queuedAlertIDs[i] = types.QueuedAlertID(id)
	}
	if err := r.uc.DiscardQueuedAlerts(ctx, queuedAlertIDs); err != nil {
		return false, err
	}
	return true, nil
}

// DiscardQueuedAlertsByFilter is the resolver for the discardQueuedAlertsByFilter field.
func (r *mutationResolver) DiscardQueuedAlertsByFilter(ctx context.Context, keyword *string) (int, error) {
	return r.uc.DiscardQueuedAlertsByFilter(ctx, keyword)
}

// ReprocessQueuedAlertsByFilter is the resolver for the reprocessQueuedAlertsByFilter field.
func (r *mutationResolver) ReprocessQueuedAlertsByFilter(ctx context.Context, keyword *string) (*alert.ReprocessBatchJob, error) {
	return r.uc.ReprocessQueuedAlertsByFilter(ctx, keyword)
}

// CreateKnowledge is the resolver for the createKnowledge field.
func (r *mutationResolver) CreateKnowledge(ctx context.Context, input graphql1.CreateKnowledgeInput) (*graphql1.Knowledge, error) {
	svc := r.knowledgeSvc
	if svc == nil {
		return nil, fmt.Errorf("knowledge service not configured")
	}
	tagIDs := make([]types.KnowledgeTagID, len(input.Tags))
	for i, t := range input.Tags {
		tagIDs[i] = types.KnowledgeTagID(t)
	}
	var ticketID types.TicketID
	if input.TicketID != nil {
		ticketID = types.TicketID(*input.TicketID)
	}
	k := &knowledgeModel.Knowledge{
		Category: types.KnowledgeCategory(input.Category),
		Title:    input.Title,
		Claim:    input.Claim,
		Tags:     tagIDs,
		Author:   authFromContext(ctx),
	}
	if err := svc.SaveKnowledge(ctx, k, input.Message, ticketID); err != nil {
		return nil, err
	}
	return knowledgeToGraphQL(ctx, r.Resolver, k), nil
}

// UpdateKnowledge is the resolver for the updateKnowledge field.
func (r *mutationResolver) UpdateKnowledge(ctx context.Context, input graphql1.UpdateKnowledgeInput) (*graphql1.Knowledge, error) {
	svc := r.knowledgeSvc
	if svc == nil {
		return nil, fmt.Errorf("knowledge service not configured")
	}
	existing, err := svc.GetKnowledge(ctx, types.KnowledgeID(input.ID))
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, fmt.Errorf("knowledge not found: %s", input.ID)
	}
	tagIDs := make([]types.KnowledgeTagID, len(input.Tags))
	for i, t := range input.Tags {
		tagIDs[i] = types.KnowledgeTagID(t)
	}
	var ticketID types.TicketID
	if input.TicketID != nil {
		ticketID = types.TicketID(*input.TicketID)
	}
	existing.Title = input.Title
	existing.Claim = input.Claim
	existing.Tags = tagIDs
	existing.Author = authFromContext(ctx)
	if err := svc.SaveKnowledge(ctx, existing, input.Message, ticketID); err != nil {
		return nil, err
	}
	return knowledgeToGraphQL(ctx, r.Resolver, existing), nil
}

// DeleteKnowledge is the resolver for the deleteKnowledge field.
func (r *mutationResolver) DeleteKnowledge(ctx context.Context, id string, reason string) (bool, error) {
	svc := r.knowledgeSvc
	if svc == nil {
		return false, fmt.Errorf("knowledge service not configured")
	}
	if err := svc.DeleteKnowledge(ctx, types.KnowledgeID(id), reason, authFromContext(ctx), ""); err != nil {
		return false, err
	}
	return true, nil
}

// CreateKnowledgeTag is the resolver for the createKnowledgeTag field.
func (r *mutationResolver) CreateKnowledgeTag(ctx context.Context, input graphql1.CreateKnowledgeTagInput) (*graphql1.KnowledgeTag, error) {
	svc := r.knowledgeSvc
	if svc == nil {
		return nil, fmt.Errorf("knowledge service not configured")
	}
	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}
	tag, err := svc.CreateTag(ctx, input.Name, desc)
	if err != nil {
		return nil, err
	}
	return knowledgeTagToGraphQL(tag), nil
}

// UpdateKnowledgeTag is the resolver for the updateKnowledgeTag field.
func (r *mutationResolver) UpdateKnowledgeTag(ctx context.Context, input graphql1.UpdateKnowledgeTagInput) (*graphql1.KnowledgeTag, error) {
	svc := r.knowledgeSvc
	if svc == nil {
		return nil, fmt.Errorf("knowledge service not configured")
	}
	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}
	tag, err := svc.UpdateTag(ctx, types.KnowledgeTagID(input.ID), input.Name, desc)
	if err != nil {
		return nil, err
	}
	return knowledgeTagToGraphQL(tag), nil
}

// DeleteKnowledgeTag is the resolver for the deleteKnowledgeTag field.
func (r *mutationResolver) DeleteKnowledgeTag(ctx context.Context, id string) (bool, error) {
	svc := r.knowledgeSvc
	if svc == nil {
		return false, fmt.Errorf("knowledge service not configured")
	}
	if err := svc.DeleteTag(ctx, types.KnowledgeTagID(id)); err != nil {
		return false, err
	}
	return true, nil
}

// MergeKnowledgeTags is the resolver for the mergeKnowledgeTags field.
func (r *mutationResolver) MergeKnowledgeTags(ctx context.Context, oldID string, newID string) (bool, error) {
	svc := r.knowledgeSvc
	if svc == nil {
		return false, fmt.Errorf("knowledge service not configured")
	}
	if err := svc.MergeTags(ctx, types.KnowledgeTagID(oldID), types.KnowledgeTagID(newID)); err != nil {
		return false, err
	}
	return true, nil
}

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, id string) (*ticket.Ticket, error) {
	t, err := r.repo.GetTicket(ctx, types.TicketID(id))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get ticket")
	}
	return t, nil
}

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context, statuses []string, keyword *string, assigneeID *string, offset *int, limit *int) (*graphql1.TicketsResponse, error) {
	var ticketStatuses []types.TicketStatus
	for _, s := range statuses {
		status := types.TicketStatus(s)
		if err := status.Validate(); err != nil {
			return nil, goerr.Wrap(err, "invalid ticket status", goerr.V("status", s))
		}
		ticketStatuses = append(ticketStatuses, status)
	}

	var offsetVal, limitVal int
	if offset != nil {
		offsetVal = *offset
	}
	if limit != nil {
		limitVal = *limit
	}

	var keywordVal, assigneeIDVal string
	if keyword != nil {
		keywordVal = *keyword
	}
	if assigneeID != nil {
		assigneeIDVal = *assigneeID
	}

	tickets, err := r.repo.GetTicketsByStatus(ctx, ticketStatuses, keywordVal, assigneeIDVal, offsetVal, limitVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to list tickets")
	}

	totalCount, err := r.repo.CountTicketsByStatus(ctx, ticketStatuses, keywordVal, assigneeIDVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to count tickets")
	}

	return &graphql1.TicketsResponse{
		Tickets:    tickets,
		TotalCount: totalCount,
	}, nil
}

// SimilarTickets is the resolver for the similarTickets field.
func (r *queryResolver) SimilarTickets(ctx context.Context, ticketID string, threshold float64, offset *int, limit *int) (*graphql1.TicketsResponse, error) {
	// Get target ticket
	targetTicket, err := r.repo.GetTicket(ctx, types.TicketID(ticketID))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get target ticket")
	}

	// If target ticket has no embedding, return empty results
	if len(targetTicket.Embedding) == 0 {
		return &graphql1.TicketsResponse{
			Tickets:    []*ticket.Ticket{},
			TotalCount: 0,
		}, nil
	}

	// Set default values for offset and limit
	var offsetVal, limitVal int
	if offset != nil {
		offsetVal = *offset
	}
	if limit != nil {
		limitVal = *limit
	} else {
		limitVal = defaultSimilarTicketsLimit
	}

	// Fetch a fixed, large number of nearest neighbors to ensure stable pagination
	candidates, err := r.repo.FindNearestTickets(ctx, targetTicket.Embedding, maxSimilarTicketsCandidates)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to find nearest tickets")
	}

	// Filter by threshold and exclude target ticket to get complete result set
	var filteredTickets []*ticket.Ticket
	for _, candidate := range candidates {
		// Exclude the target ticket itself
		if candidate.ID == targetTicket.ID {
			continue
		}

		// Only include tickets with embeddings
		if len(candidate.Embedding) == 0 {
			continue
		}

		// Calculate cosine similarity and apply threshold
		similarity := cosineSimilarity(targetTicket.Embedding, candidate.Embedding)
		if float64(similarity) >= threshold {
			filteredTickets = append(filteredTickets, candidate)
		}
	}

	// Calculate correct total count from complete filtered result set
	totalCount := len(filteredTickets)

	// Apply pagination to the complete filtered result set
	start := offsetVal
	if start > len(filteredTickets) {
		start = len(filteredTickets)
	}

	end := start + limitVal
	if end > len(filteredTickets) {
		end = len(filteredTickets)
	}

	result := filteredTickets[start:end]

	return &graphql1.TicketsResponse{
		Tickets:    result,
		TotalCount: totalCount,
	}, nil
}

// SimilarTicketsForAlert is the resolver for the similarTicketsForAlert field.
func (r *queryResolver) SimilarTicketsForAlert(ctx context.Context, alertID string, threshold float64, offset *int, limit *int) (*graphql1.TicketsResponse, error) {
	// Set default values for offset and limit
	var offsetVal, limitVal int
	if offset != nil {
		offsetVal = *offset
	}
	if limit != nil {
		limitVal = *limit
	} else {
		limitVal = defaultSimilarTicketsLimit
	}

	// Delegate to usecase
	tickets, totalCount, err := r.uc.GetSimilarTicketsForAlert(ctx, types.AlertID(alertID), threshold, offsetVal, limitVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get similar tickets for alert")
	}

	return &graphql1.TicketsResponse{
		Tickets:    tickets,
		TotalCount: totalCount,
	}, nil
}

// Alert is the resolver for the alert field.
func (r *queryResolver) Alert(ctx context.Context, id string) (*alert.Alert, error) {
	a, err := r.repo.GetAlert(ctx, types.AlertID(id))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get alert")
	}
	return a, nil
}

// Alerts is the resolver for the alerts field.
func (r *queryResolver) Alerts(ctx context.Context, offset *int, limit *int, status *alert.AlertStatus) (*graphql1.AlertsResponse, error) {
	var offsetVal, limitVal int
	if offset != nil {
		offsetVal = *offset
	}
	if limit != nil {
		limitVal = *limit
	}

	// Default (nil) returns ACTIVE for backward compatibility
	if status != nil && *status == alert.AlertStatusDeclined {
		alerts, err := r.repo.GetDeclinedAlerts(ctx, offsetVal, limitVal)
		if err != nil {
			return nil, goerr.Wrap(err, "failed to list declined alerts")
		}

		totalCount, err := r.repo.CountDeclinedAlerts(ctx)
		if err != nil {
			return nil, goerr.Wrap(err, "failed to count declined alerts")
		}

		return &graphql1.AlertsResponse{
			Alerts:     alerts,
			TotalCount: totalCount,
		}, nil
	}

	alerts, err := r.repo.GetAlertWithoutTicket(ctx, offsetVal, limitVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to list alerts")
	}

	totalCount, err := r.repo.CountAlertsWithoutTicket(ctx)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to count alerts")
	}

	return &graphql1.AlertsResponse{
		Alerts:     alerts,
		TotalCount: totalCount,
	}, nil
}

// UnboundAlerts is the resolver for the unboundAlerts field.
func (r *queryResolver) UnboundAlerts(ctx context.Context, threshold *float64, keyword *string, ticketID *string, offset *int, limit *int) (*graphql1.AlertsResponse, error) {
	var offsetVal, limitVal int
	if offset != nil {
		offsetVal = *offset
	}
	if limit != nil {
		limitVal = *limit
	}

	var ticketIDTyped *types.TicketID
	if ticketID != nil && *ticketID != "" {
		tid := types.TicketID(*ticketID)
		ticketIDTyped = &tid
	}

	alerts, totalCount, err := r.uc.GetUnboundAlertsFiltered(ctx, threshold, keyword, ticketIDTyped, offsetVal, limitVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get unbound alerts")
	}

	return &graphql1.AlertsResponse{
		Alerts:     alerts,
		TotalCount: totalCount,
	}, nil
}

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context) (*graphql1.DashboardStats, error) {
	// Get open tickets count and list
	openTickets, err := r.repo.GetTicketsByStatus(ctx, []types.TicketStatus{types.TicketStatusOpen}, "", "", 0, 5)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get open tickets")
	}

	openTicketsCount, err := r.repo.CountTicketsByStatus(ctx, []types.TicketStatus{types.TicketStatusOpen}, "", "")
	if err != nil {
		return nil, goerr.Wrap(err, "failed to count open tickets")
	}

	// Get unbound alerts count (for accurate count, we need to get all first)
	allUnboundAlerts, err := r.repo.GetAlertWithoutTicket(ctx, 0, 0) // Get all for count
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get unbound alerts count")
	}
	unboundAlertsCount := len(allUnboundAlerts)

	// Get only the first 5 unbound alerts
	unboundAlerts, err := r.repo.GetAlertWithoutTicket(ctx, 0, 5)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get unbound alerts")
	}

	// Get declined alerts count
	declinedAlertsCount, err := r.repo.CountDeclinedAlerts(ctx)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to count declined alerts")
	}

	// Get queued alerts count
	queuedAlertsCount, err := r.repo.CountQueuedAlerts(ctx)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to count queued alerts")
	}

	return &graphql1.DashboardStats{
		OpenTicketsCount:    openTicketsCount,
		UnboundAlertsCount:  unboundAlertsCount,
		DeclinedAlertsCount: declinedAlertsCount,
		QueuedAlertsCount:   queuedAlertsCount,
		OpenTickets:         openTickets,
		UnboundAlerts:       unboundAlerts,
	}, nil
}

// Activities is the resolver for the activities field.
func (r *queryResolver) Activities(ctx context.Context, offset *int, limit *int) (*graphql1.ActivitiesResponse, error) {
	const defaultActivitiesLimit = 10
	const maxActivitiesLimit = 50

	// Set default values for offset and limit
	var offsetVal, limitVal int
	if offset != nil {
		offsetVal = *offset
	}
	if limit != nil {
		limitVal = *limit
		if limitVal > maxActivitiesLimit {
			limitVal = maxActivitiesLimit
		}
	} else {
		limitVal = defaultActivitiesLimit
	}

	// Get paginated activities
	activities, err := r.repo.GetActivities(ctx, offsetVal, limitVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get activities")
	}

	// Get total count for pagination
	totalCount, err := r.repo.CountActivities(ctx)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to count activities")
	}

	// Convert to GraphQL activities
	graphqlActivities := make([]*graphql1.Activity, len(activities))
	for i, a := range activities {
		graphqlActivity := &graphql1.Activity{
			ID:        string(a.ID),
			Type:      string(a.Type),
			CreatedAt: a.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		}

		if a.UserID != "" {
			graphqlActivity.UserID = &a.UserID
		}
		if a.AlertID != types.AlertID("") {
			alertID := string(a.AlertID)
			graphqlActivity.AlertID = &alertID
		}
		if a.TicketID != types.TicketID("") {
			ticketID := string(a.TicketID)
			graphqlActivity.TicketID = &ticketID
		}
		if a.CommentID != types.CommentID("") {
			commentID := string(a.CommentID)
			graphqlActivity.CommentID = &commentID
		}
		if a.Metadata != nil {
			metadataBytes, err := json.Marshal(a.Metadata)
			if err == nil {
				metadataStr := string(metadataBytes)
				graphqlActivity.Metadata = &metadataStr
			}
		}

		graphqlActivities[i] = graphqlActivity
	}

	return &graphql1.ActivitiesResponse{
		Activities: graphqlActivities,
		TotalCount: totalCount,
	}, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*graphql1.TagMetadata, error) {
	logging.From(ctx).Info("Tags resolver called", "uc_nil", r.uc == nil)
	if r.uc == nil {
		return nil, goerr.New("use cases not configured")
	}
	if r.uc.TagUC == nil {
		return nil, goerr.New("tag service not configured")
	}

	tags, err := r.uc.TagUC.ListTags(ctx)
	if err != nil {
		logging.From(ctx).Error("Tags resolver: ListTags failed", "error", err)
		return nil, goerr.Wrap(err, "failed to list tags")
	}
	logging.From(ctx).Info("Tags resolver: ListTags returned", "count", len(tags))

	result := make([]*graphql1.TagMetadata, len(tags))
	for i, tag := range tags {
		var desc *string
		if tag.Description != "" {
			desc = &tag.Description
		}

		result[i] = &graphql1.TagMetadata{
			ID:          tag.ID,
			Name:        string(tag.Name),
			Description: desc,
			Color:       tag.Color,
			CreatedAt:   tag.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
			UpdatedAt:   tag.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
		}
	}

	return result, nil
}

// AvailableTagColors is the resolver for the availableTagColors field.
func (r *queryResolver) AvailableTagColors(ctx context.Context) ([]string, error) {
	if r.uc.TagUC == nil {
		return nil, goerr.New("tag service not configured")
	}

	colors, err := r.uc.TagUC.GetAvailableColors()
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get available colors")
	}

	return colors, nil
}

// AvailableTagColorNames is the resolver for the availableTagColorNames field.
func (r *queryResolver) AvailableTagColorNames(ctx context.Context) ([]string, error) {
	if r.uc.TagUC == nil {
		return nil, goerr.New("tag service not configured")
	}

	names, err := r.uc.TagUC.GetAvailableColorNames()
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get available color names")
	}

	return names, nil
}

// TicketSessions is the resolver for the ticketSessions field.
func (r *queryResolver) TicketSessions(ctx context.Context, ticketID string) ([]*graphql1.Session, error) {
	sessions, err := r.repo.GetSessionsByTicket(ctx, types.TicketID(ticketID))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get sessions by ticket", goerr.V("ticketID", ticketID))
	}

	// Convert to GraphQL model
	result := make([]*graphql1.Session, len(sessions))
	for i, s := range sessions {
		result[i] = toGraphQLSession(s)
	}

	return result, nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id string) (*graphql1.Session, error) {
	s, err := r.repo.GetSession(ctx, types.SessionID(id))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get session", goerr.V("sessionID", id))
	}

	if s == nil {
		return nil, nil
	}

	return toGraphQLSession(s), nil
}

// SessionMessages is the resolver for the sessionMessages field.
func (r *queryResolver) SessionMessages(ctx context.Context, sessionID string) ([]*graphql1.SessionMessage, error) {
	messages, err := r.repo.GetSessionMessages(ctx, types.SessionID(sessionID))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get session messages", goerr.V("sessionID", sessionID))
	}

	result := make([]*graphql1.SessionMessage, len(messages))
	for i, m := range messages {
		result[i] = toGraphQLSessionMessage(m)
		resolveAuthorDisplayName(ctx, r.slackService, result[i])
		resolveMessageMentions(ctx, r.mrkdwnConv, result[i])
	}

	return result, nil
}

// TicketSessionMessages is the resolver for the ticketSessionMessages field.
// chat-session-redesign Phase 3.4: superset of the legacy ticketComments
// query. Filters are optional; omit them to return every message across
// every Session attached to the ticket.
func (r *queryResolver) TicketSessionMessages(ctx context.Context, ticketID string, source *string, typeArg *string, offset *int, limit *int) ([]*graphql1.SessionMessage, error) {
	var sourceFilter *session.SessionSource
	if source != nil && *source != "" {
		s := session.SessionSource(*source)
		if !s.Valid() {
			return nil, goerr.New("invalid source value", goerr.V("source", *source))
		}
		sourceFilter = &s
	}
	var typeFilter *session.MessageType
	if typeArg != nil && *typeArg != "" {
		mt := session.MessageType(*typeArg)
		if !mt.Valid() {
			return nil, goerr.New("invalid type value", goerr.V("type", *typeArg))
		}
		typeFilter = &mt
	}

	limitVal := 0
	if limit != nil {
		limitVal = *limit
	}
	offsetVal := 0
	if offset != nil {
		offsetVal = *offset
	}

	msgs, err := r.repo.GetTicketSessionMessages(ctx, types.TicketID(ticketID), sourceFilter, typeFilter, limitVal, offsetVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get ticket session messages",
			goerr.V("ticketID", ticketID))
	}

	result := make([]*graphql1.SessionMessage, len(msgs))
	for i, m := range msgs {
		result[i] = toGraphQLSessionMessage(m)
		resolveAuthorDisplayName(ctx, r.slackService, result[i])
		resolveMessageMentions(ctx, r.mrkdwnConv, result[i])
	}
	return result, nil
}

// Diagnoses is the resolver for the diagnoses field.
func (r *queryResolver) Diagnoses(ctx context.Context, offset *int, limit *int) (*graphql1.DiagnosesResponse, error) {
	offsetVal := 0
	if offset != nil {
		offsetVal = *offset
	}
	limitVal := 20
	if limit != nil {
		limitVal = *limit
	}

	diagnoses, total, err := r.uc.GetDiagnoses(ctx, offsetVal, limitVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to list diagnoses")
	}

	// Batch-fetch issue counts to avoid N+1 queries.
	ids := make([]types.DiagnosisID, len(diagnoses))
	for i, d := range diagnoses {
		ids[i] = d.ID
	}
	countsMap, err := r.uc.BatchCountDiagnosisIssues(ctx, ids)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to batch count diagnosis issues")
	}

	gqlDiagnoses := make([]*graphql1.Diagnosis, 0, len(diagnoses))
	for _, d := range diagnoses {
		gqlDiagnoses = append(gqlDiagnoses, diagnosisToGraphQL(d, countsMap[d.ID]))
	}

	return &graphql1.DiagnosesResponse{
		Diagnoses:  gqlDiagnoses,
		TotalCount: total,
	}, nil
}

// Diagnosis is the resolver for the diagnosis field.
func (r *queryResolver) Diagnosis(ctx context.Context, id string) (*graphql1.Diagnosis, error) {
	diag, err := r.uc.GetDiagnosis(ctx, types.DiagnosisID(id))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get diagnosis", goerr.V("id", id))
	}
	if diag == nil {
		return nil, nil
	}
	counts, err := r.uc.CountDiagnosisIssues(ctx, diag.ID)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to count diagnosis issues", goerr.V("id", id))
	}
	return diagnosisToGraphQL(diag, counts), nil
}

// DiagnosisIssues is the resolver for the diagnosisIssues field.
func (r *queryResolver) DiagnosisIssues(ctx context.Context, diagnosisID string, offset *int, limit *int, status *string, ruleID *string) (*graphql1.DiagnosisIssuesResponse, error) {
	offsetVal := 0
	if offset != nil {
		offsetVal = *offset
	}
	limitVal := 50
	if limit != nil {
		limitVal = *limit
	}

	var statusFilter *diagnosismodel.IssueStatus
	if status != nil && *status != "" {
		s := diagnosismodel.IssueStatus(*status)
		statusFilter = &s
	}
	var ruleIDFilter *diagnosismodel.RuleID
	if ruleID != nil && *ruleID != "" {
		rid := diagnosismodel.RuleID(*ruleID)
		ruleIDFilter = &rid
	}

	issues, total, err := r.uc.GetDiagnosisIssues(ctx, types.DiagnosisID(diagnosisID), offsetVal, limitVal, statusFilter, ruleIDFilter)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to list diagnosis issues", goerr.V("diagnosis_id", diagnosisID))
	}

	gqlIssues := make([]*graphql1.DiagnosisIssue, 0, len(issues))
	for _, iss := range issues {
		gqlIssues = append(gqlIssues, issueToGraphQL(iss))
	}

	return &graphql1.DiagnosisIssuesResponse{
		Issues:     gqlIssues,
		TotalCount: total,
	}, nil
}

// QueuedAlerts is the resolver for the queuedAlerts field.
func (r *queryResolver) QueuedAlerts(ctx context.Context, keyword *string, offset *int, limit *int) (*graphql1.QueuedAlertsResponse, error) {
	offsetVal := 0
	if offset != nil {
		offsetVal = *offset
	}
	limitVal := 20
	if limit != nil {
		limitVal = *limit
	}

	var alerts []*alert.QueuedAlert
	var totalCount int
	var err error

	if keyword != nil && *keyword != "" {
		alerts, totalCount, err = r.repo.SearchQueuedAlerts(ctx, *keyword, offsetVal, limitVal)
	} else {
		alerts, err = r.repo.ListQueuedAlerts(ctx, offsetVal, limitVal)
		if err == nil {
			totalCount, err = r.repo.CountQueuedAlerts(ctx)
		}
	}
	if err != nil {
		return nil, goerr.Wrap(err, "failed to list queued alerts")
	}

	return &graphql1.QueuedAlertsResponse{
		Alerts:     alerts,
		TotalCount: totalCount,
	}, nil
}

// ReprocessJob is the resolver for the reprocessJob field.
func (r *queryResolver) ReprocessJob(ctx context.Context, id string) (*alert.ReprocessJob, error) {
	job, err := r.repo.GetReprocessJob(ctx, types.ReprocessJobID(id))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get reprocess job", goerr.V("id", id))
	}
	return job, nil
}

// ReprocessBatchJob is the resolver for the reprocessBatchJob field.
func (r *queryResolver) ReprocessBatchJob(ctx context.Context, id string) (*alert.ReprocessBatchJob, error) {
	batchJobID := types.ReprocessBatchJobID(id)
	job, err := r.repo.GetReprocessBatchJob(ctx, batchJobID)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get reprocess batch job", goerr.V("id", id))
	}
	return job, nil
}

// Knowledges is the resolver for the knowledges field.
func (r *queryResolver) Knowledges(ctx context.Context, category *string, tags []string, keyword *string) ([]*graphql1.Knowledge, error) {
	if r.knowledgeSvc == nil {
		return nil, fmt.Errorf("knowledge service not configured")
	}

	// Fetch all knowledges (Web UI listing)
	all, err := r.repo.ListAllKnowledges(ctx)
	if err != nil {
		return nil, err
	}

	// Filter by category if specified
	if category != nil && *category != "" {
		filtered := make([]*knowledgeModel.Knowledge, 0)
		for _, k := range all {
			if string(k.Category) == *category {
				filtered = append(filtered, k)
			}
		}
		all = filtered
	}

	// Filter by tags if specified
	if len(tags) > 0 {
		tagSet := make(map[string]bool, len(tags))
		for _, t := range tags {
			tagSet[t] = true
		}
		filtered := make([]*knowledgeModel.Knowledge, 0)
		for _, k := range all {
			for _, t := range k.Tags {
				if tagSet[t.String()] {
					filtered = append(filtered, k)
					break
				}
			}
		}
		all = filtered
	}

	// Filter by keyword (partial match on title and claim)
	if keyword != nil && *keyword != "" {
		kw := strings.ToLower(*keyword)
		filtered := make([]*knowledgeModel.Knowledge, 0)
		for _, k := range all {
			if strings.Contains(strings.ToLower(k.Title), kw) || strings.Contains(strings.ToLower(k.Claim), kw) {
				filtered = append(filtered, k)
			}
		}
		all = filtered
	}

	result := make([]*graphql1.Knowledge, len(all))
	for i, k := range all {
		result[i] = knowledgeToGraphQL(ctx, r.Resolver, k)
	}
	return result, nil
}

// Knowledge is the resolver for the knowledge field.
func (r *queryResolver) Knowledge(ctx context.Context, id string) (*graphql1.Knowledge, error) {
	svc := r.knowledgeSvc
	if svc == nil {
		return nil, fmt.Errorf("knowledge service not configured")
	}
	k, err := svc.GetKnowledge(ctx, types.KnowledgeID(id))
	if err != nil {
		return nil, err
	}
	if k == nil {
		return nil, nil
	}
	return knowledgeToGraphQL(ctx, r.Resolver, k), nil
}

// KnowledgeLogs is the resolver for the knowledgeLogs field.
func (r *queryResolver) KnowledgeLogs(ctx context.Context, knowledgeID string) ([]*graphql1.KnowledgeLog, error) {
	svc := r.knowledgeSvc
	if svc == nil {
		return nil, fmt.Errorf("knowledge service not configured")
	}
	logs, err := svc.ListKnowledgeLogs(ctx, types.KnowledgeID(knowledgeID))
	if err != nil {
		return nil, err
	}
	result := make([]*graphql1.KnowledgeLog, len(logs))
	for i, l := range logs {
		result[i] = knowledgeLogToGraphQL(l)
	}
	return result, nil
}

// KnowledgeTags is the resolver for the knowledgeTags field.
func (r *queryResolver) KnowledgeTags(ctx context.Context) ([]*graphql1.KnowledgeTag, error) {
	svc := r.knowledgeSvc
	if svc == nil {
		return nil, fmt.Errorf("knowledge service not configured")
	}
	tags, err := svc.ListTags(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*graphql1.KnowledgeTag, len(tags))
	for i, t := range tags {
		result[i] = knowledgeTagToGraphQL(t)
	}
	return result, nil
}

// ID is the resolver for the id field.
func (r *queuedAlertResolver) ID(ctx context.Context, obj *alert.QueuedAlert) (string, error) {
	return string(obj.ID), nil
}

// Schema is the resolver for the schema field.
func (r *queuedAlertResolver) Schema(ctx context.Context, obj *alert.QueuedAlert) (string, error) {
	return string(obj.Schema), nil
}

// Data is the resolver for the data field.
func (r *queuedAlertResolver) Data(ctx context.Context, obj *alert.QueuedAlert) (string, error) {
	jsonBytes, err := json.Marshal(obj.Data)
	if err != nil {
		return "", goerr.Wrap(err, "failed to marshal queued alert data to JSON")
	}
	return string(jsonBytes), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *queuedAlertResolver) CreatedAt(ctx context.Context, obj *alert.QueuedAlert) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// ID is the resolver for the id field.
func (r *reprocessBatchJobResolver) ID(ctx context.Context, obj *alert.ReprocessBatchJob) (string, error) {
	return string(obj.ID), nil
}

// Status is the resolver for the status field.
func (r *reprocessBatchJobResolver) Status(ctx context.Context, obj *alert.ReprocessBatchJob) (graphql1.ReprocessJobStatus, error) {
	switch obj.Status {
	case types.ReprocessJobStatusPending:
		return graphql1.ReprocessJobStatusPending, nil
	case types.ReprocessJobStatusRunning:
		return graphql1.ReprocessJobStatusRunning, nil
	case types.ReprocessJobStatusCompleted:
		return graphql1.ReprocessJobStatusCompleted, nil
	case types.ReprocessJobStatusFailed:
		return graphql1.ReprocessJobStatusFailed, nil
	default:
		return graphql1.ReprocessJobStatusPending, nil
	}
}

// CreatedAt is the resolver for the createdAt field.
func (r *reprocessBatchJobResolver) CreatedAt(ctx context.Context, obj *alert.ReprocessBatchJob) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *reprocessBatchJobResolver) UpdatedAt(ctx context.Context, obj *alert.ReprocessBatchJob) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// ID is the resolver for the id field.
func (r *reprocessJobResolver) ID(ctx context.Context, obj *alert.ReprocessJob) (string, error) {
	return string(obj.ID), nil
}

// QueuedAlertID is the resolver for the queuedAlertID field.
func (r *reprocessJobResolver) QueuedAlertID(ctx context.Context, obj *alert.ReprocessJob) (string, error) {
	return string(obj.QueuedAlertID), nil
}

// Status is the resolver for the status field.
func (r *reprocessJobResolver) Status(ctx context.Context, obj *alert.ReprocessJob) (graphql1.ReprocessJobStatus, error) {
	switch obj.Status {
	case types.ReprocessJobStatusPending:
		return graphql1.ReprocessJobStatusPending, nil
	case types.ReprocessJobStatusRunning:
		return graphql1.ReprocessJobStatusRunning, nil
	case types.ReprocessJobStatusCompleted:
		return graphql1.ReprocessJobStatusCompleted, nil
	case types.ReprocessJobStatusFailed:
		return graphql1.ReprocessJobStatusFailed, nil
	default:
		return graphql1.ReprocessJobStatusPending, nil
	}
}

// CreatedAt is the resolver for the createdAt field.
func (r *reprocessJobResolver) CreatedAt(ctx context.Context, obj *alert.ReprocessJob) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *reprocessJobResolver) UpdatedAt(ctx context.Context, obj *alert.ReprocessJob) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// User is the resolver for the user field.
func (r *sessionResolver) User(ctx context.Context, obj *graphql1.Session) (*graphql1.User, error) {
	if obj.UserID == nil || *obj.UserID == "" {
		return nil, nil
	}

	// Use DataLoader to efficiently fetch user
	return GetUser(ctx, *obj.UserID)
}

// ID is the resolver for the id field.
func (r *ticketResolver) ID(ctx context.Context, obj *ticket.Ticket) (string, error) {
	return string(obj.ID), nil
}

// Status is the resolver for the status field.
func (r *ticketResolver) Status(ctx context.Context, obj *ticket.Ticket) (string, error) {
	return string(obj.Status), nil
}

// Assignee is the resolver for the assignee field.
func (r *ticketResolver) Assignee(ctx context.Context, obj *ticket.Ticket) (*graphql1.User, error) {
	if obj.Assignee == nil {
		return nil, nil
	}
	return &graphql1.User{
		ID:   obj.Assignee.ID,
		Name: obj.Assignee.Name,
	}, nil
}

// Alerts is the resolver for the alerts field.
func (r *ticketResolver) Alerts(ctx context.Context, obj *ticket.Ticket) ([]*alert.Alert, error) {
	alerts, err := r.repo.BatchGetAlerts(ctx, obj.AlertIDs)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get ticket alerts")
	}
	return alerts, nil
}

// AlertsPaginated is the resolver for the alertsPaginated field.
func (r *ticketResolver) AlertsPaginated(ctx context.Context, obj *ticket.Ticket, offset *int, limit *int) (*graphql1.AlertsResponse, error) {
	// Set default values
	defaultOffset := 0
	defaultLimit := 5

	if offset == nil {
		offset = &defaultOffset
	}
	if limit == nil {
		limit = &defaultLimit
	}

	// Get total count
	totalCount := len(obj.AlertIDs)

	// Calculate pagination bounds
	start := *offset
	end := start + *limit

	var paginatedAlertIDs []types.AlertID
	if start < totalCount {
		if end > totalCount {
			end = totalCount
		}
		paginatedAlertIDs = obj.AlertIDs[start:end]
	}

	// Get alerts for this page
	alerts, err := r.repo.BatchGetAlerts(ctx, paginatedAlertIDs)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get paginated ticket alerts")
	}

	return &graphql1.AlertsResponse{
		Alerts:     alerts,
		TotalCount: totalCount,
	}, nil
}

// AlertsCount is the resolver for the alertsCount field.
func (r *ticketResolver) AlertsCount(ctx context.Context, obj *ticket.Ticket) (int, error) {
	return len(obj.AlertIDs), nil
}

// Conclusion is the resolver for the conclusion field.
func (r *ticketResolver) Conclusion(ctx context.Context, obj *ticket.Ticket) (*string, error) {
	if obj.Conclusion == "" {
		return nil, nil
	}
	conclusion := string(obj.Conclusion)
	return &conclusion, nil
}

// SlackLink is the resolver for the slackLink field.
func (r *ticketResolver) SlackLink(ctx context.Context, obj *ticket.Ticket) (*string, error) {
	if obj.SlackThread == nil || r.slackService == nil {
		return nil, nil
	}

	slackURL := r.slackService.ToExternalMsgURL(obj.SlackThread.ChannelID, obj.SlackThread.ThreadID)
	if slackURL == "" {
		return nil, nil
	}

	return &slackURL, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *ticketResolver) CreatedAt(ctx context.Context, obj *ticket.Ticket) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *ticketResolver) UpdatedAt(ctx context.Context, obj *ticket.Ticket) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// ResolvedAt is the resolver for the resolvedAt field.
func (r *ticketResolver) ResolvedAt(ctx context.Context, obj *ticket.Ticket) (*string, error) {
	if obj.ResolvedAt == nil {
		return nil, nil
	}
	s := obj.ResolvedAt.Format("2006-01-02T15:04:05Z07:00")
	return &s, nil
}

// ArchivedAt is the resolver for the archivedAt field.
func (r *ticketResolver) ArchivedAt(ctx context.Context, obj *ticket.Ticket) (*string, error) {
	if obj.ArchivedAt == nil {
		return nil, nil
	}
	s := obj.ArchivedAt.Format("2006-01-02T15:04:05Z07:00")
	return &s, nil
}

// Tags is the resolver for the tags field.
func (r *ticketResolver) Tags(ctx context.Context, obj *ticket.Ticket) ([]string, error) {
	if r.uc == nil || len(obj.TagIDs) == 0 {
		return []string{}, nil
	}

	// Use the compatibility method to get tag names
	return obj.GetTagNames(ctx, r.createTagGetter())
}

// TagObjects is the resolver for the tagObjects field.
func (r *ticketResolver) TagObjects(ctx context.Context, obj *ticket.Ticket) ([]*graphql1.TagObject, error) {
	if r.uc == nil || len(obj.TagIDs) == 0 {
		return []*graphql1.TagObject{}, nil
	}

	// Get tag IDs as slice
	tagIDSlice := make([]string, 0, len(obj.TagIDs))
	for tagID := range obj.TagIDs {
		tagIDSlice = append(tagIDSlice, tagID)
	}

	// Get tag metadata using tag getter
	tags, err := r.createTagGetter()(ctx, tagIDSlice)
	if err != nil {
		return nil, err
	}

	// Convert to GraphQL TagObject
	tagObjects := make([]*graphql1.TagObject, 0, len(tags))
	for _, tag := range tags {
		tagObjects = append(tagObjects, &graphql1.TagObject{
			ID:   tag.ID,
			Name: tag.Name,
		})
	}

	return tagObjects, nil
}

// Activity returns ActivityResolver implementation.
func (r *Resolver) Activity() ActivityResolver { return &activityResolver{r} }

// Alert returns AlertResolver implementation.
func (r *Resolver) Alert() AlertResolver { return &alertResolver{r} }

// Finding returns FindingResolver implementation.
func (r *Resolver) Finding() FindingResolver { return &findingResolver{r} }

// Knowledge returns KnowledgeResolver implementation.
func (r *Resolver) Knowledge() KnowledgeResolver { return &knowledgeResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// QueuedAlert returns QueuedAlertResolver implementation.
func (r *Resolver) QueuedAlert() QueuedAlertResolver { return &queuedAlertResolver{r} }

// ReprocessBatchJob returns ReprocessBatchJobResolver implementation.
func (r *Resolver) ReprocessBatchJob() ReprocessBatchJobResolver {
	return &reprocessBatchJobResolver{r}
}

// ReprocessJob returns ReprocessJobResolver implementation.
func (r *Resolver) ReprocessJob() ReprocessJobResolver { return &reprocessJobResolver{r} }

// Session returns SessionResolver implementation.
func (r *Resolver) Session() SessionResolver { return &sessionResolver{r} }

// Ticket returns TicketResolver implementation.
func (r *Resolver) Ticket() TicketResolver { return &ticketResolver{r} }

type activityResolver struct{ *Resolver }
type alertResolver struct{ *Resolver }
type findingResolver struct{ *Resolver }
type knowledgeResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type queuedAlertResolver struct{ *Resolver }
type reprocessBatchJobResolver struct{ *Resolver }
type reprocessJobResolver struct{ *Resolver }
type sessionResolver struct{ *Resolver }
type ticketResolver struct{ *Resolver }
