package usecase

import (
	"context"
	_ "embed"

	"github.com/m-mizutani/goerr/v2"
	"github.com/m-mizutani/gollem"
	"github.com/secmon-lab/warren/pkg/domain/model/alert"
	"github.com/secmon-lab/warren/pkg/domain/model/lang"
	"github.com/secmon-lab/warren/pkg/domain/model/prompt"
	"github.com/secmon-lab/warren/pkg/domain/model/session"
	"github.com/secmon-lab/warren/pkg/domain/model/ticket"
	"github.com/secmon-lab/warren/pkg/domain/types"
	chatpkg "github.com/secmon-lab/warren/pkg/usecase/chat/legacy"
)

// Chat processes a chat message for the specified ticket.
// It delegates to ChatUC (ChatUseCase) for the actual processing.
func (x *UseCases) Chat(ctx context.Context, target *ticket.Ticket, message string) error {
	return x.ChatUC.Execute(ctx, target, message)
}

// collectThreadComments delegates to the chat package exported function.
func (x *UseCases) collectThreadComments(ctx context.Context, ticketID types.TicketID, currentSession *session.Session) []ticket.Comment {
	return chatpkg.CollectThreadComments(ctx, x.repository, ticketID, currentSession)
}

// authorizeAgentRequest delegates to the chat package exported function.
func (x *UseCases) authorizeAgentRequest(ctx context.Context, message string) error {
	return chatpkg.AuthorizeAgentRequest(ctx, x.policyClient, x.noAuthorization, message)
}

//go:embed prompt/ticket_comment.md
var ticketCommentPromptTemplate string

// generateInitialTicketComment generates an LLM-based initial comment for a ticket
func (x *UseCases) generateInitialTicketComment(ctx context.Context, ticketData *ticket.Ticket, alerts alert.Alerts) (string, error) {
	commentPrompt, err := prompt.GenerateWithStruct(ctx, ticketCommentPromptTemplate, map[string]any{
		"ticket": ticketData,
		"alerts": alerts,
		"lang":   lang.From(ctx),
	})
	if err != nil {
		return "", goerr.Wrap(err, "failed to generate comment prompt")
	}

	session, err := x.llmClient.NewSession(ctx)
	if err != nil {
		return "", goerr.Wrap(err, "failed to create LLM session")
	}

	response, err := session.GenerateContent(ctx, gollem.Text(commentPrompt))
	if err != nil {
		return "", goerr.Wrap(err, "failed to generate comment")
	}

	if len(response.Texts) == 0 {
		return "", goerr.New("no comment generated by LLM")
	}

	return response.Texts[0], nil
}
