// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package notify_test

import (
	"context"
	slack_sdk "github.com/slack-go/slack"
	"sync"
)

// slackClientMock is a mock implementation of notify.slackClient.
//
//	func TestSomethingThatUsesslackClient(t *testing.T) {
//
//		// make and configure a mocked notify.slackClient
//		mockedslackClient := &slackClientMock{
//			PostMessageContextFunc: func(ctx context.Context, channelID string, options ...slack_sdk.MsgOption) (string, string, error) {
//				panic("mock out the PostMessageContext method")
//			},
//			UpdateMessageContextFunc: func(ctx context.Context, channelID string, messageID string, options ...slack_sdk.MsgOption) (string, string, string, error) {
//				panic("mock out the UpdateMessageContext method")
//			},
//		}
//
//		// use mockedslackClient in code that requires notify.slackClient
//		// and then make assertions.
//
//	}
type slackClientMock struct {
	// PostMessageContextFunc mocks the PostMessageContext method.
	PostMessageContextFunc func(ctx context.Context, channelID string, options ...slack_sdk.MsgOption) (string, string, error)

	// UpdateMessageContextFunc mocks the UpdateMessageContext method.
	UpdateMessageContextFunc func(ctx context.Context, channelID string, messageID string, options ...slack_sdk.MsgOption) (string, string, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// PostMessageContext holds details about calls to the PostMessageContext method.
		PostMessageContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID string
			// Options is the options argument value.
			Options []slack_sdk.MsgOption
		}
		// UpdateMessageContext holds details about calls to the UpdateMessageContext method.
		UpdateMessageContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID string
			// MessageID is the messageID argument value.
			MessageID string
			// Options is the options argument value.
			Options []slack_sdk.MsgOption
		}
	}
	lockPostMessageContext   sync.RWMutex
	lockUpdateMessageContext sync.RWMutex
}

// PostMessageContext calls PostMessageContextFunc.
func (mock *slackClientMock) PostMessageContext(ctx context.Context, channelID string, options ...slack_sdk.MsgOption) (string, string, error) {
	if mock.PostMessageContextFunc == nil {
		panic("slackClientMock.PostMessageContextFunc: method is nil but slackClient.PostMessageContext was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChannelID string
		Options   []slack_sdk.MsgOption
	}{
		Ctx:       ctx,
		ChannelID: channelID,
		Options:   options,
	}
	mock.lockPostMessageContext.Lock()
	mock.calls.PostMessageContext = append(mock.calls.PostMessageContext, callInfo)
	mock.lockPostMessageContext.Unlock()
	return mock.PostMessageContextFunc(ctx, channelID, options...)
}

// PostMessageContextCalls gets all the calls that were made to PostMessageContext.
// Check the length with:
//
//	len(mockedslackClient.PostMessageContextCalls())
func (mock *slackClientMock) PostMessageContextCalls() []struct {
	Ctx       context.Context
	ChannelID string
	Options   []slack_sdk.MsgOption
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID string
		Options   []slack_sdk.MsgOption
	}
	mock.lockPostMessageContext.RLock()
	calls = mock.calls.PostMessageContext
	mock.lockPostMessageContext.RUnlock()
	return calls
}

// UpdateMessageContext calls UpdateMessageContextFunc.
func (mock *slackClientMock) UpdateMessageContext(ctx context.Context, channelID string, messageID string, options ...slack_sdk.MsgOption) (string, string, string, error) {
	if mock.UpdateMessageContextFunc == nil {
		panic("slackClientMock.UpdateMessageContextFunc: method is nil but slackClient.UpdateMessageContext was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChannelID string
		MessageID string
		Options   []slack_sdk.MsgOption
	}{
		Ctx:       ctx,
		ChannelID: channelID,
		MessageID: messageID,
		Options:   options,
	}
	mock.lockUpdateMessageContext.Lock()
	mock.calls.UpdateMessageContext = append(mock.calls.UpdateMessageContext, callInfo)
	mock.lockUpdateMessageContext.Unlock()
	return mock.UpdateMessageContextFunc(ctx, channelID, messageID, options...)
}

// UpdateMessageContextCalls gets all the calls that were made to UpdateMessageContext.
// Check the length with:
//
//	len(mockedslackClient.UpdateMessageContextCalls())
func (mock *slackClientMock) UpdateMessageContextCalls() []struct {
	Ctx       context.Context
	ChannelID string
	MessageID string
	Options   []slack_sdk.MsgOption
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID string
		MessageID string
		Options   []slack_sdk.MsgOption
	}
	mock.lockUpdateMessageContext.RLock()
	calls = mock.calls.UpdateMessageContext
	mock.lockUpdateMessageContext.RUnlock()
	return calls
}
