// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package githubapp

import (
	"context"
	"github.com/google/go-github/v69/github"
	"sync"
)

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			CommitChangesFunc: func(ctx context.Context, owner string, repo string, branch string, files map[string][]byte, message string) error {
//				panic("mock out the CommitChanges method")
//			},
//			CreateBranchFunc: func(ctx context.Context, owner string, repo string, baseBranch string, newBranch string) error {
//				panic("mock out the CreateBranch method")
//			},
//			CreatePullRequestFunc: func(ctx context.Context, owner string, repo string, title string, body string, head string, base string) (*github.PullRequest, error) {
//				panic("mock out the CreatePullRequest method")
//			},
//			GetDefaultBranchFunc: func(ctx context.Context, owner string, repo string) (string, error) {
//				panic("mock out the GetDefaultBranch method")
//			},
//			LookupBranchFunc: func(ctx context.Context, owner string, repo string, branch string) (*github.Reference, error) {
//				panic("mock out the LookupBranch method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// CommitChangesFunc mocks the CommitChanges method.
	CommitChangesFunc func(ctx context.Context, owner string, repo string, branch string, files map[string][]byte, message string) error

	// CreateBranchFunc mocks the CreateBranch method.
	CreateBranchFunc func(ctx context.Context, owner string, repo string, baseBranch string, newBranch string) error

	// CreatePullRequestFunc mocks the CreatePullRequest method.
	CreatePullRequestFunc func(ctx context.Context, owner string, repo string, title string, body string, head string, base string) (*github.PullRequest, error)

	// GetDefaultBranchFunc mocks the GetDefaultBranch method.
	GetDefaultBranchFunc func(ctx context.Context, owner string, repo string) (string, error)

	// LookupBranchFunc mocks the LookupBranch method.
	LookupBranchFunc func(ctx context.Context, owner string, repo string, branch string) (*github.Reference, error)

	// calls tracks calls to the methods.
	calls struct {
		// CommitChanges holds details about calls to the CommitChanges method.
		CommitChanges []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Branch is the branch argument value.
			Branch string
			// Files is the files argument value.
			Files map[string][]byte
			// Message is the message argument value.
			Message string
		}
		// CreateBranch holds details about calls to the CreateBranch method.
		CreateBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// BaseBranch is the baseBranch argument value.
			BaseBranch string
			// NewBranch is the newBranch argument value.
			NewBranch string
		}
		// CreatePullRequest holds details about calls to the CreatePullRequest method.
		CreatePullRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Title is the title argument value.
			Title string
			// Body is the body argument value.
			Body string
			// Head is the head argument value.
			Head string
			// Base is the base argument value.
			Base string
		}
		// GetDefaultBranch holds details about calls to the GetDefaultBranch method.
		GetDefaultBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
		}
		// LookupBranch holds details about calls to the LookupBranch method.
		LookupBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Branch is the branch argument value.
			Branch string
		}
	}
	lockCommitChanges     sync.RWMutex
	lockCreateBranch      sync.RWMutex
	lockCreatePullRequest sync.RWMutex
	lockGetDefaultBranch  sync.RWMutex
	lockLookupBranch      sync.RWMutex
}

// CommitChanges calls CommitChangesFunc.
func (mock *ClientMock) CommitChanges(ctx context.Context, owner string, repo string, branch string, files map[string][]byte, message string) error {
	callInfo := struct {
		Ctx     context.Context
		Owner   string
		Repo    string
		Branch  string
		Files   map[string][]byte
		Message string
	}{
		Ctx:     ctx,
		Owner:   owner,
		Repo:    repo,
		Branch:  branch,
		Files:   files,
		Message: message,
	}
	mock.lockCommitChanges.Lock()
	mock.calls.CommitChanges = append(mock.calls.CommitChanges, callInfo)
	mock.lockCommitChanges.Unlock()
	if mock.CommitChangesFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CommitChangesFunc(ctx, owner, repo, branch, files, message)
}

// CommitChangesCalls gets all the calls that were made to CommitChanges.
// Check the length with:
//
//	len(mockedClient.CommitChangesCalls())
func (mock *ClientMock) CommitChangesCalls() []struct {
	Ctx     context.Context
	Owner   string
	Repo    string
	Branch  string
	Files   map[string][]byte
	Message string
} {
	var calls []struct {
		Ctx     context.Context
		Owner   string
		Repo    string
		Branch  string
		Files   map[string][]byte
		Message string
	}
	mock.lockCommitChanges.RLock()
	calls = mock.calls.CommitChanges
	mock.lockCommitChanges.RUnlock()
	return calls
}

// CreateBranch calls CreateBranchFunc.
func (mock *ClientMock) CreateBranch(ctx context.Context, owner string, repo string, baseBranch string, newBranch string) error {
	callInfo := struct {
		Ctx        context.Context
		Owner      string
		Repo       string
		BaseBranch string
		NewBranch  string
	}{
		Ctx:        ctx,
		Owner:      owner,
		Repo:       repo,
		BaseBranch: baseBranch,
		NewBranch:  newBranch,
	}
	mock.lockCreateBranch.Lock()
	mock.calls.CreateBranch = append(mock.calls.CreateBranch, callInfo)
	mock.lockCreateBranch.Unlock()
	if mock.CreateBranchFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateBranchFunc(ctx, owner, repo, baseBranch, newBranch)
}

// CreateBranchCalls gets all the calls that were made to CreateBranch.
// Check the length with:
//
//	len(mockedClient.CreateBranchCalls())
func (mock *ClientMock) CreateBranchCalls() []struct {
	Ctx        context.Context
	Owner      string
	Repo       string
	BaseBranch string
	NewBranch  string
} {
	var calls []struct {
		Ctx        context.Context
		Owner      string
		Repo       string
		BaseBranch string
		NewBranch  string
	}
	mock.lockCreateBranch.RLock()
	calls = mock.calls.CreateBranch
	mock.lockCreateBranch.RUnlock()
	return calls
}

// CreatePullRequest calls CreatePullRequestFunc.
func (mock *ClientMock) CreatePullRequest(ctx context.Context, owner string, repo string, title string, body string, head string, base string) (*github.PullRequest, error) {
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Title string
		Body  string
		Head  string
		Base  string
	}{
		Ctx:   ctx,
		Owner: owner,
		Repo:  repo,
		Title: title,
		Body:  body,
		Head:  head,
		Base:  base,
	}
	mock.lockCreatePullRequest.Lock()
	mock.calls.CreatePullRequest = append(mock.calls.CreatePullRequest, callInfo)
	mock.lockCreatePullRequest.Unlock()
	if mock.CreatePullRequestFunc == nil {
		var (
			pullRequestOut *github.PullRequest
			errOut         error
		)
		return pullRequestOut, errOut
	}
	return mock.CreatePullRequestFunc(ctx, owner, repo, title, body, head, base)
}

// CreatePullRequestCalls gets all the calls that were made to CreatePullRequest.
// Check the length with:
//
//	len(mockedClient.CreatePullRequestCalls())
func (mock *ClientMock) CreatePullRequestCalls() []struct {
	Ctx   context.Context
	Owner string
	Repo  string
	Title string
	Body  string
	Head  string
	Base  string
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Title string
		Body  string
		Head  string
		Base  string
	}
	mock.lockCreatePullRequest.RLock()
	calls = mock.calls.CreatePullRequest
	mock.lockCreatePullRequest.RUnlock()
	return calls
}

// GetDefaultBranch calls GetDefaultBranchFunc.
func (mock *ClientMock) GetDefaultBranch(ctx context.Context, owner string, repo string) (string, error) {
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Repo  string
	}{
		Ctx:   ctx,
		Owner: owner,
		Repo:  repo,
	}
	mock.lockGetDefaultBranch.Lock()
	mock.calls.GetDefaultBranch = append(mock.calls.GetDefaultBranch, callInfo)
	mock.lockGetDefaultBranch.Unlock()
	if mock.GetDefaultBranchFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.GetDefaultBranchFunc(ctx, owner, repo)
}

// GetDefaultBranchCalls gets all the calls that were made to GetDefaultBranch.
// Check the length with:
//
//	len(mockedClient.GetDefaultBranchCalls())
func (mock *ClientMock) GetDefaultBranchCalls() []struct {
	Ctx   context.Context
	Owner string
	Repo  string
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Repo  string
	}
	mock.lockGetDefaultBranch.RLock()
	calls = mock.calls.GetDefaultBranch
	mock.lockGetDefaultBranch.RUnlock()
	return calls
}

// LookupBranch calls LookupBranchFunc.
func (mock *ClientMock) LookupBranch(ctx context.Context, owner string, repo string, branch string) (*github.Reference, error) {
	callInfo := struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Branch string
	}{
		Ctx:    ctx,
		Owner:  owner,
		Repo:   repo,
		Branch: branch,
	}
	mock.lockLookupBranch.Lock()
	mock.calls.LookupBranch = append(mock.calls.LookupBranch, callInfo)
	mock.lockLookupBranch.Unlock()
	if mock.LookupBranchFunc == nil {
		var (
			referenceOut *github.Reference
			errOut       error
		)
		return referenceOut, errOut
	}
	return mock.LookupBranchFunc(ctx, owner, repo, branch)
}

// LookupBranchCalls gets all the calls that were made to LookupBranch.
// Check the length with:
//
//	len(mockedClient.LookupBranchCalls())
func (mock *ClientMock) LookupBranchCalls() []struct {
	Ctx    context.Context
	Owner  string
	Repo   string
	Branch string
} {
	var calls []struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Branch string
	}
	mock.lockLookupBranch.RLock()
	calls = mock.calls.LookupBranch
	mock.lockLookupBranch.RUnlock()
	return calls
}
