// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"cloud.google.com/go/vertexai/genai"
	"context"
	"github.com/m-mizutani/opac"
	"github.com/secmon-lab/warren/pkg/interfaces"
	"github.com/secmon-lab/warren/pkg/model"
	"github.com/secmon-lab/warren/pkg/prompt"
	"github.com/urfave/cli/v3"
	"log/slog"
	"net/http"
	"sync"
	"time"
)

// Ensure, that SlackServiceMock does implement interfaces.SlackService.
// If this is not the case, regenerate this file with moq.
var _ interfaces.SlackService = &SlackServiceMock{}

// SlackServiceMock is a mock implementation of interfaces.SlackService.
//
//	func TestSomethingThatUsesSlackService(t *testing.T) {
//
//		// make and configure a mocked interfaces.SlackService
//		mockedSlackService := &SlackServiceMock{
//			PostAlertFunc: func(ctx context.Context, alert model.Alert) (interfaces.SlackThreadService, error) {
//				panic("mock out the PostAlert method")
//			},
//			VerifyRequestFunc: func(header http.Header, body []byte) error {
//				panic("mock out the VerifyRequest method")
//			},
//		}
//
//		// use mockedSlackService in code that requires interfaces.SlackService
//		// and then make assertions.
//
//	}
type SlackServiceMock struct {
	// PostAlertFunc mocks the PostAlert method.
	PostAlertFunc func(ctx context.Context, alert model.Alert) (interfaces.SlackThreadService, error)

	// VerifyRequestFunc mocks the VerifyRequest method.
	VerifyRequestFunc func(header http.Header, body []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// PostAlert holds details about calls to the PostAlert method.
		PostAlert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Alert is the alert argument value.
			Alert model.Alert
		}
		// VerifyRequest holds details about calls to the VerifyRequest method.
		VerifyRequest []struct {
			// Header is the header argument value.
			Header http.Header
			// Body is the body argument value.
			Body []byte
		}
	}
	lockPostAlert     sync.RWMutex
	lockVerifyRequest sync.RWMutex
}

// PostAlert calls PostAlertFunc.
func (mock *SlackServiceMock) PostAlert(ctx context.Context, alert model.Alert) (interfaces.SlackThreadService, error) {
	if mock.PostAlertFunc == nil {
		panic("SlackServiceMock.PostAlertFunc: method is nil but SlackService.PostAlert was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Alert model.Alert
	}{
		Ctx:   ctx,
		Alert: alert,
	}
	mock.lockPostAlert.Lock()
	mock.calls.PostAlert = append(mock.calls.PostAlert, callInfo)
	mock.lockPostAlert.Unlock()
	return mock.PostAlertFunc(ctx, alert)
}

// PostAlertCalls gets all the calls that were made to PostAlert.
// Check the length with:
//
//	len(mockedSlackService.PostAlertCalls())
func (mock *SlackServiceMock) PostAlertCalls() []struct {
	Ctx   context.Context
	Alert model.Alert
} {
	var calls []struct {
		Ctx   context.Context
		Alert model.Alert
	}
	mock.lockPostAlert.RLock()
	calls = mock.calls.PostAlert
	mock.lockPostAlert.RUnlock()
	return calls
}

// VerifyRequest calls VerifyRequestFunc.
func (mock *SlackServiceMock) VerifyRequest(header http.Header, body []byte) error {
	if mock.VerifyRequestFunc == nil {
		panic("SlackServiceMock.VerifyRequestFunc: method is nil but SlackService.VerifyRequest was just called")
	}
	callInfo := struct {
		Header http.Header
		Body   []byte
	}{
		Header: header,
		Body:   body,
	}
	mock.lockVerifyRequest.Lock()
	mock.calls.VerifyRequest = append(mock.calls.VerifyRequest, callInfo)
	mock.lockVerifyRequest.Unlock()
	return mock.VerifyRequestFunc(header, body)
}

// VerifyRequestCalls gets all the calls that were made to VerifyRequest.
// Check the length with:
//
//	len(mockedSlackService.VerifyRequestCalls())
func (mock *SlackServiceMock) VerifyRequestCalls() []struct {
	Header http.Header
	Body   []byte
} {
	var calls []struct {
		Header http.Header
		Body   []byte
	}
	mock.lockVerifyRequest.RLock()
	calls = mock.calls.VerifyRequest
	mock.lockVerifyRequest.RUnlock()
	return calls
}

// Ensure, that SlackThreadServiceMock does implement interfaces.SlackThreadService.
// If this is not the case, regenerate this file with moq.
var _ interfaces.SlackThreadService = &SlackThreadServiceMock{}

// SlackThreadServiceMock is a mock implementation of interfaces.SlackThreadService.
//
//	func TestSomethingThatUsesSlackThreadService(t *testing.T) {
//
//		// make and configure a mocked interfaces.SlackThreadService
//		mockedSlackThreadService := &SlackThreadServiceMock{
//			AttachFileFunc: func(ctx context.Context, title string, fileName string, data []byte) error {
//				panic("mock out the AttachFile method")
//			},
//			ChannelIDFunc: func() string {
//				panic("mock out the ChannelID method")
//			},
//			PostNextActionFunc: func(ctx context.Context, action prompt.ActionPromptResult) error {
//				panic("mock out the PostNextAction method")
//			},
//			ThreadIDFunc: func() string {
//				panic("mock out the ThreadID method")
//			},
//			UpdateAlertFunc: func(ctx context.Context, alert model.Alert) error {
//				panic("mock out the UpdateAlert method")
//			},
//		}
//
//		// use mockedSlackThreadService in code that requires interfaces.SlackThreadService
//		// and then make assertions.
//
//	}
type SlackThreadServiceMock struct {
	// AttachFileFunc mocks the AttachFile method.
	AttachFileFunc func(ctx context.Context, title string, fileName string, data []byte) error

	// ChannelIDFunc mocks the ChannelID method.
	ChannelIDFunc func() string

	// PostNextActionFunc mocks the PostNextAction method.
	PostNextActionFunc func(ctx context.Context, action prompt.ActionPromptResult) error

	// ThreadIDFunc mocks the ThreadID method.
	ThreadIDFunc func() string

	// UpdateAlertFunc mocks the UpdateAlert method.
	UpdateAlertFunc func(ctx context.Context, alert model.Alert) error

	// calls tracks calls to the methods.
	calls struct {
		// AttachFile holds details about calls to the AttachFile method.
		AttachFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Title is the title argument value.
			Title string
			// FileName is the fileName argument value.
			FileName string
			// Data is the data argument value.
			Data []byte
		}
		// ChannelID holds details about calls to the ChannelID method.
		ChannelID []struct {
		}
		// PostNextAction holds details about calls to the PostNextAction method.
		PostNextAction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Action is the action argument value.
			Action prompt.ActionPromptResult
		}
		// ThreadID holds details about calls to the ThreadID method.
		ThreadID []struct {
		}
		// UpdateAlert holds details about calls to the UpdateAlert method.
		UpdateAlert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Alert is the alert argument value.
			Alert model.Alert
		}
	}
	lockAttachFile     sync.RWMutex
	lockChannelID      sync.RWMutex
	lockPostNextAction sync.RWMutex
	lockThreadID       sync.RWMutex
	lockUpdateAlert    sync.RWMutex
}

// AttachFile calls AttachFileFunc.
func (mock *SlackThreadServiceMock) AttachFile(ctx context.Context, title string, fileName string, data []byte) error {
	if mock.AttachFileFunc == nil {
		panic("SlackThreadServiceMock.AttachFileFunc: method is nil but SlackThreadService.AttachFile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Title    string
		FileName string
		Data     []byte
	}{
		Ctx:      ctx,
		Title:    title,
		FileName: fileName,
		Data:     data,
	}
	mock.lockAttachFile.Lock()
	mock.calls.AttachFile = append(mock.calls.AttachFile, callInfo)
	mock.lockAttachFile.Unlock()
	return mock.AttachFileFunc(ctx, title, fileName, data)
}

// AttachFileCalls gets all the calls that were made to AttachFile.
// Check the length with:
//
//	len(mockedSlackThreadService.AttachFileCalls())
func (mock *SlackThreadServiceMock) AttachFileCalls() []struct {
	Ctx      context.Context
	Title    string
	FileName string
	Data     []byte
} {
	var calls []struct {
		Ctx      context.Context
		Title    string
		FileName string
		Data     []byte
	}
	mock.lockAttachFile.RLock()
	calls = mock.calls.AttachFile
	mock.lockAttachFile.RUnlock()
	return calls
}

// ChannelID calls ChannelIDFunc.
func (mock *SlackThreadServiceMock) ChannelID() string {
	if mock.ChannelIDFunc == nil {
		panic("SlackThreadServiceMock.ChannelIDFunc: method is nil but SlackThreadService.ChannelID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockChannelID.Lock()
	mock.calls.ChannelID = append(mock.calls.ChannelID, callInfo)
	mock.lockChannelID.Unlock()
	return mock.ChannelIDFunc()
}

// ChannelIDCalls gets all the calls that were made to ChannelID.
// Check the length with:
//
//	len(mockedSlackThreadService.ChannelIDCalls())
func (mock *SlackThreadServiceMock) ChannelIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockChannelID.RLock()
	calls = mock.calls.ChannelID
	mock.lockChannelID.RUnlock()
	return calls
}

// PostNextAction calls PostNextActionFunc.
func (mock *SlackThreadServiceMock) PostNextAction(ctx context.Context, action prompt.ActionPromptResult) error {
	if mock.PostNextActionFunc == nil {
		panic("SlackThreadServiceMock.PostNextActionFunc: method is nil but SlackThreadService.PostNextAction was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Action prompt.ActionPromptResult
	}{
		Ctx:    ctx,
		Action: action,
	}
	mock.lockPostNextAction.Lock()
	mock.calls.PostNextAction = append(mock.calls.PostNextAction, callInfo)
	mock.lockPostNextAction.Unlock()
	return mock.PostNextActionFunc(ctx, action)
}

// PostNextActionCalls gets all the calls that were made to PostNextAction.
// Check the length with:
//
//	len(mockedSlackThreadService.PostNextActionCalls())
func (mock *SlackThreadServiceMock) PostNextActionCalls() []struct {
	Ctx    context.Context
	Action prompt.ActionPromptResult
} {
	var calls []struct {
		Ctx    context.Context
		Action prompt.ActionPromptResult
	}
	mock.lockPostNextAction.RLock()
	calls = mock.calls.PostNextAction
	mock.lockPostNextAction.RUnlock()
	return calls
}

// ThreadID calls ThreadIDFunc.
func (mock *SlackThreadServiceMock) ThreadID() string {
	if mock.ThreadIDFunc == nil {
		panic("SlackThreadServiceMock.ThreadIDFunc: method is nil but SlackThreadService.ThreadID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockThreadID.Lock()
	mock.calls.ThreadID = append(mock.calls.ThreadID, callInfo)
	mock.lockThreadID.Unlock()
	return mock.ThreadIDFunc()
}

// ThreadIDCalls gets all the calls that were made to ThreadID.
// Check the length with:
//
//	len(mockedSlackThreadService.ThreadIDCalls())
func (mock *SlackThreadServiceMock) ThreadIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockThreadID.RLock()
	calls = mock.calls.ThreadID
	mock.lockThreadID.RUnlock()
	return calls
}

// UpdateAlert calls UpdateAlertFunc.
func (mock *SlackThreadServiceMock) UpdateAlert(ctx context.Context, alert model.Alert) error {
	if mock.UpdateAlertFunc == nil {
		panic("SlackThreadServiceMock.UpdateAlertFunc: method is nil but SlackThreadService.UpdateAlert was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Alert model.Alert
	}{
		Ctx:   ctx,
		Alert: alert,
	}
	mock.lockUpdateAlert.Lock()
	mock.calls.UpdateAlert = append(mock.calls.UpdateAlert, callInfo)
	mock.lockUpdateAlert.Unlock()
	return mock.UpdateAlertFunc(ctx, alert)
}

// UpdateAlertCalls gets all the calls that were made to UpdateAlert.
// Check the length with:
//
//	len(mockedSlackThreadService.UpdateAlertCalls())
func (mock *SlackThreadServiceMock) UpdateAlertCalls() []struct {
	Ctx   context.Context
	Alert model.Alert
} {
	var calls []struct {
		Ctx   context.Context
		Alert model.Alert
	}
	mock.lockUpdateAlert.RLock()
	calls = mock.calls.UpdateAlert
	mock.lockUpdateAlert.RUnlock()
	return calls
}

// Ensure, that GenAIChatSessionMock does implement interfaces.GenAIChatSession.
// If this is not the case, regenerate this file with moq.
var _ interfaces.GenAIChatSession = &GenAIChatSessionMock{}

// GenAIChatSessionMock is a mock implementation of interfaces.GenAIChatSession.
//
//	func TestSomethingThatUsesGenAIChatSession(t *testing.T) {
//
//		// make and configure a mocked interfaces.GenAIChatSession
//		mockedGenAIChatSession := &GenAIChatSessionMock{
//			SendMessageFunc: func(ctx context.Context, msg ...genai.Part) (*genai.GenerateContentResponse, error) {
//				panic("mock out the SendMessage method")
//			},
//		}
//
//		// use mockedGenAIChatSession in code that requires interfaces.GenAIChatSession
//		// and then make assertions.
//
//	}
type GenAIChatSessionMock struct {
	// SendMessageFunc mocks the SendMessage method.
	SendMessageFunc func(ctx context.Context, msg ...genai.Part) (*genai.GenerateContentResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// SendMessage holds details about calls to the SendMessage method.
		SendMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg []genai.Part
		}
	}
	lockSendMessage sync.RWMutex
}

// SendMessage calls SendMessageFunc.
func (mock *GenAIChatSessionMock) SendMessage(ctx context.Context, msg ...genai.Part) (*genai.GenerateContentResponse, error) {
	if mock.SendMessageFunc == nil {
		panic("GenAIChatSessionMock.SendMessageFunc: method is nil but GenAIChatSession.SendMessage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg []genai.Part
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockSendMessage.Lock()
	mock.calls.SendMessage = append(mock.calls.SendMessage, callInfo)
	mock.lockSendMessage.Unlock()
	return mock.SendMessageFunc(ctx, msg...)
}

// SendMessageCalls gets all the calls that were made to SendMessage.
// Check the length with:
//
//	len(mockedGenAIChatSession.SendMessageCalls())
func (mock *GenAIChatSessionMock) SendMessageCalls() []struct {
	Ctx context.Context
	Msg []genai.Part
} {
	var calls []struct {
		Ctx context.Context
		Msg []genai.Part
	}
	mock.lockSendMessage.RLock()
	calls = mock.calls.SendMessage
	mock.lockSendMessage.RUnlock()
	return calls
}

// Ensure, that PolicyClientMock does implement interfaces.PolicyClient.
// If this is not the case, regenerate this file with moq.
var _ interfaces.PolicyClient = &PolicyClientMock{}

// PolicyClientMock is a mock implementation of interfaces.PolicyClient.
//
//	func TestSomethingThatUsesPolicyClient(t *testing.T) {
//
//		// make and configure a mocked interfaces.PolicyClient
//		mockedPolicyClient := &PolicyClientMock{
//			QueryFunc: func(contextMoqParam context.Context, s string, v1 any, v2 any, queryOptions ...opac.QueryOption) error {
//				panic("mock out the Query method")
//			},
//		}
//
//		// use mockedPolicyClient in code that requires interfaces.PolicyClient
//		// and then make assertions.
//
//	}
type PolicyClientMock struct {
	// QueryFunc mocks the Query method.
	QueryFunc func(contextMoqParam context.Context, s string, v1 any, v2 any, queryOptions ...opac.QueryOption) error

	// calls tracks calls to the methods.
	calls struct {
		// Query holds details about calls to the Query method.
		Query []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// V1 is the v1 argument value.
			V1 any
			// V2 is the v2 argument value.
			V2 any
			// QueryOptions is the queryOptions argument value.
			QueryOptions []opac.QueryOption
		}
	}
	lockQuery sync.RWMutex
}

// Query calls QueryFunc.
func (mock *PolicyClientMock) Query(contextMoqParam context.Context, s string, v1 any, v2 any, queryOptions ...opac.QueryOption) error {
	if mock.QueryFunc == nil {
		panic("PolicyClientMock.QueryFunc: method is nil but PolicyClient.Query was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
		V1              any
		V2              any
		QueryOptions    []opac.QueryOption
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
		V1:              v1,
		V2:              v2,
		QueryOptions:    queryOptions,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(contextMoqParam, s, v1, v2, queryOptions...)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedPolicyClient.QueryCalls())
func (mock *PolicyClientMock) QueryCalls() []struct {
	ContextMoqParam context.Context
	S               string
	V1              any
	V2              any
	QueryOptions    []opac.QueryOption
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
		V1              any
		V2              any
		QueryOptions    []opac.QueryOption
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// Ensure, that RepositoryMock does implement interfaces.Repository.
// If this is not the case, regenerate this file with moq.
var _ interfaces.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of interfaces.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked interfaces.Repository
//		mockedRepository := &RepositoryMock{
//			FetchLatestAlertsFunc: func(ctx context.Context, oldest time.Time, limit int) ([]model.Alert, error) {
//				panic("mock out the FetchLatestAlerts method")
//			},
//			GetAlertFunc: func(ctx context.Context, alertID model.AlertID) (*model.Alert, error) {
//				panic("mock out the GetAlert method")
//			},
//			PutAlertFunc: func(ctx context.Context, alert model.Alert) error {
//				panic("mock out the PutAlert method")
//			},
//		}
//
//		// use mockedRepository in code that requires interfaces.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// FetchLatestAlertsFunc mocks the FetchLatestAlerts method.
	FetchLatestAlertsFunc func(ctx context.Context, oldest time.Time, limit int) ([]model.Alert, error)

	// GetAlertFunc mocks the GetAlert method.
	GetAlertFunc func(ctx context.Context, alertID model.AlertID) (*model.Alert, error)

	// PutAlertFunc mocks the PutAlert method.
	PutAlertFunc func(ctx context.Context, alert model.Alert) error

	// calls tracks calls to the methods.
	calls struct {
		// FetchLatestAlerts holds details about calls to the FetchLatestAlerts method.
		FetchLatestAlerts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Oldest is the oldest argument value.
			Oldest time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetAlert holds details about calls to the GetAlert method.
		GetAlert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertID is the alertID argument value.
			AlertID model.AlertID
		}
		// PutAlert holds details about calls to the PutAlert method.
		PutAlert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Alert is the alert argument value.
			Alert model.Alert
		}
	}
	lockFetchLatestAlerts sync.RWMutex
	lockGetAlert          sync.RWMutex
	lockPutAlert          sync.RWMutex
}

// FetchLatestAlerts calls FetchLatestAlertsFunc.
func (mock *RepositoryMock) FetchLatestAlerts(ctx context.Context, oldest time.Time, limit int) ([]model.Alert, error) {
	if mock.FetchLatestAlertsFunc == nil {
		panic("RepositoryMock.FetchLatestAlertsFunc: method is nil but Repository.FetchLatestAlerts was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Oldest time.Time
		Limit  int
	}{
		Ctx:    ctx,
		Oldest: oldest,
		Limit:  limit,
	}
	mock.lockFetchLatestAlerts.Lock()
	mock.calls.FetchLatestAlerts = append(mock.calls.FetchLatestAlerts, callInfo)
	mock.lockFetchLatestAlerts.Unlock()
	return mock.FetchLatestAlertsFunc(ctx, oldest, limit)
}

// FetchLatestAlertsCalls gets all the calls that were made to FetchLatestAlerts.
// Check the length with:
//
//	len(mockedRepository.FetchLatestAlertsCalls())
func (mock *RepositoryMock) FetchLatestAlertsCalls() []struct {
	Ctx    context.Context
	Oldest time.Time
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Oldest time.Time
		Limit  int
	}
	mock.lockFetchLatestAlerts.RLock()
	calls = mock.calls.FetchLatestAlerts
	mock.lockFetchLatestAlerts.RUnlock()
	return calls
}

// GetAlert calls GetAlertFunc.
func (mock *RepositoryMock) GetAlert(ctx context.Context, alertID model.AlertID) (*model.Alert, error) {
	if mock.GetAlertFunc == nil {
		panic("RepositoryMock.GetAlertFunc: method is nil but Repository.GetAlert was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		AlertID model.AlertID
	}{
		Ctx:     ctx,
		AlertID: alertID,
	}
	mock.lockGetAlert.Lock()
	mock.calls.GetAlert = append(mock.calls.GetAlert, callInfo)
	mock.lockGetAlert.Unlock()
	return mock.GetAlertFunc(ctx, alertID)
}

// GetAlertCalls gets all the calls that were made to GetAlert.
// Check the length with:
//
//	len(mockedRepository.GetAlertCalls())
func (mock *RepositoryMock) GetAlertCalls() []struct {
	Ctx     context.Context
	AlertID model.AlertID
} {
	var calls []struct {
		Ctx     context.Context
		AlertID model.AlertID
	}
	mock.lockGetAlert.RLock()
	calls = mock.calls.GetAlert
	mock.lockGetAlert.RUnlock()
	return calls
}

// PutAlert calls PutAlertFunc.
func (mock *RepositoryMock) PutAlert(ctx context.Context, alert model.Alert) error {
	if mock.PutAlertFunc == nil {
		panic("RepositoryMock.PutAlertFunc: method is nil but Repository.PutAlert was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Alert model.Alert
	}{
		Ctx:   ctx,
		Alert: alert,
	}
	mock.lockPutAlert.Lock()
	mock.calls.PutAlert = append(mock.calls.PutAlert, callInfo)
	mock.lockPutAlert.Unlock()
	return mock.PutAlertFunc(ctx, alert)
}

// PutAlertCalls gets all the calls that were made to PutAlert.
// Check the length with:
//
//	len(mockedRepository.PutAlertCalls())
func (mock *RepositoryMock) PutAlertCalls() []struct {
	Ctx   context.Context
	Alert model.Alert
} {
	var calls []struct {
		Ctx   context.Context
		Alert model.Alert
	}
	mock.lockPutAlert.RLock()
	calls = mock.calls.PutAlert
	mock.lockPutAlert.RUnlock()
	return calls
}

// Ensure, that ActionMock does implement interfaces.Action.
// If this is not the case, regenerate this file with moq.
var _ interfaces.Action = &ActionMock{}

// ActionMock is a mock implementation of interfaces.Action.
//
//	func TestSomethingThatUsesAction(t *testing.T) {
//
//		// make and configure a mocked interfaces.Action
//		mockedAction := &ActionMock{
//			ConfigureFunc: func(ctx context.Context) error {
//				panic("mock out the Configure method")
//			},
//			ExecuteFunc: func(ctx context.Context, slack interfaces.SlackService, ssn interfaces.GenAIChatSession, args model.Arguments) (*model.ActionResult, error) {
//				panic("mock out the Execute method")
//			},
//			FlagsFunc: func() []cli.Flag {
//				panic("mock out the Flags method")
//			},
//			LogValueFunc: func() slog.Value {
//				panic("mock out the LogValue method")
//			},
//			SpecFunc: func() model.ActionSpec {
//				panic("mock out the Spec method")
//			},
//		}
//
//		// use mockedAction in code that requires interfaces.Action
//		// and then make assertions.
//
//	}
type ActionMock struct {
	// ConfigureFunc mocks the Configure method.
	ConfigureFunc func(ctx context.Context) error

	// ExecuteFunc mocks the Execute method.
	ExecuteFunc func(ctx context.Context, slack interfaces.SlackService, ssn interfaces.GenAIChatSession, args model.Arguments) (*model.ActionResult, error)

	// FlagsFunc mocks the Flags method.
	FlagsFunc func() []cli.Flag

	// LogValueFunc mocks the LogValue method.
	LogValueFunc func() slog.Value

	// SpecFunc mocks the Spec method.
	SpecFunc func() model.ActionSpec

	// calls tracks calls to the methods.
	calls struct {
		// Configure holds details about calls to the Configure method.
		Configure []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Execute holds details about calls to the Execute method.
		Execute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Slack is the slack argument value.
			Slack interfaces.SlackService
			// Ssn is the ssn argument value.
			Ssn interfaces.GenAIChatSession
			// Args is the args argument value.
			Args model.Arguments
		}
		// Flags holds details about calls to the Flags method.
		Flags []struct {
		}
		// LogValue holds details about calls to the LogValue method.
		LogValue []struct {
		}
		// Spec holds details about calls to the Spec method.
		Spec []struct {
		}
	}
	lockConfigure sync.RWMutex
	lockExecute   sync.RWMutex
	lockFlags     sync.RWMutex
	lockLogValue  sync.RWMutex
	lockSpec      sync.RWMutex
}

// Configure calls ConfigureFunc.
func (mock *ActionMock) Configure(ctx context.Context) error {
	if mock.ConfigureFunc == nil {
		panic("ActionMock.ConfigureFunc: method is nil but Action.Configure was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockConfigure.Lock()
	mock.calls.Configure = append(mock.calls.Configure, callInfo)
	mock.lockConfigure.Unlock()
	return mock.ConfigureFunc(ctx)
}

// ConfigureCalls gets all the calls that were made to Configure.
// Check the length with:
//
//	len(mockedAction.ConfigureCalls())
func (mock *ActionMock) ConfigureCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockConfigure.RLock()
	calls = mock.calls.Configure
	mock.lockConfigure.RUnlock()
	return calls
}

// Execute calls ExecuteFunc.
func (mock *ActionMock) Execute(ctx context.Context, slack interfaces.SlackService, ssn interfaces.GenAIChatSession, args model.Arguments) (*model.ActionResult, error) {
	if mock.ExecuteFunc == nil {
		panic("ActionMock.ExecuteFunc: method is nil but Action.Execute was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Slack interfaces.SlackService
		Ssn   interfaces.GenAIChatSession
		Args  model.Arguments
	}{
		Ctx:   ctx,
		Slack: slack,
		Ssn:   ssn,
		Args:  args,
	}
	mock.lockExecute.Lock()
	mock.calls.Execute = append(mock.calls.Execute, callInfo)
	mock.lockExecute.Unlock()
	return mock.ExecuteFunc(ctx, slack, ssn, args)
}

// ExecuteCalls gets all the calls that were made to Execute.
// Check the length with:
//
//	len(mockedAction.ExecuteCalls())
func (mock *ActionMock) ExecuteCalls() []struct {
	Ctx   context.Context
	Slack interfaces.SlackService
	Ssn   interfaces.GenAIChatSession
	Args  model.Arguments
} {
	var calls []struct {
		Ctx   context.Context
		Slack interfaces.SlackService
		Ssn   interfaces.GenAIChatSession
		Args  model.Arguments
	}
	mock.lockExecute.RLock()
	calls = mock.calls.Execute
	mock.lockExecute.RUnlock()
	return calls
}

// Flags calls FlagsFunc.
func (mock *ActionMock) Flags() []cli.Flag {
	if mock.FlagsFunc == nil {
		panic("ActionMock.FlagsFunc: method is nil but Action.Flags was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFlags.Lock()
	mock.calls.Flags = append(mock.calls.Flags, callInfo)
	mock.lockFlags.Unlock()
	return mock.FlagsFunc()
}

// FlagsCalls gets all the calls that were made to Flags.
// Check the length with:
//
//	len(mockedAction.FlagsCalls())
func (mock *ActionMock) FlagsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFlags.RLock()
	calls = mock.calls.Flags
	mock.lockFlags.RUnlock()
	return calls
}

// LogValue calls LogValueFunc.
func (mock *ActionMock) LogValue() slog.Value {
	if mock.LogValueFunc == nil {
		panic("ActionMock.LogValueFunc: method is nil but Action.LogValue was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLogValue.Lock()
	mock.calls.LogValue = append(mock.calls.LogValue, callInfo)
	mock.lockLogValue.Unlock()
	return mock.LogValueFunc()
}

// LogValueCalls gets all the calls that were made to LogValue.
// Check the length with:
//
//	len(mockedAction.LogValueCalls())
func (mock *ActionMock) LogValueCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogValue.RLock()
	calls = mock.calls.LogValue
	mock.lockLogValue.RUnlock()
	return calls
}

// Spec calls SpecFunc.
func (mock *ActionMock) Spec() model.ActionSpec {
	if mock.SpecFunc == nil {
		panic("ActionMock.SpecFunc: method is nil but Action.Spec was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSpec.Lock()
	mock.calls.Spec = append(mock.calls.Spec, callInfo)
	mock.lockSpec.Unlock()
	return mock.SpecFunc()
}

// SpecCalls gets all the calls that were made to Spec.
// Check the length with:
//
//	len(mockedAction.SpecCalls())
func (mock *ActionMock) SpecCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSpec.RLock()
	calls = mock.calls.Spec
	mock.lockSpec.RUnlock()
	return calls
}
