// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package http_test

import (
	"context"
	"github.com/secmon-lab/warren/pkg/domain/model/alert"
	slack_model "github.com/secmon-lab/warren/pkg/domain/model/slack"
	"github.com/secmon-lab/warren/pkg/domain/types"
	"sync"
)

// UseCaseMock is a mock implementation of http.UseCase.
//
//	func TestSomethingThatUsesUseCase(t *testing.T) {
//
//		// make and configure a mocked http.UseCase
//		mockedUseCase := &UseCaseMock{
//			HandleAlertWithAuthFunc: func(ctx context.Context, schema types.AlertSchema, alertData any) ([]*alert.Alert, error) {
//				panic("mock out the HandleAlertWithAuth method")
//			},
//			HandleSlackAppMentionFunc: func(ctx context.Context, user slack_model.User, mention slack_model.Mention, slackMsg *slack_model.Message) error {
//				panic("mock out the HandleSlackAppMention method")
//			},
//			HandleSlackInteractionBlockActionsFunc: func(ctx context.Context, user slack_model.User, slackThread slack_model.Thread, actionID slack_model.ActionID, value string, triggerID string) error {
//				panic("mock out the HandleSlackInteractionBlockActions method")
//			},
//			HandleSlackInteractionViewSubmissionIgnoreListFunc: func(ctx context.Context, metadata string, values slack_model.StateValue) error {
//				panic("mock out the HandleSlackInteractionViewSubmissionIgnoreList method")
//			},
//			HandleSlackInteractionViewSubmissionResolveAlertFunc: func(ctx context.Context, user slack_model.User, metadata string, values slack_model.StateValue) error {
//				panic("mock out the HandleSlackInteractionViewSubmissionResolveAlert method")
//			},
//			HandleSlackInteractionViewSubmissionResolveListFunc: func(ctx context.Context, user slack_model.User, metadata string, values slack_model.StateValue) error {
//				panic("mock out the HandleSlackInteractionViewSubmissionResolveList method")
//			},
//			HandleSlackMessageFunc: func(ctx context.Context, slackMsg *slack_model.Message, text string, user slack_model.User, ts string) error {
//				panic("mock out the HandleSlackMessage method")
//			},
//		}
//
//		// use mockedUseCase in code that requires http.UseCase
//		// and then make assertions.
//
//	}
type UseCaseMock struct {
	// HandleAlertWithAuthFunc mocks the HandleAlertWithAuth method.
	HandleAlertWithAuthFunc func(ctx context.Context, schema types.AlertSchema, alertData any) ([]*alert.Alert, error)

	// HandleSlackAppMentionFunc mocks the HandleSlackAppMention method.
	HandleSlackAppMentionFunc func(ctx context.Context, user slack_model.User, mention slack_model.Mention, slackMsg *slack_model.Message) error

	// HandleSlackInteractionBlockActionsFunc mocks the HandleSlackInteractionBlockActions method.
	HandleSlackInteractionBlockActionsFunc func(ctx context.Context, user slack_model.User, slackThread slack_model.Thread, actionID slack_model.ActionID, value string, triggerID string) error

	// HandleSlackInteractionViewSubmissionIgnoreListFunc mocks the HandleSlackInteractionViewSubmissionIgnoreList method.
	HandleSlackInteractionViewSubmissionIgnoreListFunc func(ctx context.Context, metadata string, values slack_model.StateValue) error

	// HandleSlackInteractionViewSubmissionResolveAlertFunc mocks the HandleSlackInteractionViewSubmissionResolveAlert method.
	HandleSlackInteractionViewSubmissionResolveAlertFunc func(ctx context.Context, user slack_model.User, metadata string, values slack_model.StateValue) error

	// HandleSlackInteractionViewSubmissionResolveListFunc mocks the HandleSlackInteractionViewSubmissionResolveList method.
	HandleSlackInteractionViewSubmissionResolveListFunc func(ctx context.Context, user slack_model.User, metadata string, values slack_model.StateValue) error

	// HandleSlackMessageFunc mocks the HandleSlackMessage method.
	HandleSlackMessageFunc func(ctx context.Context, slackMsg *slack_model.Message, text string, user slack_model.User, ts string) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleAlertWithAuth holds details about calls to the HandleAlertWithAuth method.
		HandleAlertWithAuth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Schema is the schema argument value.
			Schema types.AlertSchema
			// AlertData is the alertData argument value.
			AlertData any
		}
		// HandleSlackAppMention holds details about calls to the HandleSlackAppMention method.
		HandleSlackAppMention []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User slack_model.User
			// Mention is the mention argument value.
			Mention slack_model.Mention
			// SlackMsg is the slackMsg argument value.
			SlackMsg *slack_model.Message
		}
		// HandleSlackInteractionBlockActions holds details about calls to the HandleSlackInteractionBlockActions method.
		HandleSlackInteractionBlockActions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User slack_model.User
			// SlackThread is the slackThread argument value.
			SlackThread slack_model.Thread
			// ActionID is the actionID argument value.
			ActionID slack_model.ActionID
			// Value is the value argument value.
			Value string
			// TriggerID is the triggerID argument value.
			TriggerID string
		}
		// HandleSlackInteractionViewSubmissionIgnoreList holds details about calls to the HandleSlackInteractionViewSubmissionIgnoreList method.
		HandleSlackInteractionViewSubmissionIgnoreList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Metadata is the metadata argument value.
			Metadata string
			// Values is the values argument value.
			Values slack_model.StateValue
		}
		// HandleSlackInteractionViewSubmissionResolveAlert holds details about calls to the HandleSlackInteractionViewSubmissionResolveAlert method.
		HandleSlackInteractionViewSubmissionResolveAlert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User slack_model.User
			// Metadata is the metadata argument value.
			Metadata string
			// Values is the values argument value.
			Values slack_model.StateValue
		}
		// HandleSlackInteractionViewSubmissionResolveList holds details about calls to the HandleSlackInteractionViewSubmissionResolveList method.
		HandleSlackInteractionViewSubmissionResolveList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User slack_model.User
			// Metadata is the metadata argument value.
			Metadata string
			// Values is the values argument value.
			Values slack_model.StateValue
		}
		// HandleSlackMessage holds details about calls to the HandleSlackMessage method.
		HandleSlackMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SlackMsg is the slackMsg argument value.
			SlackMsg *slack_model.Message
			// Text is the text argument value.
			Text string
			// User is the user argument value.
			User slack_model.User
			// Ts is the ts argument value.
			Ts string
		}
	}
	lockHandleAlertWithAuth                              sync.RWMutex
	lockHandleSlackAppMention                            sync.RWMutex
	lockHandleSlackInteractionBlockActions               sync.RWMutex
	lockHandleSlackInteractionViewSubmissionIgnoreList   sync.RWMutex
	lockHandleSlackInteractionViewSubmissionResolveAlert sync.RWMutex
	lockHandleSlackInteractionViewSubmissionResolveList  sync.RWMutex
	lockHandleSlackMessage                               sync.RWMutex
}

// HandleAlertWithAuth calls HandleAlertWithAuthFunc.
func (mock *UseCaseMock) HandleAlertWithAuth(ctx context.Context, schema types.AlertSchema, alertData any) ([]*alert.Alert, error) {
	callInfo := struct {
		Ctx       context.Context
		Schema    types.AlertSchema
		AlertData any
	}{
		Ctx:       ctx,
		Schema:    schema,
		AlertData: alertData,
	}
	mock.lockHandleAlertWithAuth.Lock()
	mock.calls.HandleAlertWithAuth = append(mock.calls.HandleAlertWithAuth, callInfo)
	mock.lockHandleAlertWithAuth.Unlock()
	if mock.HandleAlertWithAuthFunc == nil {
		var (
			alertsOut []*alert.Alert
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.HandleAlertWithAuthFunc(ctx, schema, alertData)
}

// HandleAlertWithAuthCalls gets all the calls that were made to HandleAlertWithAuth.
// Check the length with:
//
//	len(mockedUseCase.HandleAlertWithAuthCalls())
func (mock *UseCaseMock) HandleAlertWithAuthCalls() []struct {
	Ctx       context.Context
	Schema    types.AlertSchema
	AlertData any
} {
	var calls []struct {
		Ctx       context.Context
		Schema    types.AlertSchema
		AlertData any
	}
	mock.lockHandleAlertWithAuth.RLock()
	calls = mock.calls.HandleAlertWithAuth
	mock.lockHandleAlertWithAuth.RUnlock()
	return calls
}

// HandleSlackAppMention calls HandleSlackAppMentionFunc.
func (mock *UseCaseMock) HandleSlackAppMention(ctx context.Context, user slack_model.User, mention slack_model.Mention, slackMsg *slack_model.Message) error {
	callInfo := struct {
		Ctx      context.Context
		User     slack_model.User
		Mention  slack_model.Mention
		SlackMsg *slack_model.Message
	}{
		Ctx:      ctx,
		User:     user,
		Mention:  mention,
		SlackMsg: slackMsg,
	}
	mock.lockHandleSlackAppMention.Lock()
	mock.calls.HandleSlackAppMention = append(mock.calls.HandleSlackAppMention, callInfo)
	mock.lockHandleSlackAppMention.Unlock()
	if mock.HandleSlackAppMentionFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.HandleSlackAppMentionFunc(ctx, user, mention, slackMsg)
}

// HandleSlackAppMentionCalls gets all the calls that were made to HandleSlackAppMention.
// Check the length with:
//
//	len(mockedUseCase.HandleSlackAppMentionCalls())
func (mock *UseCaseMock) HandleSlackAppMentionCalls() []struct {
	Ctx      context.Context
	User     slack_model.User
	Mention  slack_model.Mention
	SlackMsg *slack_model.Message
} {
	var calls []struct {
		Ctx      context.Context
		User     slack_model.User
		Mention  slack_model.Mention
		SlackMsg *slack_model.Message
	}
	mock.lockHandleSlackAppMention.RLock()
	calls = mock.calls.HandleSlackAppMention
	mock.lockHandleSlackAppMention.RUnlock()
	return calls
}

// HandleSlackInteractionBlockActions calls HandleSlackInteractionBlockActionsFunc.
func (mock *UseCaseMock) HandleSlackInteractionBlockActions(ctx context.Context, user slack_model.User, slackThread slack_model.Thread, actionID slack_model.ActionID, value string, triggerID string) error {
	callInfo := struct {
		Ctx         context.Context
		User        slack_model.User
		SlackThread slack_model.Thread
		ActionID    slack_model.ActionID
		Value       string
		TriggerID   string
	}{
		Ctx:         ctx,
		User:        user,
		SlackThread: slackThread,
		ActionID:    actionID,
		Value:       value,
		TriggerID:   triggerID,
	}
	mock.lockHandleSlackInteractionBlockActions.Lock()
	mock.calls.HandleSlackInteractionBlockActions = append(mock.calls.HandleSlackInteractionBlockActions, callInfo)
	mock.lockHandleSlackInteractionBlockActions.Unlock()
	if mock.HandleSlackInteractionBlockActionsFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.HandleSlackInteractionBlockActionsFunc(ctx, user, slackThread, actionID, value, triggerID)
}

// HandleSlackInteractionBlockActionsCalls gets all the calls that were made to HandleSlackInteractionBlockActions.
// Check the length with:
//
//	len(mockedUseCase.HandleSlackInteractionBlockActionsCalls())
func (mock *UseCaseMock) HandleSlackInteractionBlockActionsCalls() []struct {
	Ctx         context.Context
	User        slack_model.User
	SlackThread slack_model.Thread
	ActionID    slack_model.ActionID
	Value       string
	TriggerID   string
} {
	var calls []struct {
		Ctx         context.Context
		User        slack_model.User
		SlackThread slack_model.Thread
		ActionID    slack_model.ActionID
		Value       string
		TriggerID   string
	}
	mock.lockHandleSlackInteractionBlockActions.RLock()
	calls = mock.calls.HandleSlackInteractionBlockActions
	mock.lockHandleSlackInteractionBlockActions.RUnlock()
	return calls
}

// HandleSlackInteractionViewSubmissionIgnoreList calls HandleSlackInteractionViewSubmissionIgnoreListFunc.
func (mock *UseCaseMock) HandleSlackInteractionViewSubmissionIgnoreList(ctx context.Context, metadata string, values slack_model.StateValue) error {
	callInfo := struct {
		Ctx      context.Context
		Metadata string
		Values   slack_model.StateValue
	}{
		Ctx:      ctx,
		Metadata: metadata,
		Values:   values,
	}
	mock.lockHandleSlackInteractionViewSubmissionIgnoreList.Lock()
	mock.calls.HandleSlackInteractionViewSubmissionIgnoreList = append(mock.calls.HandleSlackInteractionViewSubmissionIgnoreList, callInfo)
	mock.lockHandleSlackInteractionViewSubmissionIgnoreList.Unlock()
	if mock.HandleSlackInteractionViewSubmissionIgnoreListFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.HandleSlackInteractionViewSubmissionIgnoreListFunc(ctx, metadata, values)
}

// HandleSlackInteractionViewSubmissionIgnoreListCalls gets all the calls that were made to HandleSlackInteractionViewSubmissionIgnoreList.
// Check the length with:
//
//	len(mockedUseCase.HandleSlackInteractionViewSubmissionIgnoreListCalls())
func (mock *UseCaseMock) HandleSlackInteractionViewSubmissionIgnoreListCalls() []struct {
	Ctx      context.Context
	Metadata string
	Values   slack_model.StateValue
} {
	var calls []struct {
		Ctx      context.Context
		Metadata string
		Values   slack_model.StateValue
	}
	mock.lockHandleSlackInteractionViewSubmissionIgnoreList.RLock()
	calls = mock.calls.HandleSlackInteractionViewSubmissionIgnoreList
	mock.lockHandleSlackInteractionViewSubmissionIgnoreList.RUnlock()
	return calls
}

// HandleSlackInteractionViewSubmissionResolveAlert calls HandleSlackInteractionViewSubmissionResolveAlertFunc.
func (mock *UseCaseMock) HandleSlackInteractionViewSubmissionResolveAlert(ctx context.Context, user slack_model.User, metadata string, values slack_model.StateValue) error {
	callInfo := struct {
		Ctx      context.Context
		User     slack_model.User
		Metadata string
		Values   slack_model.StateValue
	}{
		Ctx:      ctx,
		User:     user,
		Metadata: metadata,
		Values:   values,
	}
	mock.lockHandleSlackInteractionViewSubmissionResolveAlert.Lock()
	mock.calls.HandleSlackInteractionViewSubmissionResolveAlert = append(mock.calls.HandleSlackInteractionViewSubmissionResolveAlert, callInfo)
	mock.lockHandleSlackInteractionViewSubmissionResolveAlert.Unlock()
	if mock.HandleSlackInteractionViewSubmissionResolveAlertFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.HandleSlackInteractionViewSubmissionResolveAlertFunc(ctx, user, metadata, values)
}

// HandleSlackInteractionViewSubmissionResolveAlertCalls gets all the calls that were made to HandleSlackInteractionViewSubmissionResolveAlert.
// Check the length with:
//
//	len(mockedUseCase.HandleSlackInteractionViewSubmissionResolveAlertCalls())
func (mock *UseCaseMock) HandleSlackInteractionViewSubmissionResolveAlertCalls() []struct {
	Ctx      context.Context
	User     slack_model.User
	Metadata string
	Values   slack_model.StateValue
} {
	var calls []struct {
		Ctx      context.Context
		User     slack_model.User
		Metadata string
		Values   slack_model.StateValue
	}
	mock.lockHandleSlackInteractionViewSubmissionResolveAlert.RLock()
	calls = mock.calls.HandleSlackInteractionViewSubmissionResolveAlert
	mock.lockHandleSlackInteractionViewSubmissionResolveAlert.RUnlock()
	return calls
}

// HandleSlackInteractionViewSubmissionResolveList calls HandleSlackInteractionViewSubmissionResolveListFunc.
func (mock *UseCaseMock) HandleSlackInteractionViewSubmissionResolveList(ctx context.Context, user slack_model.User, metadata string, values slack_model.StateValue) error {
	callInfo := struct {
		Ctx      context.Context
		User     slack_model.User
		Metadata string
		Values   slack_model.StateValue
	}{
		Ctx:      ctx,
		User:     user,
		Metadata: metadata,
		Values:   values,
	}
	mock.lockHandleSlackInteractionViewSubmissionResolveList.Lock()
	mock.calls.HandleSlackInteractionViewSubmissionResolveList = append(mock.calls.HandleSlackInteractionViewSubmissionResolveList, callInfo)
	mock.lockHandleSlackInteractionViewSubmissionResolveList.Unlock()
	if mock.HandleSlackInteractionViewSubmissionResolveListFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.HandleSlackInteractionViewSubmissionResolveListFunc(ctx, user, metadata, values)
}

// HandleSlackInteractionViewSubmissionResolveListCalls gets all the calls that were made to HandleSlackInteractionViewSubmissionResolveList.
// Check the length with:
//
//	len(mockedUseCase.HandleSlackInteractionViewSubmissionResolveListCalls())
func (mock *UseCaseMock) HandleSlackInteractionViewSubmissionResolveListCalls() []struct {
	Ctx      context.Context
	User     slack_model.User
	Metadata string
	Values   slack_model.StateValue
} {
	var calls []struct {
		Ctx      context.Context
		User     slack_model.User
		Metadata string
		Values   slack_model.StateValue
	}
	mock.lockHandleSlackInteractionViewSubmissionResolveList.RLock()
	calls = mock.calls.HandleSlackInteractionViewSubmissionResolveList
	mock.lockHandleSlackInteractionViewSubmissionResolveList.RUnlock()
	return calls
}

// HandleSlackMessage calls HandleSlackMessageFunc.
func (mock *UseCaseMock) HandleSlackMessage(ctx context.Context, slackMsg *slack_model.Message, text string, user slack_model.User, ts string) error {
	callInfo := struct {
		Ctx      context.Context
		SlackMsg *slack_model.Message
		Text     string
		User     slack_model.User
		Ts       string
	}{
		Ctx:      ctx,
		SlackMsg: slackMsg,
		Text:     text,
		User:     user,
		Ts:       ts,
	}
	mock.lockHandleSlackMessage.Lock()
	mock.calls.HandleSlackMessage = append(mock.calls.HandleSlackMessage, callInfo)
	mock.lockHandleSlackMessage.Unlock()
	if mock.HandleSlackMessageFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.HandleSlackMessageFunc(ctx, slackMsg, text, user, ts)
}

// HandleSlackMessageCalls gets all the calls that were made to HandleSlackMessage.
// Check the length with:
//
//	len(mockedUseCase.HandleSlackMessageCalls())
func (mock *UseCaseMock) HandleSlackMessageCalls() []struct {
	Ctx      context.Context
	SlackMsg *slack_model.Message
	Text     string
	User     slack_model.User
	Ts       string
} {
	var calls []struct {
		Ctx      context.Context
		SlackMsg *slack_model.Message
		Text     string
		User     slack_model.User
		Ts       string
	}
	mock.lockHandleSlackMessage.RLock()
	calls = mock.calls.HandleSlackMessage
	mock.lockHandleSlackMessage.RUnlock()
	return calls
}
