// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/m-mizutani/gollem"
	"github.com/m-mizutani/opaq"
	"github.com/secmon-lab/warren/pkg/domain/model/alert"
	"github.com/secmon-lab/warren/pkg/domain/model/session"
	modelslack "github.com/secmon-lab/warren/pkg/domain/model/slack"
	"github.com/secmon-lab/warren/pkg/domain/model/ticket"
	"github.com/secmon-lab/warren/pkg/domain/types"
	slackslack "github.com/slack-go/slack"
	"io"
	"sync"
	"time"
)

// SlackClientMock is a mock implementation of interfaces.SlackClient.
//
//	func TestSomethingThatUsesSlackClient(t *testing.T) {
//
//		// make and configure a mocked interfaces.SlackClient
//		mockedSlackClient := &SlackClientMock{
//			AuthTestFunc: func() (*slackslack.AuthTestResponse, error) {
//				panic("mock out the AuthTest method")
//			},
//			OpenViewFunc: func(triggerID string, view slackslack.ModalViewRequest) (*slackslack.ViewResponse, error) {
//				panic("mock out the OpenView method")
//			},
//			PostMessageContextFunc: func(ctx context.Context, channelID string, options ...slackslack.MsgOption) (string, string, error) {
//				panic("mock out the PostMessageContext method")
//			},
//			UpdateMessageContextFunc: func(ctx context.Context, channelID string, timestamp string, options ...slackslack.MsgOption) (string, string, string, error) {
//				panic("mock out the UpdateMessageContext method")
//			},
//			UploadFileV2ContextFunc: func(ctx context.Context, params slackslack.UploadFileV2Parameters) (*slackslack.FileSummary, error) {
//				panic("mock out the UploadFileV2Context method")
//			},
//		}
//
//		// use mockedSlackClient in code that requires interfaces.SlackClient
//		// and then make assertions.
//
//	}
type SlackClientMock struct {
	// AuthTestFunc mocks the AuthTest method.
	AuthTestFunc func() (*slackslack.AuthTestResponse, error)

	// OpenViewFunc mocks the OpenView method.
	OpenViewFunc func(triggerID string, view slackslack.ModalViewRequest) (*slackslack.ViewResponse, error)

	// PostMessageContextFunc mocks the PostMessageContext method.
	PostMessageContextFunc func(ctx context.Context, channelID string, options ...slackslack.MsgOption) (string, string, error)

	// UpdateMessageContextFunc mocks the UpdateMessageContext method.
	UpdateMessageContextFunc func(ctx context.Context, channelID string, timestamp string, options ...slackslack.MsgOption) (string, string, string, error)

	// UploadFileV2ContextFunc mocks the UploadFileV2Context method.
	UploadFileV2ContextFunc func(ctx context.Context, params slackslack.UploadFileV2Parameters) (*slackslack.FileSummary, error)

	// calls tracks calls to the methods.
	calls struct {
		// AuthTest holds details about calls to the AuthTest method.
		AuthTest []struct {
		}
		// OpenView holds details about calls to the OpenView method.
		OpenView []struct {
			// TriggerID is the triggerID argument value.
			TriggerID string
			// View is the view argument value.
			View slackslack.ModalViewRequest
		}
		// PostMessageContext holds details about calls to the PostMessageContext method.
		PostMessageContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID string
			// Options is the options argument value.
			Options []slackslack.MsgOption
		}
		// UpdateMessageContext holds details about calls to the UpdateMessageContext method.
		UpdateMessageContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID string
			// Timestamp is the timestamp argument value.
			Timestamp string
			// Options is the options argument value.
			Options []slackslack.MsgOption
		}
		// UploadFileV2Context holds details about calls to the UploadFileV2Context method.
		UploadFileV2Context []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params slackslack.UploadFileV2Parameters
		}
	}
	lockAuthTest             sync.RWMutex
	lockOpenView             sync.RWMutex
	lockPostMessageContext   sync.RWMutex
	lockUpdateMessageContext sync.RWMutex
	lockUploadFileV2Context  sync.RWMutex
}

// AuthTest calls AuthTestFunc.
func (mock *SlackClientMock) AuthTest() (*slackslack.AuthTestResponse, error) {
	callInfo := struct {
	}{}
	mock.lockAuthTest.Lock()
	mock.calls.AuthTest = append(mock.calls.AuthTest, callInfo)
	mock.lockAuthTest.Unlock()
	if mock.AuthTestFunc == nil {
		var (
			authTestResponseOut *slackslack.AuthTestResponse
			errOut              error
		)
		return authTestResponseOut, errOut
	}
	return mock.AuthTestFunc()
}

// AuthTestCalls gets all the calls that were made to AuthTest.
// Check the length with:
//
//	len(mockedSlackClient.AuthTestCalls())
func (mock *SlackClientMock) AuthTestCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAuthTest.RLock()
	calls = mock.calls.AuthTest
	mock.lockAuthTest.RUnlock()
	return calls
}

// OpenView calls OpenViewFunc.
func (mock *SlackClientMock) OpenView(triggerID string, view slackslack.ModalViewRequest) (*slackslack.ViewResponse, error) {
	callInfo := struct {
		TriggerID string
		View      slackslack.ModalViewRequest
	}{
		TriggerID: triggerID,
		View:      view,
	}
	mock.lockOpenView.Lock()
	mock.calls.OpenView = append(mock.calls.OpenView, callInfo)
	mock.lockOpenView.Unlock()
	if mock.OpenViewFunc == nil {
		var (
			viewResponseOut *slackslack.ViewResponse
			errOut          error
		)
		return viewResponseOut, errOut
	}
	return mock.OpenViewFunc(triggerID, view)
}

// OpenViewCalls gets all the calls that were made to OpenView.
// Check the length with:
//
//	len(mockedSlackClient.OpenViewCalls())
func (mock *SlackClientMock) OpenViewCalls() []struct {
	TriggerID string
	View      slackslack.ModalViewRequest
} {
	var calls []struct {
		TriggerID string
		View      slackslack.ModalViewRequest
	}
	mock.lockOpenView.RLock()
	calls = mock.calls.OpenView
	mock.lockOpenView.RUnlock()
	return calls
}

// PostMessageContext calls PostMessageContextFunc.
func (mock *SlackClientMock) PostMessageContext(ctx context.Context, channelID string, options ...slackslack.MsgOption) (string, string, error) {
	callInfo := struct {
		Ctx       context.Context
		ChannelID string
		Options   []slackslack.MsgOption
	}{
		Ctx:       ctx,
		ChannelID: channelID,
		Options:   options,
	}
	mock.lockPostMessageContext.Lock()
	mock.calls.PostMessageContext = append(mock.calls.PostMessageContext, callInfo)
	mock.lockPostMessageContext.Unlock()
	if mock.PostMessageContextFunc == nil {
		var (
			sOut1  string
			sOut2  string
			errOut error
		)
		return sOut1, sOut2, errOut
	}
	return mock.PostMessageContextFunc(ctx, channelID, options...)
}

// PostMessageContextCalls gets all the calls that were made to PostMessageContext.
// Check the length with:
//
//	len(mockedSlackClient.PostMessageContextCalls())
func (mock *SlackClientMock) PostMessageContextCalls() []struct {
	Ctx       context.Context
	ChannelID string
	Options   []slackslack.MsgOption
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID string
		Options   []slackslack.MsgOption
	}
	mock.lockPostMessageContext.RLock()
	calls = mock.calls.PostMessageContext
	mock.lockPostMessageContext.RUnlock()
	return calls
}

// UpdateMessageContext calls UpdateMessageContextFunc.
func (mock *SlackClientMock) UpdateMessageContext(ctx context.Context, channelID string, timestamp string, options ...slackslack.MsgOption) (string, string, string, error) {
	callInfo := struct {
		Ctx       context.Context
		ChannelID string
		Timestamp string
		Options   []slackslack.MsgOption
	}{
		Ctx:       ctx,
		ChannelID: channelID,
		Timestamp: timestamp,
		Options:   options,
	}
	mock.lockUpdateMessageContext.Lock()
	mock.calls.UpdateMessageContext = append(mock.calls.UpdateMessageContext, callInfo)
	mock.lockUpdateMessageContext.Unlock()
	if mock.UpdateMessageContextFunc == nil {
		var (
			sOut1  string
			sOut2  string
			sOut3  string
			errOut error
		)
		return sOut1, sOut2, sOut3, errOut
	}
	return mock.UpdateMessageContextFunc(ctx, channelID, timestamp, options...)
}

// UpdateMessageContextCalls gets all the calls that were made to UpdateMessageContext.
// Check the length with:
//
//	len(mockedSlackClient.UpdateMessageContextCalls())
func (mock *SlackClientMock) UpdateMessageContextCalls() []struct {
	Ctx       context.Context
	ChannelID string
	Timestamp string
	Options   []slackslack.MsgOption
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID string
		Timestamp string
		Options   []slackslack.MsgOption
	}
	mock.lockUpdateMessageContext.RLock()
	calls = mock.calls.UpdateMessageContext
	mock.lockUpdateMessageContext.RUnlock()
	return calls
}

// UploadFileV2Context calls UploadFileV2ContextFunc.
func (mock *SlackClientMock) UploadFileV2Context(ctx context.Context, params slackslack.UploadFileV2Parameters) (*slackslack.FileSummary, error) {
	callInfo := struct {
		Ctx    context.Context
		Params slackslack.UploadFileV2Parameters
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockUploadFileV2Context.Lock()
	mock.calls.UploadFileV2Context = append(mock.calls.UploadFileV2Context, callInfo)
	mock.lockUploadFileV2Context.Unlock()
	if mock.UploadFileV2ContextFunc == nil {
		var (
			fileSummaryOut *slackslack.FileSummary
			errOut         error
		)
		return fileSummaryOut, errOut
	}
	return mock.UploadFileV2ContextFunc(ctx, params)
}

// UploadFileV2ContextCalls gets all the calls that were made to UploadFileV2Context.
// Check the length with:
//
//	len(mockedSlackClient.UploadFileV2ContextCalls())
func (mock *SlackClientMock) UploadFileV2ContextCalls() []struct {
	Ctx    context.Context
	Params slackslack.UploadFileV2Parameters
} {
	var calls []struct {
		Ctx    context.Context
		Params slackslack.UploadFileV2Parameters
	}
	mock.lockUploadFileV2Context.RLock()
	calls = mock.calls.UploadFileV2Context
	mock.lockUploadFileV2Context.RUnlock()
	return calls
}

// SlackThreadServiceMock is a mock implementation of interfaces.SlackThreadService.
//
//	func TestSomethingThatUsesSlackThreadService(t *testing.T) {
//
//		// make and configure a mocked interfaces.SlackThreadService
//		mockedSlackThreadService := &SlackThreadServiceMock{
//			NewStateFuncFunc: func(ctx context.Context, message string) func(ctx context.Context, msg string) {
//				panic("mock out the NewStateFunc method")
//			},
//			ReplyFunc: func(ctx context.Context, message string)  {
//				panic("mock out the Reply method")
//			},
//		}
//
//		// use mockedSlackThreadService in code that requires interfaces.SlackThreadService
//		// and then make assertions.
//
//	}
type SlackThreadServiceMock struct {
	// NewStateFuncFunc mocks the NewStateFunc method.
	NewStateFuncFunc func(ctx context.Context, message string) func(ctx context.Context, msg string)

	// ReplyFunc mocks the Reply method.
	ReplyFunc func(ctx context.Context, message string)

	// calls tracks calls to the methods.
	calls struct {
		// NewStateFunc holds details about calls to the NewStateFunc method.
		NewStateFunc []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message string
		}
		// Reply holds details about calls to the Reply method.
		Reply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message string
		}
	}
	lockNewStateFunc sync.RWMutex
	lockReply        sync.RWMutex
}

// NewStateFunc calls NewStateFuncFunc.
func (mock *SlackThreadServiceMock) NewStateFunc(ctx context.Context, message string) func(ctx context.Context, msg string) {
	callInfo := struct {
		Ctx     context.Context
		Message string
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockNewStateFunc.Lock()
	mock.calls.NewStateFunc = append(mock.calls.NewStateFunc, callInfo)
	mock.lockNewStateFunc.Unlock()
	if mock.NewStateFuncFunc == nil {
		var (
			fnOut func(ctx context.Context, msg string)
		)
		return fnOut
	}
	return mock.NewStateFuncFunc(ctx, message)
}

// NewStateFuncCalls gets all the calls that were made to NewStateFunc.
// Check the length with:
//
//	len(mockedSlackThreadService.NewStateFuncCalls())
func (mock *SlackThreadServiceMock) NewStateFuncCalls() []struct {
	Ctx     context.Context
	Message string
} {
	var calls []struct {
		Ctx     context.Context
		Message string
	}
	mock.lockNewStateFunc.RLock()
	calls = mock.calls.NewStateFunc
	mock.lockNewStateFunc.RUnlock()
	return calls
}

// Reply calls ReplyFunc.
func (mock *SlackThreadServiceMock) Reply(ctx context.Context, message string) {
	callInfo := struct {
		Ctx     context.Context
		Message string
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockReply.Lock()
	mock.calls.Reply = append(mock.calls.Reply, callInfo)
	mock.lockReply.Unlock()
	if mock.ReplyFunc == nil {
		return
	}
	mock.ReplyFunc(ctx, message)
}

// ReplyCalls gets all the calls that were made to Reply.
// Check the length with:
//
//	len(mockedSlackThreadService.ReplyCalls())
func (mock *SlackThreadServiceMock) ReplyCalls() []struct {
	Ctx     context.Context
	Message string
} {
	var calls []struct {
		Ctx     context.Context
		Message string
	}
	mock.lockReply.RLock()
	calls = mock.calls.Reply
	mock.lockReply.RUnlock()
	return calls
}

// RepositoryMock is a mock implementation of interfaces.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked interfaces.Repository
//		mockedRepository := &RepositoryMock{
//			BatchGetAlertsFunc: func(ctx context.Context, alertIDs []types.AlertID) (alert.Alerts, error) {
//				panic("mock out the BatchGetAlerts method")
//			},
//			BindAlertToTicketFunc: func(ctx context.Context, alertID types.AlertID, ticketID types.TicketID) error {
//				panic("mock out the BindAlertToTicket method")
//			},
//			FindSimilarAlertsFunc: func(ctx context.Context, alertMoqParam alert.Alert, limit int) (alert.Alerts, error) {
//				panic("mock out the FindSimilarAlerts method")
//			},
//			GetAlertFunc: func(ctx context.Context, alertID types.AlertID) (*alert.Alert, error) {
//				panic("mock out the GetAlert method")
//			},
//			GetAlertByThreadFunc: func(ctx context.Context, thread modelslack.Thread) (*alert.Alert, error) {
//				panic("mock out the GetAlertByThread method")
//			},
//			GetAlertListFunc: func(ctx context.Context, listID types.AlertListID) (*alert.List, error) {
//				panic("mock out the GetAlertList method")
//			},
//			GetAlertListByThreadFunc: func(ctx context.Context, thread modelslack.Thread) (*alert.List, error) {
//				panic("mock out the GetAlertListByThread method")
//			},
//			GetAlertWithoutTicketFunc: func(ctx context.Context) (alert.Alerts, error) {
//				panic("mock out the GetAlertWithoutTicket method")
//			},
//			GetAlertsBySpanFunc: func(ctx context.Context, begin time.Time, end time.Time) (alert.Alerts, error) {
//				panic("mock out the GetAlertsBySpan method")
//			},
//			GetLatestAlertListInThreadFunc: func(ctx context.Context, thread modelslack.Thread) (*alert.List, error) {
//				panic("mock out the GetLatestAlertListInThread method")
//			},
//			GetLatestHistoryFunc: func(ctx context.Context, sessionID types.SessionID) (*session.History, error) {
//				panic("mock out the GetLatestHistory method")
//			},
//			GetSessionFunc: func(ctx context.Context, id types.SessionID) (*session.Session, error) {
//				panic("mock out the GetSession method")
//			},
//			GetSessionByThreadFunc: func(ctx context.Context, thread modelslack.Thread) (*session.Session, error) {
//				panic("mock out the GetSessionByThread method")
//			},
//			GetTicketFunc: func(ctx context.Context, ticketID types.TicketID) (*ticket.Ticket, error) {
//				panic("mock out the GetTicket method")
//			},
//			GetTicketByThreadFunc: func(ctx context.Context, thread modelslack.Thread) (*ticket.Ticket, error) {
//				panic("mock out the GetTicketByThread method")
//			},
//			GetTicketCommentsFunc: func(ctx context.Context, ticketID types.TicketID) ([]ticket.Comment, error) {
//				panic("mock out the GetTicketComments method")
//			},
//			PutAlertFunc: func(ctx context.Context, alertMoqParam alert.Alert) error {
//				panic("mock out the PutAlert method")
//			},
//			PutAlertListFunc: func(ctx context.Context, list alert.List) error {
//				panic("mock out the PutAlertList method")
//			},
//			PutHistoryFunc: func(ctx context.Context, sessionID types.SessionID, history *session.History) error {
//				panic("mock out the PutHistory method")
//			},
//			PutSessionFunc: func(ctx context.Context, sessionMoqParam session.Session) error {
//				panic("mock out the PutSession method")
//			},
//			PutTicketFunc: func(ctx context.Context, ticketMoqParam ticket.Ticket) error {
//				panic("mock out the PutTicket method")
//			},
//			PutTicketCommentFunc: func(ctx context.Context, comment ticket.Comment) error {
//				panic("mock out the PutTicketComment method")
//			},
//			SearchAlertsFunc: func(ctx context.Context, path string, op string, value any, limit int) (alert.Alerts, error) {
//				panic("mock out the SearchAlerts method")
//			},
//			UnbindAlertFromTicketFunc: func(ctx context.Context, alertID types.AlertID) error {
//				panic("mock out the UnbindAlertFromTicket method")
//			},
//		}
//
//		// use mockedRepository in code that requires interfaces.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// BatchGetAlertsFunc mocks the BatchGetAlerts method.
	BatchGetAlertsFunc func(ctx context.Context, alertIDs []types.AlertID) (alert.Alerts, error)

	// BindAlertToTicketFunc mocks the BindAlertToTicket method.
	BindAlertToTicketFunc func(ctx context.Context, alertID types.AlertID, ticketID types.TicketID) error

	// FindSimilarAlertsFunc mocks the FindSimilarAlerts method.
	FindSimilarAlertsFunc func(ctx context.Context, alertMoqParam alert.Alert, limit int) (alert.Alerts, error)

	// GetAlertFunc mocks the GetAlert method.
	GetAlertFunc func(ctx context.Context, alertID types.AlertID) (*alert.Alert, error)

	// GetAlertByThreadFunc mocks the GetAlertByThread method.
	GetAlertByThreadFunc func(ctx context.Context, thread modelslack.Thread) (*alert.Alert, error)

	// GetAlertListFunc mocks the GetAlertList method.
	GetAlertListFunc func(ctx context.Context, listID types.AlertListID) (*alert.List, error)

	// GetAlertListByThreadFunc mocks the GetAlertListByThread method.
	GetAlertListByThreadFunc func(ctx context.Context, thread modelslack.Thread) (*alert.List, error)

	// GetAlertWithoutTicketFunc mocks the GetAlertWithoutTicket method.
	GetAlertWithoutTicketFunc func(ctx context.Context) (alert.Alerts, error)

	// GetAlertsBySpanFunc mocks the GetAlertsBySpan method.
	GetAlertsBySpanFunc func(ctx context.Context, begin time.Time, end time.Time) (alert.Alerts, error)

	// GetLatestAlertListInThreadFunc mocks the GetLatestAlertListInThread method.
	GetLatestAlertListInThreadFunc func(ctx context.Context, thread modelslack.Thread) (*alert.List, error)

	// GetLatestHistoryFunc mocks the GetLatestHistory method.
	GetLatestHistoryFunc func(ctx context.Context, sessionID types.SessionID) (*session.History, error)

	// GetSessionFunc mocks the GetSession method.
	GetSessionFunc func(ctx context.Context, id types.SessionID) (*session.Session, error)

	// GetSessionByThreadFunc mocks the GetSessionByThread method.
	GetSessionByThreadFunc func(ctx context.Context, thread modelslack.Thread) (*session.Session, error)

	// GetTicketFunc mocks the GetTicket method.
	GetTicketFunc func(ctx context.Context, ticketID types.TicketID) (*ticket.Ticket, error)

	// GetTicketByThreadFunc mocks the GetTicketByThread method.
	GetTicketByThreadFunc func(ctx context.Context, thread modelslack.Thread) (*ticket.Ticket, error)

	// GetTicketCommentsFunc mocks the GetTicketComments method.
	GetTicketCommentsFunc func(ctx context.Context, ticketID types.TicketID) ([]ticket.Comment, error)

	// PutAlertFunc mocks the PutAlert method.
	PutAlertFunc func(ctx context.Context, alertMoqParam alert.Alert) error

	// PutAlertListFunc mocks the PutAlertList method.
	PutAlertListFunc func(ctx context.Context, list alert.List) error

	// PutHistoryFunc mocks the PutHistory method.
	PutHistoryFunc func(ctx context.Context, sessionID types.SessionID, history *session.History) error

	// PutSessionFunc mocks the PutSession method.
	PutSessionFunc func(ctx context.Context, sessionMoqParam session.Session) error

	// PutTicketFunc mocks the PutTicket method.
	PutTicketFunc func(ctx context.Context, ticketMoqParam ticket.Ticket) error

	// PutTicketCommentFunc mocks the PutTicketComment method.
	PutTicketCommentFunc func(ctx context.Context, comment ticket.Comment) error

	// SearchAlertsFunc mocks the SearchAlerts method.
	SearchAlertsFunc func(ctx context.Context, path string, op string, value any, limit int) (alert.Alerts, error)

	// UnbindAlertFromTicketFunc mocks the UnbindAlertFromTicket method.
	UnbindAlertFromTicketFunc func(ctx context.Context, alertID types.AlertID) error

	// calls tracks calls to the methods.
	calls struct {
		// BatchGetAlerts holds details about calls to the BatchGetAlerts method.
		BatchGetAlerts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertIDs is the alertIDs argument value.
			AlertIDs []types.AlertID
		}
		// BindAlertToTicket holds details about calls to the BindAlertToTicket method.
		BindAlertToTicket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertID is the alertID argument value.
			AlertID types.AlertID
			// TicketID is the ticketID argument value.
			TicketID types.TicketID
		}
		// FindSimilarAlerts holds details about calls to the FindSimilarAlerts method.
		FindSimilarAlerts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertMoqParam is the alertMoqParam argument value.
			AlertMoqParam alert.Alert
			// Limit is the limit argument value.
			Limit int
		}
		// GetAlert holds details about calls to the GetAlert method.
		GetAlert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertID is the alertID argument value.
			AlertID types.AlertID
		}
		// GetAlertByThread holds details about calls to the GetAlertByThread method.
		GetAlertByThread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Thread is the thread argument value.
			Thread modelslack.Thread
		}
		// GetAlertList holds details about calls to the GetAlertList method.
		GetAlertList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ListID is the listID argument value.
			ListID types.AlertListID
		}
		// GetAlertListByThread holds details about calls to the GetAlertListByThread method.
		GetAlertListByThread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Thread is the thread argument value.
			Thread modelslack.Thread
		}
		// GetAlertWithoutTicket holds details about calls to the GetAlertWithoutTicket method.
		GetAlertWithoutTicket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAlertsBySpan holds details about calls to the GetAlertsBySpan method.
		GetAlertsBySpan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Begin is the begin argument value.
			Begin time.Time
			// End is the end argument value.
			End time.Time
		}
		// GetLatestAlertListInThread holds details about calls to the GetLatestAlertListInThread method.
		GetLatestAlertListInThread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Thread is the thread argument value.
			Thread modelslack.Thread
		}
		// GetLatestHistory holds details about calls to the GetLatestHistory method.
		GetLatestHistory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionID is the sessionID argument value.
			SessionID types.SessionID
		}
		// GetSession holds details about calls to the GetSession method.
		GetSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID types.SessionID
		}
		// GetSessionByThread holds details about calls to the GetSessionByThread method.
		GetSessionByThread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Thread is the thread argument value.
			Thread modelslack.Thread
		}
		// GetTicket holds details about calls to the GetTicket method.
		GetTicket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TicketID is the ticketID argument value.
			TicketID types.TicketID
		}
		// GetTicketByThread holds details about calls to the GetTicketByThread method.
		GetTicketByThread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Thread is the thread argument value.
			Thread modelslack.Thread
		}
		// GetTicketComments holds details about calls to the GetTicketComments method.
		GetTicketComments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TicketID is the ticketID argument value.
			TicketID types.TicketID
		}
		// PutAlert holds details about calls to the PutAlert method.
		PutAlert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertMoqParam is the alertMoqParam argument value.
			AlertMoqParam alert.Alert
		}
		// PutAlertList holds details about calls to the PutAlertList method.
		PutAlertList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// List is the list argument value.
			List alert.List
		}
		// PutHistory holds details about calls to the PutHistory method.
		PutHistory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionID is the sessionID argument value.
			SessionID types.SessionID
			// History is the history argument value.
			History *session.History
		}
		// PutSession holds details about calls to the PutSession method.
		PutSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionMoqParam is the sessionMoqParam argument value.
			SessionMoqParam session.Session
		}
		// PutTicket holds details about calls to the PutTicket method.
		PutTicket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TicketMoqParam is the ticketMoqParam argument value.
			TicketMoqParam ticket.Ticket
		}
		// PutTicketComment holds details about calls to the PutTicketComment method.
		PutTicketComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Comment is the comment argument value.
			Comment ticket.Comment
		}
		// SearchAlerts holds details about calls to the SearchAlerts method.
		SearchAlerts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Op is the op argument value.
			Op string
			// Value is the value argument value.
			Value any
			// Limit is the limit argument value.
			Limit int
		}
		// UnbindAlertFromTicket holds details about calls to the UnbindAlertFromTicket method.
		UnbindAlertFromTicket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertID is the alertID argument value.
			AlertID types.AlertID
		}
	}
	lockBatchGetAlerts             sync.RWMutex
	lockBindAlertToTicket          sync.RWMutex
	lockFindSimilarAlerts          sync.RWMutex
	lockGetAlert                   sync.RWMutex
	lockGetAlertByThread           sync.RWMutex
	lockGetAlertList               sync.RWMutex
	lockGetAlertListByThread       sync.RWMutex
	lockGetAlertWithoutTicket      sync.RWMutex
	lockGetAlertsBySpan            sync.RWMutex
	lockGetLatestAlertListInThread sync.RWMutex
	lockGetLatestHistory           sync.RWMutex
	lockGetSession                 sync.RWMutex
	lockGetSessionByThread         sync.RWMutex
	lockGetTicket                  sync.RWMutex
	lockGetTicketByThread          sync.RWMutex
	lockGetTicketComments          sync.RWMutex
	lockPutAlert                   sync.RWMutex
	lockPutAlertList               sync.RWMutex
	lockPutHistory                 sync.RWMutex
	lockPutSession                 sync.RWMutex
	lockPutTicket                  sync.RWMutex
	lockPutTicketComment           sync.RWMutex
	lockSearchAlerts               sync.RWMutex
	lockUnbindAlertFromTicket      sync.RWMutex
}

// BatchGetAlerts calls BatchGetAlertsFunc.
func (mock *RepositoryMock) BatchGetAlerts(ctx context.Context, alertIDs []types.AlertID) (alert.Alerts, error) {
	callInfo := struct {
		Ctx      context.Context
		AlertIDs []types.AlertID
	}{
		Ctx:      ctx,
		AlertIDs: alertIDs,
	}
	mock.lockBatchGetAlerts.Lock()
	mock.calls.BatchGetAlerts = append(mock.calls.BatchGetAlerts, callInfo)
	mock.lockBatchGetAlerts.Unlock()
	if mock.BatchGetAlertsFunc == nil {
		var (
			alertsOut alert.Alerts
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.BatchGetAlertsFunc(ctx, alertIDs)
}

// BatchGetAlertsCalls gets all the calls that were made to BatchGetAlerts.
// Check the length with:
//
//	len(mockedRepository.BatchGetAlertsCalls())
func (mock *RepositoryMock) BatchGetAlertsCalls() []struct {
	Ctx      context.Context
	AlertIDs []types.AlertID
} {
	var calls []struct {
		Ctx      context.Context
		AlertIDs []types.AlertID
	}
	mock.lockBatchGetAlerts.RLock()
	calls = mock.calls.BatchGetAlerts
	mock.lockBatchGetAlerts.RUnlock()
	return calls
}

// BindAlertToTicket calls BindAlertToTicketFunc.
func (mock *RepositoryMock) BindAlertToTicket(ctx context.Context, alertID types.AlertID, ticketID types.TicketID) error {
	callInfo := struct {
		Ctx      context.Context
		AlertID  types.AlertID
		TicketID types.TicketID
	}{
		Ctx:      ctx,
		AlertID:  alertID,
		TicketID: ticketID,
	}
	mock.lockBindAlertToTicket.Lock()
	mock.calls.BindAlertToTicket = append(mock.calls.BindAlertToTicket, callInfo)
	mock.lockBindAlertToTicket.Unlock()
	if mock.BindAlertToTicketFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.BindAlertToTicketFunc(ctx, alertID, ticketID)
}

// BindAlertToTicketCalls gets all the calls that were made to BindAlertToTicket.
// Check the length with:
//
//	len(mockedRepository.BindAlertToTicketCalls())
func (mock *RepositoryMock) BindAlertToTicketCalls() []struct {
	Ctx      context.Context
	AlertID  types.AlertID
	TicketID types.TicketID
} {
	var calls []struct {
		Ctx      context.Context
		AlertID  types.AlertID
		TicketID types.TicketID
	}
	mock.lockBindAlertToTicket.RLock()
	calls = mock.calls.BindAlertToTicket
	mock.lockBindAlertToTicket.RUnlock()
	return calls
}

// FindSimilarAlerts calls FindSimilarAlertsFunc.
func (mock *RepositoryMock) FindSimilarAlerts(ctx context.Context, alertMoqParam alert.Alert, limit int) (alert.Alerts, error) {
	callInfo := struct {
		Ctx           context.Context
		AlertMoqParam alert.Alert
		Limit         int
	}{
		Ctx:           ctx,
		AlertMoqParam: alertMoqParam,
		Limit:         limit,
	}
	mock.lockFindSimilarAlerts.Lock()
	mock.calls.FindSimilarAlerts = append(mock.calls.FindSimilarAlerts, callInfo)
	mock.lockFindSimilarAlerts.Unlock()
	if mock.FindSimilarAlertsFunc == nil {
		var (
			alertsOut alert.Alerts
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.FindSimilarAlertsFunc(ctx, alertMoqParam, limit)
}

// FindSimilarAlertsCalls gets all the calls that were made to FindSimilarAlerts.
// Check the length with:
//
//	len(mockedRepository.FindSimilarAlertsCalls())
func (mock *RepositoryMock) FindSimilarAlertsCalls() []struct {
	Ctx           context.Context
	AlertMoqParam alert.Alert
	Limit         int
} {
	var calls []struct {
		Ctx           context.Context
		AlertMoqParam alert.Alert
		Limit         int
	}
	mock.lockFindSimilarAlerts.RLock()
	calls = mock.calls.FindSimilarAlerts
	mock.lockFindSimilarAlerts.RUnlock()
	return calls
}

// GetAlert calls GetAlertFunc.
func (mock *RepositoryMock) GetAlert(ctx context.Context, alertID types.AlertID) (*alert.Alert, error) {
	callInfo := struct {
		Ctx     context.Context
		AlertID types.AlertID
	}{
		Ctx:     ctx,
		AlertID: alertID,
	}
	mock.lockGetAlert.Lock()
	mock.calls.GetAlert = append(mock.calls.GetAlert, callInfo)
	mock.lockGetAlert.Unlock()
	if mock.GetAlertFunc == nil {
		var (
			alertOut *alert.Alert
			errOut   error
		)
		return alertOut, errOut
	}
	return mock.GetAlertFunc(ctx, alertID)
}

// GetAlertCalls gets all the calls that were made to GetAlert.
// Check the length with:
//
//	len(mockedRepository.GetAlertCalls())
func (mock *RepositoryMock) GetAlertCalls() []struct {
	Ctx     context.Context
	AlertID types.AlertID
} {
	var calls []struct {
		Ctx     context.Context
		AlertID types.AlertID
	}
	mock.lockGetAlert.RLock()
	calls = mock.calls.GetAlert
	mock.lockGetAlert.RUnlock()
	return calls
}

// GetAlertByThread calls GetAlertByThreadFunc.
func (mock *RepositoryMock) GetAlertByThread(ctx context.Context, thread modelslack.Thread) (*alert.Alert, error) {
	callInfo := struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}{
		Ctx:    ctx,
		Thread: thread,
	}
	mock.lockGetAlertByThread.Lock()
	mock.calls.GetAlertByThread = append(mock.calls.GetAlertByThread, callInfo)
	mock.lockGetAlertByThread.Unlock()
	if mock.GetAlertByThreadFunc == nil {
		var (
			alertOut *alert.Alert
			errOut   error
		)
		return alertOut, errOut
	}
	return mock.GetAlertByThreadFunc(ctx, thread)
}

// GetAlertByThreadCalls gets all the calls that were made to GetAlertByThread.
// Check the length with:
//
//	len(mockedRepository.GetAlertByThreadCalls())
func (mock *RepositoryMock) GetAlertByThreadCalls() []struct {
	Ctx    context.Context
	Thread modelslack.Thread
} {
	var calls []struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}
	mock.lockGetAlertByThread.RLock()
	calls = mock.calls.GetAlertByThread
	mock.lockGetAlertByThread.RUnlock()
	return calls
}

// GetAlertList calls GetAlertListFunc.
func (mock *RepositoryMock) GetAlertList(ctx context.Context, listID types.AlertListID) (*alert.List, error) {
	callInfo := struct {
		Ctx    context.Context
		ListID types.AlertListID
	}{
		Ctx:    ctx,
		ListID: listID,
	}
	mock.lockGetAlertList.Lock()
	mock.calls.GetAlertList = append(mock.calls.GetAlertList, callInfo)
	mock.lockGetAlertList.Unlock()
	if mock.GetAlertListFunc == nil {
		var (
			listOut *alert.List
			errOut  error
		)
		return listOut, errOut
	}
	return mock.GetAlertListFunc(ctx, listID)
}

// GetAlertListCalls gets all the calls that were made to GetAlertList.
// Check the length with:
//
//	len(mockedRepository.GetAlertListCalls())
func (mock *RepositoryMock) GetAlertListCalls() []struct {
	Ctx    context.Context
	ListID types.AlertListID
} {
	var calls []struct {
		Ctx    context.Context
		ListID types.AlertListID
	}
	mock.lockGetAlertList.RLock()
	calls = mock.calls.GetAlertList
	mock.lockGetAlertList.RUnlock()
	return calls
}

// GetAlertListByThread calls GetAlertListByThreadFunc.
func (mock *RepositoryMock) GetAlertListByThread(ctx context.Context, thread modelslack.Thread) (*alert.List, error) {
	callInfo := struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}{
		Ctx:    ctx,
		Thread: thread,
	}
	mock.lockGetAlertListByThread.Lock()
	mock.calls.GetAlertListByThread = append(mock.calls.GetAlertListByThread, callInfo)
	mock.lockGetAlertListByThread.Unlock()
	if mock.GetAlertListByThreadFunc == nil {
		var (
			listOut *alert.List
			errOut  error
		)
		return listOut, errOut
	}
	return mock.GetAlertListByThreadFunc(ctx, thread)
}

// GetAlertListByThreadCalls gets all the calls that were made to GetAlertListByThread.
// Check the length with:
//
//	len(mockedRepository.GetAlertListByThreadCalls())
func (mock *RepositoryMock) GetAlertListByThreadCalls() []struct {
	Ctx    context.Context
	Thread modelslack.Thread
} {
	var calls []struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}
	mock.lockGetAlertListByThread.RLock()
	calls = mock.calls.GetAlertListByThread
	mock.lockGetAlertListByThread.RUnlock()
	return calls
}

// GetAlertWithoutTicket calls GetAlertWithoutTicketFunc.
func (mock *RepositoryMock) GetAlertWithoutTicket(ctx context.Context) (alert.Alerts, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAlertWithoutTicket.Lock()
	mock.calls.GetAlertWithoutTicket = append(mock.calls.GetAlertWithoutTicket, callInfo)
	mock.lockGetAlertWithoutTicket.Unlock()
	if mock.GetAlertWithoutTicketFunc == nil {
		var (
			alertsOut alert.Alerts
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.GetAlertWithoutTicketFunc(ctx)
}

// GetAlertWithoutTicketCalls gets all the calls that were made to GetAlertWithoutTicket.
// Check the length with:
//
//	len(mockedRepository.GetAlertWithoutTicketCalls())
func (mock *RepositoryMock) GetAlertWithoutTicketCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAlertWithoutTicket.RLock()
	calls = mock.calls.GetAlertWithoutTicket
	mock.lockGetAlertWithoutTicket.RUnlock()
	return calls
}

// GetAlertsBySpan calls GetAlertsBySpanFunc.
func (mock *RepositoryMock) GetAlertsBySpan(ctx context.Context, begin time.Time, end time.Time) (alert.Alerts, error) {
	callInfo := struct {
		Ctx   context.Context
		Begin time.Time
		End   time.Time
	}{
		Ctx:   ctx,
		Begin: begin,
		End:   end,
	}
	mock.lockGetAlertsBySpan.Lock()
	mock.calls.GetAlertsBySpan = append(mock.calls.GetAlertsBySpan, callInfo)
	mock.lockGetAlertsBySpan.Unlock()
	if mock.GetAlertsBySpanFunc == nil {
		var (
			alertsOut alert.Alerts
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.GetAlertsBySpanFunc(ctx, begin, end)
}

// GetAlertsBySpanCalls gets all the calls that were made to GetAlertsBySpan.
// Check the length with:
//
//	len(mockedRepository.GetAlertsBySpanCalls())
func (mock *RepositoryMock) GetAlertsBySpanCalls() []struct {
	Ctx   context.Context
	Begin time.Time
	End   time.Time
} {
	var calls []struct {
		Ctx   context.Context
		Begin time.Time
		End   time.Time
	}
	mock.lockGetAlertsBySpan.RLock()
	calls = mock.calls.GetAlertsBySpan
	mock.lockGetAlertsBySpan.RUnlock()
	return calls
}

// GetLatestAlertListInThread calls GetLatestAlertListInThreadFunc.
func (mock *RepositoryMock) GetLatestAlertListInThread(ctx context.Context, thread modelslack.Thread) (*alert.List, error) {
	callInfo := struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}{
		Ctx:    ctx,
		Thread: thread,
	}
	mock.lockGetLatestAlertListInThread.Lock()
	mock.calls.GetLatestAlertListInThread = append(mock.calls.GetLatestAlertListInThread, callInfo)
	mock.lockGetLatestAlertListInThread.Unlock()
	if mock.GetLatestAlertListInThreadFunc == nil {
		var (
			listOut *alert.List
			errOut  error
		)
		return listOut, errOut
	}
	return mock.GetLatestAlertListInThreadFunc(ctx, thread)
}

// GetLatestAlertListInThreadCalls gets all the calls that were made to GetLatestAlertListInThread.
// Check the length with:
//
//	len(mockedRepository.GetLatestAlertListInThreadCalls())
func (mock *RepositoryMock) GetLatestAlertListInThreadCalls() []struct {
	Ctx    context.Context
	Thread modelslack.Thread
} {
	var calls []struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}
	mock.lockGetLatestAlertListInThread.RLock()
	calls = mock.calls.GetLatestAlertListInThread
	mock.lockGetLatestAlertListInThread.RUnlock()
	return calls
}

// GetLatestHistory calls GetLatestHistoryFunc.
func (mock *RepositoryMock) GetLatestHistory(ctx context.Context, sessionID types.SessionID) (*session.History, error) {
	callInfo := struct {
		Ctx       context.Context
		SessionID types.SessionID
	}{
		Ctx:       ctx,
		SessionID: sessionID,
	}
	mock.lockGetLatestHistory.Lock()
	mock.calls.GetLatestHistory = append(mock.calls.GetLatestHistory, callInfo)
	mock.lockGetLatestHistory.Unlock()
	if mock.GetLatestHistoryFunc == nil {
		var (
			historyOut *session.History
			errOut     error
		)
		return historyOut, errOut
	}
	return mock.GetLatestHistoryFunc(ctx, sessionID)
}

// GetLatestHistoryCalls gets all the calls that were made to GetLatestHistory.
// Check the length with:
//
//	len(mockedRepository.GetLatestHistoryCalls())
func (mock *RepositoryMock) GetLatestHistoryCalls() []struct {
	Ctx       context.Context
	SessionID types.SessionID
} {
	var calls []struct {
		Ctx       context.Context
		SessionID types.SessionID
	}
	mock.lockGetLatestHistory.RLock()
	calls = mock.calls.GetLatestHistory
	mock.lockGetLatestHistory.RUnlock()
	return calls
}

// GetSession calls GetSessionFunc.
func (mock *RepositoryMock) GetSession(ctx context.Context, id types.SessionID) (*session.Session, error) {
	callInfo := struct {
		Ctx context.Context
		ID  types.SessionID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetSession.Lock()
	mock.calls.GetSession = append(mock.calls.GetSession, callInfo)
	mock.lockGetSession.Unlock()
	if mock.GetSessionFunc == nil {
		var (
			sessionOut *session.Session
			errOut     error
		)
		return sessionOut, errOut
	}
	return mock.GetSessionFunc(ctx, id)
}

// GetSessionCalls gets all the calls that were made to GetSession.
// Check the length with:
//
//	len(mockedRepository.GetSessionCalls())
func (mock *RepositoryMock) GetSessionCalls() []struct {
	Ctx context.Context
	ID  types.SessionID
} {
	var calls []struct {
		Ctx context.Context
		ID  types.SessionID
	}
	mock.lockGetSession.RLock()
	calls = mock.calls.GetSession
	mock.lockGetSession.RUnlock()
	return calls
}

// GetSessionByThread calls GetSessionByThreadFunc.
func (mock *RepositoryMock) GetSessionByThread(ctx context.Context, thread modelslack.Thread) (*session.Session, error) {
	callInfo := struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}{
		Ctx:    ctx,
		Thread: thread,
	}
	mock.lockGetSessionByThread.Lock()
	mock.calls.GetSessionByThread = append(mock.calls.GetSessionByThread, callInfo)
	mock.lockGetSessionByThread.Unlock()
	if mock.GetSessionByThreadFunc == nil {
		var (
			sessionOut *session.Session
			errOut     error
		)
		return sessionOut, errOut
	}
	return mock.GetSessionByThreadFunc(ctx, thread)
}

// GetSessionByThreadCalls gets all the calls that were made to GetSessionByThread.
// Check the length with:
//
//	len(mockedRepository.GetSessionByThreadCalls())
func (mock *RepositoryMock) GetSessionByThreadCalls() []struct {
	Ctx    context.Context
	Thread modelslack.Thread
} {
	var calls []struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}
	mock.lockGetSessionByThread.RLock()
	calls = mock.calls.GetSessionByThread
	mock.lockGetSessionByThread.RUnlock()
	return calls
}

// GetTicket calls GetTicketFunc.
func (mock *RepositoryMock) GetTicket(ctx context.Context, ticketID types.TicketID) (*ticket.Ticket, error) {
	callInfo := struct {
		Ctx      context.Context
		TicketID types.TicketID
	}{
		Ctx:      ctx,
		TicketID: ticketID,
	}
	mock.lockGetTicket.Lock()
	mock.calls.GetTicket = append(mock.calls.GetTicket, callInfo)
	mock.lockGetTicket.Unlock()
	if mock.GetTicketFunc == nil {
		var (
			ticketOut *ticket.Ticket
			errOut    error
		)
		return ticketOut, errOut
	}
	return mock.GetTicketFunc(ctx, ticketID)
}

// GetTicketCalls gets all the calls that were made to GetTicket.
// Check the length with:
//
//	len(mockedRepository.GetTicketCalls())
func (mock *RepositoryMock) GetTicketCalls() []struct {
	Ctx      context.Context
	TicketID types.TicketID
} {
	var calls []struct {
		Ctx      context.Context
		TicketID types.TicketID
	}
	mock.lockGetTicket.RLock()
	calls = mock.calls.GetTicket
	mock.lockGetTicket.RUnlock()
	return calls
}

// GetTicketByThread calls GetTicketByThreadFunc.
func (mock *RepositoryMock) GetTicketByThread(ctx context.Context, thread modelslack.Thread) (*ticket.Ticket, error) {
	callInfo := struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}{
		Ctx:    ctx,
		Thread: thread,
	}
	mock.lockGetTicketByThread.Lock()
	mock.calls.GetTicketByThread = append(mock.calls.GetTicketByThread, callInfo)
	mock.lockGetTicketByThread.Unlock()
	if mock.GetTicketByThreadFunc == nil {
		var (
			ticketOut *ticket.Ticket
			errOut    error
		)
		return ticketOut, errOut
	}
	return mock.GetTicketByThreadFunc(ctx, thread)
}

// GetTicketByThreadCalls gets all the calls that were made to GetTicketByThread.
// Check the length with:
//
//	len(mockedRepository.GetTicketByThreadCalls())
func (mock *RepositoryMock) GetTicketByThreadCalls() []struct {
	Ctx    context.Context
	Thread modelslack.Thread
} {
	var calls []struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}
	mock.lockGetTicketByThread.RLock()
	calls = mock.calls.GetTicketByThread
	mock.lockGetTicketByThread.RUnlock()
	return calls
}

// GetTicketComments calls GetTicketCommentsFunc.
func (mock *RepositoryMock) GetTicketComments(ctx context.Context, ticketID types.TicketID) ([]ticket.Comment, error) {
	callInfo := struct {
		Ctx      context.Context
		TicketID types.TicketID
	}{
		Ctx:      ctx,
		TicketID: ticketID,
	}
	mock.lockGetTicketComments.Lock()
	mock.calls.GetTicketComments = append(mock.calls.GetTicketComments, callInfo)
	mock.lockGetTicketComments.Unlock()
	if mock.GetTicketCommentsFunc == nil {
		var (
			commentsOut []ticket.Comment
			errOut      error
		)
		return commentsOut, errOut
	}
	return mock.GetTicketCommentsFunc(ctx, ticketID)
}

// GetTicketCommentsCalls gets all the calls that were made to GetTicketComments.
// Check the length with:
//
//	len(mockedRepository.GetTicketCommentsCalls())
func (mock *RepositoryMock) GetTicketCommentsCalls() []struct {
	Ctx      context.Context
	TicketID types.TicketID
} {
	var calls []struct {
		Ctx      context.Context
		TicketID types.TicketID
	}
	mock.lockGetTicketComments.RLock()
	calls = mock.calls.GetTicketComments
	mock.lockGetTicketComments.RUnlock()
	return calls
}

// PutAlert calls PutAlertFunc.
func (mock *RepositoryMock) PutAlert(ctx context.Context, alertMoqParam alert.Alert) error {
	callInfo := struct {
		Ctx           context.Context
		AlertMoqParam alert.Alert
	}{
		Ctx:           ctx,
		AlertMoqParam: alertMoqParam,
	}
	mock.lockPutAlert.Lock()
	mock.calls.PutAlert = append(mock.calls.PutAlert, callInfo)
	mock.lockPutAlert.Unlock()
	if mock.PutAlertFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutAlertFunc(ctx, alertMoqParam)
}

// PutAlertCalls gets all the calls that were made to PutAlert.
// Check the length with:
//
//	len(mockedRepository.PutAlertCalls())
func (mock *RepositoryMock) PutAlertCalls() []struct {
	Ctx           context.Context
	AlertMoqParam alert.Alert
} {
	var calls []struct {
		Ctx           context.Context
		AlertMoqParam alert.Alert
	}
	mock.lockPutAlert.RLock()
	calls = mock.calls.PutAlert
	mock.lockPutAlert.RUnlock()
	return calls
}

// PutAlertList calls PutAlertListFunc.
func (mock *RepositoryMock) PutAlertList(ctx context.Context, list alert.List) error {
	callInfo := struct {
		Ctx  context.Context
		List alert.List
	}{
		Ctx:  ctx,
		List: list,
	}
	mock.lockPutAlertList.Lock()
	mock.calls.PutAlertList = append(mock.calls.PutAlertList, callInfo)
	mock.lockPutAlertList.Unlock()
	if mock.PutAlertListFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutAlertListFunc(ctx, list)
}

// PutAlertListCalls gets all the calls that were made to PutAlertList.
// Check the length with:
//
//	len(mockedRepository.PutAlertListCalls())
func (mock *RepositoryMock) PutAlertListCalls() []struct {
	Ctx  context.Context
	List alert.List
} {
	var calls []struct {
		Ctx  context.Context
		List alert.List
	}
	mock.lockPutAlertList.RLock()
	calls = mock.calls.PutAlertList
	mock.lockPutAlertList.RUnlock()
	return calls
}

// PutHistory calls PutHistoryFunc.
func (mock *RepositoryMock) PutHistory(ctx context.Context, sessionID types.SessionID, history *session.History) error {
	callInfo := struct {
		Ctx       context.Context
		SessionID types.SessionID
		History   *session.History
	}{
		Ctx:       ctx,
		SessionID: sessionID,
		History:   history,
	}
	mock.lockPutHistory.Lock()
	mock.calls.PutHistory = append(mock.calls.PutHistory, callInfo)
	mock.lockPutHistory.Unlock()
	if mock.PutHistoryFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutHistoryFunc(ctx, sessionID, history)
}

// PutHistoryCalls gets all the calls that were made to PutHistory.
// Check the length with:
//
//	len(mockedRepository.PutHistoryCalls())
func (mock *RepositoryMock) PutHistoryCalls() []struct {
	Ctx       context.Context
	SessionID types.SessionID
	History   *session.History
} {
	var calls []struct {
		Ctx       context.Context
		SessionID types.SessionID
		History   *session.History
	}
	mock.lockPutHistory.RLock()
	calls = mock.calls.PutHistory
	mock.lockPutHistory.RUnlock()
	return calls
}

// PutSession calls PutSessionFunc.
func (mock *RepositoryMock) PutSession(ctx context.Context, sessionMoqParam session.Session) error {
	callInfo := struct {
		Ctx             context.Context
		SessionMoqParam session.Session
	}{
		Ctx:             ctx,
		SessionMoqParam: sessionMoqParam,
	}
	mock.lockPutSession.Lock()
	mock.calls.PutSession = append(mock.calls.PutSession, callInfo)
	mock.lockPutSession.Unlock()
	if mock.PutSessionFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutSessionFunc(ctx, sessionMoqParam)
}

// PutSessionCalls gets all the calls that were made to PutSession.
// Check the length with:
//
//	len(mockedRepository.PutSessionCalls())
func (mock *RepositoryMock) PutSessionCalls() []struct {
	Ctx             context.Context
	SessionMoqParam session.Session
} {
	var calls []struct {
		Ctx             context.Context
		SessionMoqParam session.Session
	}
	mock.lockPutSession.RLock()
	calls = mock.calls.PutSession
	mock.lockPutSession.RUnlock()
	return calls
}

// PutTicket calls PutTicketFunc.
func (mock *RepositoryMock) PutTicket(ctx context.Context, ticketMoqParam ticket.Ticket) error {
	callInfo := struct {
		Ctx            context.Context
		TicketMoqParam ticket.Ticket
	}{
		Ctx:            ctx,
		TicketMoqParam: ticketMoqParam,
	}
	mock.lockPutTicket.Lock()
	mock.calls.PutTicket = append(mock.calls.PutTicket, callInfo)
	mock.lockPutTicket.Unlock()
	if mock.PutTicketFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutTicketFunc(ctx, ticketMoqParam)
}

// PutTicketCalls gets all the calls that were made to PutTicket.
// Check the length with:
//
//	len(mockedRepository.PutTicketCalls())
func (mock *RepositoryMock) PutTicketCalls() []struct {
	Ctx            context.Context
	TicketMoqParam ticket.Ticket
} {
	var calls []struct {
		Ctx            context.Context
		TicketMoqParam ticket.Ticket
	}
	mock.lockPutTicket.RLock()
	calls = mock.calls.PutTicket
	mock.lockPutTicket.RUnlock()
	return calls
}

// PutTicketComment calls PutTicketCommentFunc.
func (mock *RepositoryMock) PutTicketComment(ctx context.Context, comment ticket.Comment) error {
	callInfo := struct {
		Ctx     context.Context
		Comment ticket.Comment
	}{
		Ctx:     ctx,
		Comment: comment,
	}
	mock.lockPutTicketComment.Lock()
	mock.calls.PutTicketComment = append(mock.calls.PutTicketComment, callInfo)
	mock.lockPutTicketComment.Unlock()
	if mock.PutTicketCommentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutTicketCommentFunc(ctx, comment)
}

// PutTicketCommentCalls gets all the calls that were made to PutTicketComment.
// Check the length with:
//
//	len(mockedRepository.PutTicketCommentCalls())
func (mock *RepositoryMock) PutTicketCommentCalls() []struct {
	Ctx     context.Context
	Comment ticket.Comment
} {
	var calls []struct {
		Ctx     context.Context
		Comment ticket.Comment
	}
	mock.lockPutTicketComment.RLock()
	calls = mock.calls.PutTicketComment
	mock.lockPutTicketComment.RUnlock()
	return calls
}

// SearchAlerts calls SearchAlertsFunc.
func (mock *RepositoryMock) SearchAlerts(ctx context.Context, path string, op string, value any, limit int) (alert.Alerts, error) {
	callInfo := struct {
		Ctx   context.Context
		Path  string
		Op    string
		Value any
		Limit int
	}{
		Ctx:   ctx,
		Path:  path,
		Op:    op,
		Value: value,
		Limit: limit,
	}
	mock.lockSearchAlerts.Lock()
	mock.calls.SearchAlerts = append(mock.calls.SearchAlerts, callInfo)
	mock.lockSearchAlerts.Unlock()
	if mock.SearchAlertsFunc == nil {
		var (
			alertsOut alert.Alerts
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.SearchAlertsFunc(ctx, path, op, value, limit)
}

// SearchAlertsCalls gets all the calls that were made to SearchAlerts.
// Check the length with:
//
//	len(mockedRepository.SearchAlertsCalls())
func (mock *RepositoryMock) SearchAlertsCalls() []struct {
	Ctx   context.Context
	Path  string
	Op    string
	Value any
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Path  string
		Op    string
		Value any
		Limit int
	}
	mock.lockSearchAlerts.RLock()
	calls = mock.calls.SearchAlerts
	mock.lockSearchAlerts.RUnlock()
	return calls
}

// UnbindAlertFromTicket calls UnbindAlertFromTicketFunc.
func (mock *RepositoryMock) UnbindAlertFromTicket(ctx context.Context, alertID types.AlertID) error {
	callInfo := struct {
		Ctx     context.Context
		AlertID types.AlertID
	}{
		Ctx:     ctx,
		AlertID: alertID,
	}
	mock.lockUnbindAlertFromTicket.Lock()
	mock.calls.UnbindAlertFromTicket = append(mock.calls.UnbindAlertFromTicket, callInfo)
	mock.lockUnbindAlertFromTicket.Unlock()
	if mock.UnbindAlertFromTicketFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UnbindAlertFromTicketFunc(ctx, alertID)
}

// UnbindAlertFromTicketCalls gets all the calls that were made to UnbindAlertFromTicket.
// Check the length with:
//
//	len(mockedRepository.UnbindAlertFromTicketCalls())
func (mock *RepositoryMock) UnbindAlertFromTicketCalls() []struct {
	Ctx     context.Context
	AlertID types.AlertID
} {
	var calls []struct {
		Ctx     context.Context
		AlertID types.AlertID
	}
	mock.lockUnbindAlertFromTicket.RLock()
	calls = mock.calls.UnbindAlertFromTicket
	mock.lockUnbindAlertFromTicket.RUnlock()
	return calls
}

// PolicyClientMock is a mock implementation of interfaces.PolicyClient.
//
//	func TestSomethingThatUsesPolicyClient(t *testing.T) {
//
//		// make and configure a mocked interfaces.PolicyClient
//		mockedPolicyClient := &PolicyClientMock{
//			QueryFunc: func(contextMoqParam context.Context, s string, v1 any, v2 any, queryOptions ...opaq.QueryOption) error {
//				panic("mock out the Query method")
//			},
//			SourcesFunc: func() map[string]string {
//				panic("mock out the Sources method")
//			},
//		}
//
//		// use mockedPolicyClient in code that requires interfaces.PolicyClient
//		// and then make assertions.
//
//	}
type PolicyClientMock struct {
	// QueryFunc mocks the Query method.
	QueryFunc func(contextMoqParam context.Context, s string, v1 any, v2 any, queryOptions ...opaq.QueryOption) error

	// SourcesFunc mocks the Sources method.
	SourcesFunc func() map[string]string

	// calls tracks calls to the methods.
	calls struct {
		// Query holds details about calls to the Query method.
		Query []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// V1 is the v1 argument value.
			V1 any
			// V2 is the v2 argument value.
			V2 any
			// QueryOptions is the queryOptions argument value.
			QueryOptions []opaq.QueryOption
		}
		// Sources holds details about calls to the Sources method.
		Sources []struct {
		}
	}
	lockQuery   sync.RWMutex
	lockSources sync.RWMutex
}

// Query calls QueryFunc.
func (mock *PolicyClientMock) Query(contextMoqParam context.Context, s string, v1 any, v2 any, queryOptions ...opaq.QueryOption) error {
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
		V1              any
		V2              any
		QueryOptions    []opaq.QueryOption
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
		V1:              v1,
		V2:              v2,
		QueryOptions:    queryOptions,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	if mock.QueryFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.QueryFunc(contextMoqParam, s, v1, v2, queryOptions...)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedPolicyClient.QueryCalls())
func (mock *PolicyClientMock) QueryCalls() []struct {
	ContextMoqParam context.Context
	S               string
	V1              any
	V2              any
	QueryOptions    []opaq.QueryOption
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
		V1              any
		V2              any
		QueryOptions    []opaq.QueryOption
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// Sources calls SourcesFunc.
func (mock *PolicyClientMock) Sources() map[string]string {
	callInfo := struct {
	}{}
	mock.lockSources.Lock()
	mock.calls.Sources = append(mock.calls.Sources, callInfo)
	mock.lockSources.Unlock()
	if mock.SourcesFunc == nil {
		var (
			stringToStringOut map[string]string
		)
		return stringToStringOut
	}
	return mock.SourcesFunc()
}

// SourcesCalls gets all the calls that were made to Sources.
// Check the length with:
//
//	len(mockedPolicyClient.SourcesCalls())
func (mock *PolicyClientMock) SourcesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSources.RLock()
	calls = mock.calls.Sources
	mock.lockSources.RUnlock()
	return calls
}

// EmbeddingClientMock is a mock implementation of interfaces.EmbeddingClient.
//
//	func TestSomethingThatUsesEmbeddingClient(t *testing.T) {
//
//		// make and configure a mocked interfaces.EmbeddingClient
//		mockedEmbeddingClient := &EmbeddingClientMock{
//			EmbeddingsFunc: func(ctx context.Context, texts []string, dimensionality int) ([][]float32, error) {
//				panic("mock out the Embeddings method")
//			},
//		}
//
//		// use mockedEmbeddingClient in code that requires interfaces.EmbeddingClient
//		// and then make assertions.
//
//	}
type EmbeddingClientMock struct {
	// EmbeddingsFunc mocks the Embeddings method.
	EmbeddingsFunc func(ctx context.Context, texts []string, dimensionality int) ([][]float32, error)

	// calls tracks calls to the methods.
	calls struct {
		// Embeddings holds details about calls to the Embeddings method.
		Embeddings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Texts is the texts argument value.
			Texts []string
			// Dimensionality is the dimensionality argument value.
			Dimensionality int
		}
	}
	lockEmbeddings sync.RWMutex
}

// Embeddings calls EmbeddingsFunc.
func (mock *EmbeddingClientMock) Embeddings(ctx context.Context, texts []string, dimensionality int) ([][]float32, error) {
	callInfo := struct {
		Ctx            context.Context
		Texts          []string
		Dimensionality int
	}{
		Ctx:            ctx,
		Texts:          texts,
		Dimensionality: dimensionality,
	}
	mock.lockEmbeddings.Lock()
	mock.calls.Embeddings = append(mock.calls.Embeddings, callInfo)
	mock.lockEmbeddings.Unlock()
	if mock.EmbeddingsFunc == nil {
		var (
			float32ssOut [][]float32
			errOut       error
		)
		return float32ssOut, errOut
	}
	return mock.EmbeddingsFunc(ctx, texts, dimensionality)
}

// EmbeddingsCalls gets all the calls that were made to Embeddings.
// Check the length with:
//
//	len(mockedEmbeddingClient.EmbeddingsCalls())
func (mock *EmbeddingClientMock) EmbeddingsCalls() []struct {
	Ctx            context.Context
	Texts          []string
	Dimensionality int
} {
	var calls []struct {
		Ctx            context.Context
		Texts          []string
		Dimensionality int
	}
	mock.lockEmbeddings.RLock()
	calls = mock.calls.Embeddings
	mock.lockEmbeddings.RUnlock()
	return calls
}

// StorageClientMock is a mock implementation of interfaces.StorageClient.
//
//	func TestSomethingThatUsesStorageClient(t *testing.T) {
//
//		// make and configure a mocked interfaces.StorageClient
//		mockedStorageClient := &StorageClientMock{
//			CloseFunc: func(ctx context.Context)  {
//				panic("mock out the Close method")
//			},
//			GetObjectFunc: func(ctx context.Context, object string) (io.ReadCloser, error) {
//				panic("mock out the GetObject method")
//			},
//			PutObjectFunc: func(ctx context.Context, object string) io.WriteCloser {
//				panic("mock out the PutObject method")
//			},
//		}
//
//		// use mockedStorageClient in code that requires interfaces.StorageClient
//		// and then make assertions.
//
//	}
type StorageClientMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context)

	// GetObjectFunc mocks the GetObject method.
	GetObjectFunc func(ctx context.Context, object string) (io.ReadCloser, error)

	// PutObjectFunc mocks the PutObject method.
	PutObjectFunc func(ctx context.Context, object string) io.WriteCloser

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetObject holds details about calls to the GetObject method.
		GetObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Object is the object argument value.
			Object string
		}
		// PutObject holds details about calls to the PutObject method.
		PutObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Object is the object argument value.
			Object string
		}
	}
	lockClose     sync.RWMutex
	lockGetObject sync.RWMutex
	lockPutObject sync.RWMutex
}

// Close calls CloseFunc.
func (mock *StorageClientMock) Close(ctx context.Context) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	if mock.CloseFunc == nil {
		return
	}
	mock.CloseFunc(ctx)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedStorageClient.CloseCalls())
func (mock *StorageClientMock) CloseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// GetObject calls GetObjectFunc.
func (mock *StorageClientMock) GetObject(ctx context.Context, object string) (io.ReadCloser, error) {
	callInfo := struct {
		Ctx    context.Context
		Object string
	}{
		Ctx:    ctx,
		Object: object,
	}
	mock.lockGetObject.Lock()
	mock.calls.GetObject = append(mock.calls.GetObject, callInfo)
	mock.lockGetObject.Unlock()
	if mock.GetObjectFunc == nil {
		var (
			readCloserOut io.ReadCloser
			errOut        error
		)
		return readCloserOut, errOut
	}
	return mock.GetObjectFunc(ctx, object)
}

// GetObjectCalls gets all the calls that were made to GetObject.
// Check the length with:
//
//	len(mockedStorageClient.GetObjectCalls())
func (mock *StorageClientMock) GetObjectCalls() []struct {
	Ctx    context.Context
	Object string
} {
	var calls []struct {
		Ctx    context.Context
		Object string
	}
	mock.lockGetObject.RLock()
	calls = mock.calls.GetObject
	mock.lockGetObject.RUnlock()
	return calls
}

// PutObject calls PutObjectFunc.
func (mock *StorageClientMock) PutObject(ctx context.Context, object string) io.WriteCloser {
	callInfo := struct {
		Ctx    context.Context
		Object string
	}{
		Ctx:    ctx,
		Object: object,
	}
	mock.lockPutObject.Lock()
	mock.calls.PutObject = append(mock.calls.PutObject, callInfo)
	mock.lockPutObject.Unlock()
	if mock.PutObjectFunc == nil {
		var (
			writeCloserOut io.WriteCloser
		)
		return writeCloserOut
	}
	return mock.PutObjectFunc(ctx, object)
}

// PutObjectCalls gets all the calls that were made to PutObject.
// Check the length with:
//
//	len(mockedStorageClient.PutObjectCalls())
func (mock *StorageClientMock) PutObjectCalls() []struct {
	Ctx    context.Context
	Object string
} {
	var calls []struct {
		Ctx    context.Context
		Object string
	}
	mock.lockPutObject.RLock()
	calls = mock.calls.PutObject
	mock.lockPutObject.RUnlock()
	return calls
}

// LLMClientMock is a mock implementation of interfaces.LLMClient.
//
//	func TestSomethingThatUsesLLMClient(t *testing.T) {
//
//		// make and configure a mocked interfaces.LLMClient
//		mockedLLMClient := &LLMClientMock{
//			GenerateEmbeddingFunc: func(ctx context.Context, dimension int, input []string) ([][]float64, error) {
//				panic("mock out the GenerateEmbedding method")
//			},
//			NewSessionFunc: func(ctx context.Context, options ...gollem.SessionOption) (gollem.Session, error) {
//				panic("mock out the NewSession method")
//			},
//		}
//
//		// use mockedLLMClient in code that requires interfaces.LLMClient
//		// and then make assertions.
//
//	}
type LLMClientMock struct {
	// GenerateEmbeddingFunc mocks the GenerateEmbedding method.
	GenerateEmbeddingFunc func(ctx context.Context, dimension int, input []string) ([][]float64, error)

	// NewSessionFunc mocks the NewSession method.
	NewSessionFunc func(ctx context.Context, options ...gollem.SessionOption) (gollem.Session, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateEmbedding holds details about calls to the GenerateEmbedding method.
		GenerateEmbedding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dimension is the dimension argument value.
			Dimension int
			// Input is the input argument value.
			Input []string
		}
		// NewSession holds details about calls to the NewSession method.
		NewSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Options is the options argument value.
			Options []gollem.SessionOption
		}
	}
	lockGenerateEmbedding sync.RWMutex
	lockNewSession        sync.RWMutex
}

// GenerateEmbedding calls GenerateEmbeddingFunc.
func (mock *LLMClientMock) GenerateEmbedding(ctx context.Context, dimension int, input []string) ([][]float64, error) {
	callInfo := struct {
		Ctx       context.Context
		Dimension int
		Input     []string
	}{
		Ctx:       ctx,
		Dimension: dimension,
		Input:     input,
	}
	mock.lockGenerateEmbedding.Lock()
	mock.calls.GenerateEmbedding = append(mock.calls.GenerateEmbedding, callInfo)
	mock.lockGenerateEmbedding.Unlock()
	if mock.GenerateEmbeddingFunc == nil {
		var (
			float64ssOut [][]float64
			errOut       error
		)
		return float64ssOut, errOut
	}
	return mock.GenerateEmbeddingFunc(ctx, dimension, input)
}

// GenerateEmbeddingCalls gets all the calls that were made to GenerateEmbedding.
// Check the length with:
//
//	len(mockedLLMClient.GenerateEmbeddingCalls())
func (mock *LLMClientMock) GenerateEmbeddingCalls() []struct {
	Ctx       context.Context
	Dimension int
	Input     []string
} {
	var calls []struct {
		Ctx       context.Context
		Dimension int
		Input     []string
	}
	mock.lockGenerateEmbedding.RLock()
	calls = mock.calls.GenerateEmbedding
	mock.lockGenerateEmbedding.RUnlock()
	return calls
}

// NewSession calls NewSessionFunc.
func (mock *LLMClientMock) NewSession(ctx context.Context, options ...gollem.SessionOption) (gollem.Session, error) {
	callInfo := struct {
		Ctx     context.Context
		Options []gollem.SessionOption
	}{
		Ctx:     ctx,
		Options: options,
	}
	mock.lockNewSession.Lock()
	mock.calls.NewSession = append(mock.calls.NewSession, callInfo)
	mock.lockNewSession.Unlock()
	if mock.NewSessionFunc == nil {
		var (
			sessionOut gollem.Session
			errOut     error
		)
		return sessionOut, errOut
	}
	return mock.NewSessionFunc(ctx, options...)
}

// NewSessionCalls gets all the calls that were made to NewSession.
// Check the length with:
//
//	len(mockedLLMClient.NewSessionCalls())
func (mock *LLMClientMock) NewSessionCalls() []struct {
	Ctx     context.Context
	Options []gollem.SessionOption
} {
	var calls []struct {
		Ctx     context.Context
		Options []gollem.SessionOption
	}
	mock.lockNewSession.RLock()
	calls = mock.calls.NewSession
	mock.lockNewSession.RUnlock()
	return calls
}

// LLMSessionMock is a mock implementation of interfaces.LLMSession.
//
//	func TestSomethingThatUsesLLMSession(t *testing.T) {
//
//		// make and configure a mocked interfaces.LLMSession
//		mockedLLMSession := &LLMSessionMock{
//			GenerateContentFunc: func(ctx context.Context, input ...gollem.Input) (*gollem.Response, error) {
//				panic("mock out the GenerateContent method")
//			},
//			GenerateStreamFunc: func(ctx context.Context, input ...gollem.Input) (<-chan *gollem.Response, error) {
//				panic("mock out the GenerateStream method")
//			},
//			HistoryFunc: func() *gollem.History {
//				panic("mock out the History method")
//			},
//		}
//
//		// use mockedLLMSession in code that requires interfaces.LLMSession
//		// and then make assertions.
//
//	}
type LLMSessionMock struct {
	// GenerateContentFunc mocks the GenerateContent method.
	GenerateContentFunc func(ctx context.Context, input ...gollem.Input) (*gollem.Response, error)

	// GenerateStreamFunc mocks the GenerateStream method.
	GenerateStreamFunc func(ctx context.Context, input ...gollem.Input) (<-chan *gollem.Response, error)

	// HistoryFunc mocks the History method.
	HistoryFunc func() *gollem.History

	// calls tracks calls to the methods.
	calls struct {
		// GenerateContent holds details about calls to the GenerateContent method.
		GenerateContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input []gollem.Input
		}
		// GenerateStream holds details about calls to the GenerateStream method.
		GenerateStream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input []gollem.Input
		}
		// History holds details about calls to the History method.
		History []struct {
		}
	}
	lockGenerateContent sync.RWMutex
	lockGenerateStream  sync.RWMutex
	lockHistory         sync.RWMutex
}

// GenerateContent calls GenerateContentFunc.
func (mock *LLMSessionMock) GenerateContent(ctx context.Context, input ...gollem.Input) (*gollem.Response, error) {
	callInfo := struct {
		Ctx   context.Context
		Input []gollem.Input
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockGenerateContent.Lock()
	mock.calls.GenerateContent = append(mock.calls.GenerateContent, callInfo)
	mock.lockGenerateContent.Unlock()
	if mock.GenerateContentFunc == nil {
		var (
			responseOut *gollem.Response
			errOut      error
		)
		return responseOut, errOut
	}
	return mock.GenerateContentFunc(ctx, input...)
}

// GenerateContentCalls gets all the calls that were made to GenerateContent.
// Check the length with:
//
//	len(mockedLLMSession.GenerateContentCalls())
func (mock *LLMSessionMock) GenerateContentCalls() []struct {
	Ctx   context.Context
	Input []gollem.Input
} {
	var calls []struct {
		Ctx   context.Context
		Input []gollem.Input
	}
	mock.lockGenerateContent.RLock()
	calls = mock.calls.GenerateContent
	mock.lockGenerateContent.RUnlock()
	return calls
}

// GenerateStream calls GenerateStreamFunc.
func (mock *LLMSessionMock) GenerateStream(ctx context.Context, input ...gollem.Input) (<-chan *gollem.Response, error) {
	callInfo := struct {
		Ctx   context.Context
		Input []gollem.Input
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockGenerateStream.Lock()
	mock.calls.GenerateStream = append(mock.calls.GenerateStream, callInfo)
	mock.lockGenerateStream.Unlock()
	if mock.GenerateStreamFunc == nil {
		var (
			responseChOut <-chan *gollem.Response
			errOut        error
		)
		return responseChOut, errOut
	}
	return mock.GenerateStreamFunc(ctx, input...)
}

// GenerateStreamCalls gets all the calls that were made to GenerateStream.
// Check the length with:
//
//	len(mockedLLMSession.GenerateStreamCalls())
func (mock *LLMSessionMock) GenerateStreamCalls() []struct {
	Ctx   context.Context
	Input []gollem.Input
} {
	var calls []struct {
		Ctx   context.Context
		Input []gollem.Input
	}
	mock.lockGenerateStream.RLock()
	calls = mock.calls.GenerateStream
	mock.lockGenerateStream.RUnlock()
	return calls
}

// History calls HistoryFunc.
func (mock *LLMSessionMock) History() *gollem.History {
	callInfo := struct {
	}{}
	mock.lockHistory.Lock()
	mock.calls.History = append(mock.calls.History, callInfo)
	mock.lockHistory.Unlock()
	if mock.HistoryFunc == nil {
		var (
			historyOut *gollem.History
		)
		return historyOut
	}
	return mock.HistoryFunc()
}

// HistoryCalls gets all the calls that were made to History.
// Check the length with:
//
//	len(mockedLLMSession.HistoryCalls())
func (mock *LLMSessionMock) HistoryCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHistory.RLock()
	calls = mock.calls.History
	mock.lockHistory.RUnlock()
	return calls
}
