package bigquery

import (
	"context"
	"time"

	"github.com/m-mizutani/goerr/v2"
	"github.com/m-mizutani/gollem"
	"github.com/secmon-lab/warren/pkg/domain/model/memory"
	"github.com/secmon-lab/warren/pkg/domain/types"
	"github.com/secmon-lab/warren/pkg/utils/logging"
)

// saveExecutionMemory saves task execution metadata as agent memory
// Note: Does NOT store the actual execution result (resp.String()), only metadata
func (a *Agent) saveExecutionMemory(
	ctx context.Context,
	query string,
	resp *gollem.ExecuteResponse,
	execErr error,
	duration time.Duration,
	session gollem.Session,
) error {
	// Generate KPT analysis using LLM (all components in one call)
	successes, problems, improvements, err := a.generateKPTAnalysis(ctx, query, resp, execErr, duration, session)
	if err != nil {
		// Log warning but continue with empty arrays (non-critical failure)
		logging.From(ctx).Warn("Failed to generate KPT analysis, saving memory with empty KPT", "error", err)
	}

	// Build AgentMemory (QueryEmbedding will be generated by Memory Service)
	mem := &memory.AgentMemory{
		ID:           types.NewAgentMemoryID(),
		AgentID:      a.ID(),
		TaskQuery:    query,
		Timestamp:    time.Now(),
		Duration:     duration,
		Successes:    successes,
		Problems:     problems,
		Improvements: improvements,
	}

	// Save memory (with embedding generation)
	if err := a.memoryService.SaveAgentMemory(ctx, mem); err != nil {
		return goerr.Wrap(err, "failed to save memory")
	}

	return nil
}
