// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package interfaces

import (
	"cloud.google.com/go/vertexai/genai"
	"context"
	"github.com/m-mizutani/opaq"
	"github.com/secmon-lab/warren/pkg/domain/model/action"
	"github.com/secmon-lab/warren/pkg/domain/model/alert"
	"github.com/secmon-lab/warren/pkg/domain/model/policy"
	"github.com/secmon-lab/warren/pkg/domain/model/session"
	modelslack "github.com/secmon-lab/warren/pkg/domain/model/slack"
	"github.com/secmon-lab/warren/pkg/domain/types"
	slackslack "github.com/slack-go/slack"
	"github.com/urfave/cli/v3"
	"log/slog"
	"sync"
	"time"
)

// ActionMock is a mock implementation of Action.
//
//	func TestSomethingThatUsesAction(t *testing.T) {
//
//		// make and configure a mocked Action
//		mockedAction := &ActionMock{
//			ConfigureFunc: func(ctx context.Context) error {
//				panic("mock out the Configure method")
//			},
//			ExecuteFunc: func(ctx context.Context, name string, args map[string]any) (*action.Result, error) {
//				panic("mock out the Execute method")
//			},
//			FlagsFunc: func() []cli.Flag {
//				panic("mock out the Flags method")
//			},
//			LogValueFunc: func() slog.Value {
//				panic("mock out the LogValue method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			ToolsFunc: func() []*genai.FunctionDeclaration {
//				panic("mock out the Tools method")
//			},
//		}
//
//		// use mockedAction in code that requires Action
//		// and then make assertions.
//
//	}
type ActionMock struct {
	// ConfigureFunc mocks the Configure method.
	ConfigureFunc func(ctx context.Context) error

	// ExecuteFunc mocks the Execute method.
	ExecuteFunc func(ctx context.Context, name string, args map[string]any) (*action.Result, error)

	// FlagsFunc mocks the Flags method.
	FlagsFunc func() []cli.Flag

	// LogValueFunc mocks the LogValue method.
	LogValueFunc func() slog.Value

	// NameFunc mocks the Name method.
	NameFunc func() string

	// ToolsFunc mocks the Tools method.
	ToolsFunc func() []*genai.FunctionDeclaration

	// calls tracks calls to the methods.
	calls struct {
		// Configure holds details about calls to the Configure method.
		Configure []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Execute holds details about calls to the Execute method.
		Execute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args map[string]any
		}
		// Flags holds details about calls to the Flags method.
		Flags []struct {
		}
		// LogValue holds details about calls to the LogValue method.
		LogValue []struct {
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// Tools holds details about calls to the Tools method.
		Tools []struct {
		}
	}
	lockConfigure sync.RWMutex
	lockExecute   sync.RWMutex
	lockFlags     sync.RWMutex
	lockLogValue  sync.RWMutex
	lockName      sync.RWMutex
	lockTools     sync.RWMutex
}

// Configure calls ConfigureFunc.
func (mock *ActionMock) Configure(ctx context.Context) error {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockConfigure.Lock()
	mock.calls.Configure = append(mock.calls.Configure, callInfo)
	mock.lockConfigure.Unlock()
	if mock.ConfigureFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ConfigureFunc(ctx)
}

// ConfigureCalls gets all the calls that were made to Configure.
// Check the length with:
//
//	len(mockedAction.ConfigureCalls())
func (mock *ActionMock) ConfigureCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockConfigure.RLock()
	calls = mock.calls.Configure
	mock.lockConfigure.RUnlock()
	return calls
}

// Execute calls ExecuteFunc.
func (mock *ActionMock) Execute(ctx context.Context, name string, args map[string]any) (*action.Result, error) {
	callInfo := struct {
		Ctx  context.Context
		Name string
		Args map[string]any
	}{
		Ctx:  ctx,
		Name: name,
		Args: args,
	}
	mock.lockExecute.Lock()
	mock.calls.Execute = append(mock.calls.Execute, callInfo)
	mock.lockExecute.Unlock()
	if mock.ExecuteFunc == nil {
		var (
			resultOut *action.Result
			errOut    error
		)
		return resultOut, errOut
	}
	return mock.ExecuteFunc(ctx, name, args)
}

// ExecuteCalls gets all the calls that were made to Execute.
// Check the length with:
//
//	len(mockedAction.ExecuteCalls())
func (mock *ActionMock) ExecuteCalls() []struct {
	Ctx  context.Context
	Name string
	Args map[string]any
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Args map[string]any
	}
	mock.lockExecute.RLock()
	calls = mock.calls.Execute
	mock.lockExecute.RUnlock()
	return calls
}

// Flags calls FlagsFunc.
func (mock *ActionMock) Flags() []cli.Flag {
	callInfo := struct {
	}{}
	mock.lockFlags.Lock()
	mock.calls.Flags = append(mock.calls.Flags, callInfo)
	mock.lockFlags.Unlock()
	if mock.FlagsFunc == nil {
		var (
			flagsOut []cli.Flag
		)
		return flagsOut
	}
	return mock.FlagsFunc()
}

// FlagsCalls gets all the calls that were made to Flags.
// Check the length with:
//
//	len(mockedAction.FlagsCalls())
func (mock *ActionMock) FlagsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFlags.RLock()
	calls = mock.calls.Flags
	mock.lockFlags.RUnlock()
	return calls
}

// LogValue calls LogValueFunc.
func (mock *ActionMock) LogValue() slog.Value {
	callInfo := struct {
	}{}
	mock.lockLogValue.Lock()
	mock.calls.LogValue = append(mock.calls.LogValue, callInfo)
	mock.lockLogValue.Unlock()
	if mock.LogValueFunc == nil {
		var (
			valueOut slog.Value
		)
		return valueOut
	}
	return mock.LogValueFunc()
}

// LogValueCalls gets all the calls that were made to LogValue.
// Check the length with:
//
//	len(mockedAction.LogValueCalls())
func (mock *ActionMock) LogValueCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogValue.RLock()
	calls = mock.calls.LogValue
	mock.lockLogValue.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *ActionMock) Name() string {
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	if mock.NameFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedAction.NameCalls())
func (mock *ActionMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Tools calls ToolsFunc.
func (mock *ActionMock) Tools() []*genai.FunctionDeclaration {
	callInfo := struct {
	}{}
	mock.lockTools.Lock()
	mock.calls.Tools = append(mock.calls.Tools, callInfo)
	mock.lockTools.Unlock()
	if mock.ToolsFunc == nil {
		var (
			functionDeclarationsOut []*genai.FunctionDeclaration
		)
		return functionDeclarationsOut
	}
	return mock.ToolsFunc()
}

// ToolsCalls gets all the calls that were made to Tools.
// Check the length with:
//
//	len(mockedAction.ToolsCalls())
func (mock *ActionMock) ToolsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTools.RLock()
	calls = mock.calls.Tools
	mock.lockTools.RUnlock()
	return calls
}

// SlackClientMock is a mock implementation of SlackClient.
//
//	func TestSomethingThatUsesSlackClient(t *testing.T) {
//
//		// make and configure a mocked SlackClient
//		mockedSlackClient := &SlackClientMock{
//			AuthTestFunc: func() (*slackslack.AuthTestResponse, error) {
//				panic("mock out the AuthTest method")
//			},
//			OpenViewFunc: func(triggerID string, view slackslack.ModalViewRequest) (*slackslack.ViewResponse, error) {
//				panic("mock out the OpenView method")
//			},
//			PostMessageContextFunc: func(ctx context.Context, channelID string, options ...slackslack.MsgOption) (string, string, error) {
//				panic("mock out the PostMessageContext method")
//			},
//			UpdateMessageContextFunc: func(ctx context.Context, channelID string, timestamp string, options ...slackslack.MsgOption) (string, string, string, error) {
//				panic("mock out the UpdateMessageContext method")
//			},
//			UploadFileV2ContextFunc: func(ctx context.Context, params slackslack.UploadFileV2Parameters) (*slackslack.FileSummary, error) {
//				panic("mock out the UploadFileV2Context method")
//			},
//		}
//
//		// use mockedSlackClient in code that requires SlackClient
//		// and then make assertions.
//
//	}
type SlackClientMock struct {
	// AuthTestFunc mocks the AuthTest method.
	AuthTestFunc func() (*slackslack.AuthTestResponse, error)

	// OpenViewFunc mocks the OpenView method.
	OpenViewFunc func(triggerID string, view slackslack.ModalViewRequest) (*slackslack.ViewResponse, error)

	// PostMessageContextFunc mocks the PostMessageContext method.
	PostMessageContextFunc func(ctx context.Context, channelID string, options ...slackslack.MsgOption) (string, string, error)

	// UpdateMessageContextFunc mocks the UpdateMessageContext method.
	UpdateMessageContextFunc func(ctx context.Context, channelID string, timestamp string, options ...slackslack.MsgOption) (string, string, string, error)

	// UploadFileV2ContextFunc mocks the UploadFileV2Context method.
	UploadFileV2ContextFunc func(ctx context.Context, params slackslack.UploadFileV2Parameters) (*slackslack.FileSummary, error)

	// calls tracks calls to the methods.
	calls struct {
		// AuthTest holds details about calls to the AuthTest method.
		AuthTest []struct {
		}
		// OpenView holds details about calls to the OpenView method.
		OpenView []struct {
			// TriggerID is the triggerID argument value.
			TriggerID string
			// View is the view argument value.
			View slackslack.ModalViewRequest
		}
		// PostMessageContext holds details about calls to the PostMessageContext method.
		PostMessageContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID string
			// Options is the options argument value.
			Options []slackslack.MsgOption
		}
		// UpdateMessageContext holds details about calls to the UpdateMessageContext method.
		UpdateMessageContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID string
			// Timestamp is the timestamp argument value.
			Timestamp string
			// Options is the options argument value.
			Options []slackslack.MsgOption
		}
		// UploadFileV2Context holds details about calls to the UploadFileV2Context method.
		UploadFileV2Context []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params slackslack.UploadFileV2Parameters
		}
	}
	lockAuthTest             sync.RWMutex
	lockOpenView             sync.RWMutex
	lockPostMessageContext   sync.RWMutex
	lockUpdateMessageContext sync.RWMutex
	lockUploadFileV2Context  sync.RWMutex
}

// AuthTest calls AuthTestFunc.
func (mock *SlackClientMock) AuthTest() (*slackslack.AuthTestResponse, error) {
	callInfo := struct {
	}{}
	mock.lockAuthTest.Lock()
	mock.calls.AuthTest = append(mock.calls.AuthTest, callInfo)
	mock.lockAuthTest.Unlock()
	if mock.AuthTestFunc == nil {
		var (
			authTestResponseOut *slackslack.AuthTestResponse
			errOut              error
		)
		return authTestResponseOut, errOut
	}
	return mock.AuthTestFunc()
}

// AuthTestCalls gets all the calls that were made to AuthTest.
// Check the length with:
//
//	len(mockedSlackClient.AuthTestCalls())
func (mock *SlackClientMock) AuthTestCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAuthTest.RLock()
	calls = mock.calls.AuthTest
	mock.lockAuthTest.RUnlock()
	return calls
}

// OpenView calls OpenViewFunc.
func (mock *SlackClientMock) OpenView(triggerID string, view slackslack.ModalViewRequest) (*slackslack.ViewResponse, error) {
	callInfo := struct {
		TriggerID string
		View      slackslack.ModalViewRequest
	}{
		TriggerID: triggerID,
		View:      view,
	}
	mock.lockOpenView.Lock()
	mock.calls.OpenView = append(mock.calls.OpenView, callInfo)
	mock.lockOpenView.Unlock()
	if mock.OpenViewFunc == nil {
		var (
			viewResponseOut *slackslack.ViewResponse
			errOut          error
		)
		return viewResponseOut, errOut
	}
	return mock.OpenViewFunc(triggerID, view)
}

// OpenViewCalls gets all the calls that were made to OpenView.
// Check the length with:
//
//	len(mockedSlackClient.OpenViewCalls())
func (mock *SlackClientMock) OpenViewCalls() []struct {
	TriggerID string
	View      slackslack.ModalViewRequest
} {
	var calls []struct {
		TriggerID string
		View      slackslack.ModalViewRequest
	}
	mock.lockOpenView.RLock()
	calls = mock.calls.OpenView
	mock.lockOpenView.RUnlock()
	return calls
}

// PostMessageContext calls PostMessageContextFunc.
func (mock *SlackClientMock) PostMessageContext(ctx context.Context, channelID string, options ...slackslack.MsgOption) (string, string, error) {
	callInfo := struct {
		Ctx       context.Context
		ChannelID string
		Options   []slackslack.MsgOption
	}{
		Ctx:       ctx,
		ChannelID: channelID,
		Options:   options,
	}
	mock.lockPostMessageContext.Lock()
	mock.calls.PostMessageContext = append(mock.calls.PostMessageContext, callInfo)
	mock.lockPostMessageContext.Unlock()
	if mock.PostMessageContextFunc == nil {
		var (
			sOut1  string
			sOut2  string
			errOut error
		)
		return sOut1, sOut2, errOut
	}
	return mock.PostMessageContextFunc(ctx, channelID, options...)
}

// PostMessageContextCalls gets all the calls that were made to PostMessageContext.
// Check the length with:
//
//	len(mockedSlackClient.PostMessageContextCalls())
func (mock *SlackClientMock) PostMessageContextCalls() []struct {
	Ctx       context.Context
	ChannelID string
	Options   []slackslack.MsgOption
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID string
		Options   []slackslack.MsgOption
	}
	mock.lockPostMessageContext.RLock()
	calls = mock.calls.PostMessageContext
	mock.lockPostMessageContext.RUnlock()
	return calls
}

// UpdateMessageContext calls UpdateMessageContextFunc.
func (mock *SlackClientMock) UpdateMessageContext(ctx context.Context, channelID string, timestamp string, options ...slackslack.MsgOption) (string, string, string, error) {
	callInfo := struct {
		Ctx       context.Context
		ChannelID string
		Timestamp string
		Options   []slackslack.MsgOption
	}{
		Ctx:       ctx,
		ChannelID: channelID,
		Timestamp: timestamp,
		Options:   options,
	}
	mock.lockUpdateMessageContext.Lock()
	mock.calls.UpdateMessageContext = append(mock.calls.UpdateMessageContext, callInfo)
	mock.lockUpdateMessageContext.Unlock()
	if mock.UpdateMessageContextFunc == nil {
		var (
			sOut1  string
			sOut2  string
			sOut3  string
			errOut error
		)
		return sOut1, sOut2, sOut3, errOut
	}
	return mock.UpdateMessageContextFunc(ctx, channelID, timestamp, options...)
}

// UpdateMessageContextCalls gets all the calls that were made to UpdateMessageContext.
// Check the length with:
//
//	len(mockedSlackClient.UpdateMessageContextCalls())
func (mock *SlackClientMock) UpdateMessageContextCalls() []struct {
	Ctx       context.Context
	ChannelID string
	Timestamp string
	Options   []slackslack.MsgOption
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID string
		Timestamp string
		Options   []slackslack.MsgOption
	}
	mock.lockUpdateMessageContext.RLock()
	calls = mock.calls.UpdateMessageContext
	mock.lockUpdateMessageContext.RUnlock()
	return calls
}

// UploadFileV2Context calls UploadFileV2ContextFunc.
func (mock *SlackClientMock) UploadFileV2Context(ctx context.Context, params slackslack.UploadFileV2Parameters) (*slackslack.FileSummary, error) {
	callInfo := struct {
		Ctx    context.Context
		Params slackslack.UploadFileV2Parameters
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockUploadFileV2Context.Lock()
	mock.calls.UploadFileV2Context = append(mock.calls.UploadFileV2Context, callInfo)
	mock.lockUploadFileV2Context.Unlock()
	if mock.UploadFileV2ContextFunc == nil {
		var (
			fileSummaryOut *slackslack.FileSummary
			errOut         error
		)
		return fileSummaryOut, errOut
	}
	return mock.UploadFileV2ContextFunc(ctx, params)
}

// UploadFileV2ContextCalls gets all the calls that were made to UploadFileV2Context.
// Check the length with:
//
//	len(mockedSlackClient.UploadFileV2ContextCalls())
func (mock *SlackClientMock) UploadFileV2ContextCalls() []struct {
	Ctx    context.Context
	Params slackslack.UploadFileV2Parameters
} {
	var calls []struct {
		Ctx    context.Context
		Params slackslack.UploadFileV2Parameters
	}
	mock.lockUploadFileV2Context.RLock()
	calls = mock.calls.UploadFileV2Context
	mock.lockUploadFileV2Context.RUnlock()
	return calls
}

// SlackThreadServiceMock is a mock implementation of SlackThreadService.
//
//	func TestSomethingThatUsesSlackThreadService(t *testing.T) {
//
//		// make and configure a mocked SlackThreadService
//		mockedSlackThreadService := &SlackThreadServiceMock{
//			NewStateFuncFunc: func(ctx context.Context, message string) func(ctx context.Context, msg string) {
//				panic("mock out the NewStateFunc method")
//			},
//			ReplyFunc: func(ctx context.Context, message string)  {
//				panic("mock out the Reply method")
//			},
//		}
//
//		// use mockedSlackThreadService in code that requires SlackThreadService
//		// and then make assertions.
//
//	}
type SlackThreadServiceMock struct {
	// NewStateFuncFunc mocks the NewStateFunc method.
	NewStateFuncFunc func(ctx context.Context, message string) func(ctx context.Context, msg string)

	// ReplyFunc mocks the Reply method.
	ReplyFunc func(ctx context.Context, message string)

	// calls tracks calls to the methods.
	calls struct {
		// NewStateFunc holds details about calls to the NewStateFunc method.
		NewStateFunc []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message string
		}
		// Reply holds details about calls to the Reply method.
		Reply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message string
		}
	}
	lockNewStateFunc sync.RWMutex
	lockReply        sync.RWMutex
}

// NewStateFunc calls NewStateFuncFunc.
func (mock *SlackThreadServiceMock) NewStateFunc(ctx context.Context, message string) func(ctx context.Context, msg string) {
	callInfo := struct {
		Ctx     context.Context
		Message string
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockNewStateFunc.Lock()
	mock.calls.NewStateFunc = append(mock.calls.NewStateFunc, callInfo)
	mock.lockNewStateFunc.Unlock()
	if mock.NewStateFuncFunc == nil {
		var (
			fnOut func(ctx context.Context, msg string)
		)
		return fnOut
	}
	return mock.NewStateFuncFunc(ctx, message)
}

// NewStateFuncCalls gets all the calls that were made to NewStateFunc.
// Check the length with:
//
//	len(mockedSlackThreadService.NewStateFuncCalls())
func (mock *SlackThreadServiceMock) NewStateFuncCalls() []struct {
	Ctx     context.Context
	Message string
} {
	var calls []struct {
		Ctx     context.Context
		Message string
	}
	mock.lockNewStateFunc.RLock()
	calls = mock.calls.NewStateFunc
	mock.lockNewStateFunc.RUnlock()
	return calls
}

// Reply calls ReplyFunc.
func (mock *SlackThreadServiceMock) Reply(ctx context.Context, message string) {
	callInfo := struct {
		Ctx     context.Context
		Message string
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockReply.Lock()
	mock.calls.Reply = append(mock.calls.Reply, callInfo)
	mock.lockReply.Unlock()
	if mock.ReplyFunc == nil {
		return
	}
	mock.ReplyFunc(ctx, message)
}

// ReplyCalls gets all the calls that were made to Reply.
// Check the length with:
//
//	len(mockedSlackThreadService.ReplyCalls())
func (mock *SlackThreadServiceMock) ReplyCalls() []struct {
	Ctx     context.Context
	Message string
} {
	var calls []struct {
		Ctx     context.Context
		Message string
	}
	mock.lockReply.RLock()
	calls = mock.calls.Reply
	mock.lockReply.RUnlock()
	return calls
}

// LLMSessionMock is a mock implementation of LLMSession.
//
//	func TestSomethingThatUsesLLMSession(t *testing.T) {
//
//		// make and configure a mocked LLMSession
//		mockedLLMSession := &LLMSessionMock{
//			GetHistoryFunc: func() []*genai.Content {
//				panic("mock out the GetHistory method")
//			},
//			SendMessageFunc: func(ctx context.Context, msg ...genai.Part) (*genai.GenerateContentResponse, error) {
//				panic("mock out the SendMessage method")
//			},
//		}
//
//		// use mockedLLMSession in code that requires LLMSession
//		// and then make assertions.
//
//	}
type LLMSessionMock struct {
	// GetHistoryFunc mocks the GetHistory method.
	GetHistoryFunc func() []*genai.Content

	// SendMessageFunc mocks the SendMessage method.
	SendMessageFunc func(ctx context.Context, msg ...genai.Part) (*genai.GenerateContentResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetHistory holds details about calls to the GetHistory method.
		GetHistory []struct {
		}
		// SendMessage holds details about calls to the SendMessage method.
		SendMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg []genai.Part
		}
	}
	lockGetHistory  sync.RWMutex
	lockSendMessage sync.RWMutex
}

// GetHistory calls GetHistoryFunc.
func (mock *LLMSessionMock) GetHistory() []*genai.Content {
	callInfo := struct {
	}{}
	mock.lockGetHistory.Lock()
	mock.calls.GetHistory = append(mock.calls.GetHistory, callInfo)
	mock.lockGetHistory.Unlock()
	if mock.GetHistoryFunc == nil {
		var (
			contentsOut []*genai.Content
		)
		return contentsOut
	}
	return mock.GetHistoryFunc()
}

// GetHistoryCalls gets all the calls that were made to GetHistory.
// Check the length with:
//
//	len(mockedLLMSession.GetHistoryCalls())
func (mock *LLMSessionMock) GetHistoryCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetHistory.RLock()
	calls = mock.calls.GetHistory
	mock.lockGetHistory.RUnlock()
	return calls
}

// SendMessage calls SendMessageFunc.
func (mock *LLMSessionMock) SendMessage(ctx context.Context, msg ...genai.Part) (*genai.GenerateContentResponse, error) {
	callInfo := struct {
		Ctx context.Context
		Msg []genai.Part
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockSendMessage.Lock()
	mock.calls.SendMessage = append(mock.calls.SendMessage, callInfo)
	mock.lockSendMessage.Unlock()
	if mock.SendMessageFunc == nil {
		var (
			generateContentResponseOut *genai.GenerateContentResponse
			errOut                     error
		)
		return generateContentResponseOut, errOut
	}
	return mock.SendMessageFunc(ctx, msg...)
}

// SendMessageCalls gets all the calls that were made to SendMessage.
// Check the length with:
//
//	len(mockedLLMSession.SendMessageCalls())
func (mock *LLMSessionMock) SendMessageCalls() []struct {
	Ctx context.Context
	Msg []genai.Part
} {
	var calls []struct {
		Ctx context.Context
		Msg []genai.Part
	}
	mock.lockSendMessage.RLock()
	calls = mock.calls.SendMessage
	mock.lockSendMessage.RUnlock()
	return calls
}

// RepositoryMock is a mock implementation of Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked Repository
//		mockedRepository := &RepositoryMock{
//			BatchGetAlertsFunc: func(ctx context.Context, alertIDs []types.AlertID) (alert.Alerts, error) {
//				panic("mock out the BatchGetAlerts method")
//			},
//			BatchUpdateAlertStatusFunc: func(ctx context.Context, alertIDs []types.AlertID, status types.AlertStatus, reason string) error {
//				panic("mock out the BatchUpdateAlertStatus method")
//			},
//			GetAlertFunc: func(ctx context.Context, alertID types.AlertID) (*alert.Alert, error) {
//				panic("mock out the GetAlert method")
//			},
//			GetAlertByThreadFunc: func(ctx context.Context, thread modelslack.Thread) (*alert.Alert, error) {
//				panic("mock out the GetAlertByThread method")
//			},
//			GetAlertCommentsFunc: func(ctx context.Context, alertID types.AlertID) ([]alert.AlertComment, error) {
//				panic("mock out the GetAlertComments method")
//			},
//			GetAlertListFunc: func(ctx context.Context, listID types.AlertListID) (*alert.List, error) {
//				panic("mock out the GetAlertList method")
//			},
//			GetAlertListByThreadFunc: func(ctx context.Context, thread modelslack.Thread) (*alert.List, error) {
//				panic("mock out the GetAlertListByThread method")
//			},
//			GetAlertsBySpanFunc: func(ctx context.Context, begin time.Time, end time.Time) (alert.Alerts, error) {
//				panic("mock out the GetAlertsBySpan method")
//			},
//			GetAlertsByStatusFunc: func(ctx context.Context, status ...types.AlertStatus) (alert.Alerts, error) {
//				panic("mock out the GetAlertsByStatus method")
//			},
//			GetAlertsWithoutStatusFunc: func(ctx context.Context, status types.AlertStatus) (alert.Alerts, error) {
//				panic("mock out the GetAlertsWithoutStatus method")
//			},
//			GetLatestAlertListInThreadFunc: func(ctx context.Context, thread modelslack.Thread) (*alert.List, error) {
//				panic("mock out the GetLatestAlertListInThread method")
//			},
//			GetLatestHistoryFunc: func(ctx context.Context, sessionID types.SessionID) (*session.History, error) {
//				panic("mock out the GetLatestHistory method")
//			},
//			GetNotesFunc: func(ctx context.Context, sessionID types.SessionID) ([]*session.Note, error) {
//				panic("mock out the GetNotes method")
//			},
//			GetPolicyDiffFunc: func(ctx context.Context, id types.PolicyDiffID) (*policy.Diff, error) {
//				panic("mock out the GetPolicyDiff method")
//			},
//			GetSessionFunc: func(ctx context.Context, id types.SessionID) (*session.Session, error) {
//				panic("mock out the GetSession method")
//			},
//			GetSessionByThreadFunc: func(ctx context.Context, thread modelslack.Thread) (*session.Session, error) {
//				panic("mock out the GetSessionByThread method")
//			},
//			PutAlertFunc: func(ctx context.Context, alertMoqParam alert.Alert) error {
//				panic("mock out the PutAlert method")
//			},
//			PutAlertCommentFunc: func(ctx context.Context, comment alert.AlertComment) error {
//				panic("mock out the PutAlertComment method")
//			},
//			PutAlertListFunc: func(ctx context.Context, list alert.List) error {
//				panic("mock out the PutAlertList method")
//			},
//			PutHistoryFunc: func(ctx context.Context, sessionID types.SessionID, history *session.History) error {
//				panic("mock out the PutHistory method")
//			},
//			PutNoteFunc: func(ctx context.Context, note *session.Note) error {
//				panic("mock out the PutNote method")
//			},
//			PutPolicyDiffFunc: func(ctx context.Context, diff *policy.Diff) error {
//				panic("mock out the PutPolicyDiff method")
//			},
//			PutSessionFunc: func(ctx context.Context, sessionMoqParam session.Session) error {
//				panic("mock out the PutSession method")
//			},
//			SearchAlertsFunc: func(ctx context.Context, path string, op string, value any) (alert.Alerts, error) {
//				panic("mock out the SearchAlerts method")
//			},
//		}
//
//		// use mockedRepository in code that requires Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// BatchGetAlertsFunc mocks the BatchGetAlerts method.
	BatchGetAlertsFunc func(ctx context.Context, alertIDs []types.AlertID) (alert.Alerts, error)

	// BatchUpdateAlertStatusFunc mocks the BatchUpdateAlertStatus method.
	BatchUpdateAlertStatusFunc func(ctx context.Context, alertIDs []types.AlertID, status types.AlertStatus, reason string) error

	// GetAlertFunc mocks the GetAlert method.
	GetAlertFunc func(ctx context.Context, alertID types.AlertID) (*alert.Alert, error)

	// GetAlertByThreadFunc mocks the GetAlertByThread method.
	GetAlertByThreadFunc func(ctx context.Context, thread modelslack.Thread) (*alert.Alert, error)

	// GetAlertCommentsFunc mocks the GetAlertComments method.
	GetAlertCommentsFunc func(ctx context.Context, alertID types.AlertID) ([]alert.AlertComment, error)

	// GetAlertListFunc mocks the GetAlertList method.
	GetAlertListFunc func(ctx context.Context, listID types.AlertListID) (*alert.List, error)

	// GetAlertListByThreadFunc mocks the GetAlertListByThread method.
	GetAlertListByThreadFunc func(ctx context.Context, thread modelslack.Thread) (*alert.List, error)

	// GetAlertsBySpanFunc mocks the GetAlertsBySpan method.
	GetAlertsBySpanFunc func(ctx context.Context, begin time.Time, end time.Time) (alert.Alerts, error)

	// GetAlertsByStatusFunc mocks the GetAlertsByStatus method.
	GetAlertsByStatusFunc func(ctx context.Context, status ...types.AlertStatus) (alert.Alerts, error)

	// GetAlertsWithoutStatusFunc mocks the GetAlertsWithoutStatus method.
	GetAlertsWithoutStatusFunc func(ctx context.Context, status types.AlertStatus) (alert.Alerts, error)

	// GetLatestAlertListInThreadFunc mocks the GetLatestAlertListInThread method.
	GetLatestAlertListInThreadFunc func(ctx context.Context, thread modelslack.Thread) (*alert.List, error)

	// GetLatestHistoryFunc mocks the GetLatestHistory method.
	GetLatestHistoryFunc func(ctx context.Context, sessionID types.SessionID) (*session.History, error)

	// GetNotesFunc mocks the GetNotes method.
	GetNotesFunc func(ctx context.Context, sessionID types.SessionID) ([]*session.Note, error)

	// GetPolicyDiffFunc mocks the GetPolicyDiff method.
	GetPolicyDiffFunc func(ctx context.Context, id types.PolicyDiffID) (*policy.Diff, error)

	// GetSessionFunc mocks the GetSession method.
	GetSessionFunc func(ctx context.Context, id types.SessionID) (*session.Session, error)

	// GetSessionByThreadFunc mocks the GetSessionByThread method.
	GetSessionByThreadFunc func(ctx context.Context, thread modelslack.Thread) (*session.Session, error)

	// PutAlertFunc mocks the PutAlert method.
	PutAlertFunc func(ctx context.Context, alertMoqParam alert.Alert) error

	// PutAlertCommentFunc mocks the PutAlertComment method.
	PutAlertCommentFunc func(ctx context.Context, comment alert.AlertComment) error

	// PutAlertListFunc mocks the PutAlertList method.
	PutAlertListFunc func(ctx context.Context, list alert.List) error

	// PutHistoryFunc mocks the PutHistory method.
	PutHistoryFunc func(ctx context.Context, sessionID types.SessionID, history *session.History) error

	// PutNoteFunc mocks the PutNote method.
	PutNoteFunc func(ctx context.Context, note *session.Note) error

	// PutPolicyDiffFunc mocks the PutPolicyDiff method.
	PutPolicyDiffFunc func(ctx context.Context, diff *policy.Diff) error

	// PutSessionFunc mocks the PutSession method.
	PutSessionFunc func(ctx context.Context, sessionMoqParam session.Session) error

	// SearchAlertsFunc mocks the SearchAlerts method.
	SearchAlertsFunc func(ctx context.Context, path string, op string, value any) (alert.Alerts, error)

	// calls tracks calls to the methods.
	calls struct {
		// BatchGetAlerts holds details about calls to the BatchGetAlerts method.
		BatchGetAlerts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertIDs is the alertIDs argument value.
			AlertIDs []types.AlertID
		}
		// BatchUpdateAlertStatus holds details about calls to the BatchUpdateAlertStatus method.
		BatchUpdateAlertStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertIDs is the alertIDs argument value.
			AlertIDs []types.AlertID
			// Status is the status argument value.
			Status types.AlertStatus
			// Reason is the reason argument value.
			Reason string
		}
		// GetAlert holds details about calls to the GetAlert method.
		GetAlert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertID is the alertID argument value.
			AlertID types.AlertID
		}
		// GetAlertByThread holds details about calls to the GetAlertByThread method.
		GetAlertByThread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Thread is the thread argument value.
			Thread modelslack.Thread
		}
		// GetAlertComments holds details about calls to the GetAlertComments method.
		GetAlertComments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertID is the alertID argument value.
			AlertID types.AlertID
		}
		// GetAlertList holds details about calls to the GetAlertList method.
		GetAlertList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ListID is the listID argument value.
			ListID types.AlertListID
		}
		// GetAlertListByThread holds details about calls to the GetAlertListByThread method.
		GetAlertListByThread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Thread is the thread argument value.
			Thread modelslack.Thread
		}
		// GetAlertsBySpan holds details about calls to the GetAlertsBySpan method.
		GetAlertsBySpan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Begin is the begin argument value.
			Begin time.Time
			// End is the end argument value.
			End time.Time
		}
		// GetAlertsByStatus holds details about calls to the GetAlertsByStatus method.
		GetAlertsByStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status []types.AlertStatus
		}
		// GetAlertsWithoutStatus holds details about calls to the GetAlertsWithoutStatus method.
		GetAlertsWithoutStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status types.AlertStatus
		}
		// GetLatestAlertListInThread holds details about calls to the GetLatestAlertListInThread method.
		GetLatestAlertListInThread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Thread is the thread argument value.
			Thread modelslack.Thread
		}
		// GetLatestHistory holds details about calls to the GetLatestHistory method.
		GetLatestHistory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionID is the sessionID argument value.
			SessionID types.SessionID
		}
		// GetNotes holds details about calls to the GetNotes method.
		GetNotes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionID is the sessionID argument value.
			SessionID types.SessionID
		}
		// GetPolicyDiff holds details about calls to the GetPolicyDiff method.
		GetPolicyDiff []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID types.PolicyDiffID
		}
		// GetSession holds details about calls to the GetSession method.
		GetSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID types.SessionID
		}
		// GetSessionByThread holds details about calls to the GetSessionByThread method.
		GetSessionByThread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Thread is the thread argument value.
			Thread modelslack.Thread
		}
		// PutAlert holds details about calls to the PutAlert method.
		PutAlert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AlertMoqParam is the alertMoqParam argument value.
			AlertMoqParam alert.Alert
		}
		// PutAlertComment holds details about calls to the PutAlertComment method.
		PutAlertComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Comment is the comment argument value.
			Comment alert.AlertComment
		}
		// PutAlertList holds details about calls to the PutAlertList method.
		PutAlertList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// List is the list argument value.
			List alert.List
		}
		// PutHistory holds details about calls to the PutHistory method.
		PutHistory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionID is the sessionID argument value.
			SessionID types.SessionID
			// History is the history argument value.
			History *session.History
		}
		// PutNote holds details about calls to the PutNote method.
		PutNote []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Note is the note argument value.
			Note *session.Note
		}
		// PutPolicyDiff holds details about calls to the PutPolicyDiff method.
		PutPolicyDiff []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Diff is the diff argument value.
			Diff *policy.Diff
		}
		// PutSession holds details about calls to the PutSession method.
		PutSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionMoqParam is the sessionMoqParam argument value.
			SessionMoqParam session.Session
		}
		// SearchAlerts holds details about calls to the SearchAlerts method.
		SearchAlerts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Op is the op argument value.
			Op string
			// Value is the value argument value.
			Value any
		}
	}
	lockBatchGetAlerts             sync.RWMutex
	lockBatchUpdateAlertStatus     sync.RWMutex
	lockGetAlert                   sync.RWMutex
	lockGetAlertByThread           sync.RWMutex
	lockGetAlertComments           sync.RWMutex
	lockGetAlertList               sync.RWMutex
	lockGetAlertListByThread       sync.RWMutex
	lockGetAlertsBySpan            sync.RWMutex
	lockGetAlertsByStatus          sync.RWMutex
	lockGetAlertsWithoutStatus     sync.RWMutex
	lockGetLatestAlertListInThread sync.RWMutex
	lockGetLatestHistory           sync.RWMutex
	lockGetNotes                   sync.RWMutex
	lockGetPolicyDiff              sync.RWMutex
	lockGetSession                 sync.RWMutex
	lockGetSessionByThread         sync.RWMutex
	lockPutAlert                   sync.RWMutex
	lockPutAlertComment            sync.RWMutex
	lockPutAlertList               sync.RWMutex
	lockPutHistory                 sync.RWMutex
	lockPutNote                    sync.RWMutex
	lockPutPolicyDiff              sync.RWMutex
	lockPutSession                 sync.RWMutex
	lockSearchAlerts               sync.RWMutex
}

// BatchGetAlerts calls BatchGetAlertsFunc.
func (mock *RepositoryMock) BatchGetAlerts(ctx context.Context, alertIDs []types.AlertID) (alert.Alerts, error) {
	callInfo := struct {
		Ctx      context.Context
		AlertIDs []types.AlertID
	}{
		Ctx:      ctx,
		AlertIDs: alertIDs,
	}
	mock.lockBatchGetAlerts.Lock()
	mock.calls.BatchGetAlerts = append(mock.calls.BatchGetAlerts, callInfo)
	mock.lockBatchGetAlerts.Unlock()
	if mock.BatchGetAlertsFunc == nil {
		var (
			alertsOut alert.Alerts
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.BatchGetAlertsFunc(ctx, alertIDs)
}

// BatchGetAlertsCalls gets all the calls that were made to BatchGetAlerts.
// Check the length with:
//
//	len(mockedRepository.BatchGetAlertsCalls())
func (mock *RepositoryMock) BatchGetAlertsCalls() []struct {
	Ctx      context.Context
	AlertIDs []types.AlertID
} {
	var calls []struct {
		Ctx      context.Context
		AlertIDs []types.AlertID
	}
	mock.lockBatchGetAlerts.RLock()
	calls = mock.calls.BatchGetAlerts
	mock.lockBatchGetAlerts.RUnlock()
	return calls
}

// BatchUpdateAlertStatus calls BatchUpdateAlertStatusFunc.
func (mock *RepositoryMock) BatchUpdateAlertStatus(ctx context.Context, alertIDs []types.AlertID, status types.AlertStatus, reason string) error {
	callInfo := struct {
		Ctx      context.Context
		AlertIDs []types.AlertID
		Status   types.AlertStatus
		Reason   string
	}{
		Ctx:      ctx,
		AlertIDs: alertIDs,
		Status:   status,
		Reason:   reason,
	}
	mock.lockBatchUpdateAlertStatus.Lock()
	mock.calls.BatchUpdateAlertStatus = append(mock.calls.BatchUpdateAlertStatus, callInfo)
	mock.lockBatchUpdateAlertStatus.Unlock()
	if mock.BatchUpdateAlertStatusFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.BatchUpdateAlertStatusFunc(ctx, alertIDs, status, reason)
}

// BatchUpdateAlertStatusCalls gets all the calls that were made to BatchUpdateAlertStatus.
// Check the length with:
//
//	len(mockedRepository.BatchUpdateAlertStatusCalls())
func (mock *RepositoryMock) BatchUpdateAlertStatusCalls() []struct {
	Ctx      context.Context
	AlertIDs []types.AlertID
	Status   types.AlertStatus
	Reason   string
} {
	var calls []struct {
		Ctx      context.Context
		AlertIDs []types.AlertID
		Status   types.AlertStatus
		Reason   string
	}
	mock.lockBatchUpdateAlertStatus.RLock()
	calls = mock.calls.BatchUpdateAlertStatus
	mock.lockBatchUpdateAlertStatus.RUnlock()
	return calls
}

// GetAlert calls GetAlertFunc.
func (mock *RepositoryMock) GetAlert(ctx context.Context, alertID types.AlertID) (*alert.Alert, error) {
	callInfo := struct {
		Ctx     context.Context
		AlertID types.AlertID
	}{
		Ctx:     ctx,
		AlertID: alertID,
	}
	mock.lockGetAlert.Lock()
	mock.calls.GetAlert = append(mock.calls.GetAlert, callInfo)
	mock.lockGetAlert.Unlock()
	if mock.GetAlertFunc == nil {
		var (
			alertOut *alert.Alert
			errOut   error
		)
		return alertOut, errOut
	}
	return mock.GetAlertFunc(ctx, alertID)
}

// GetAlertCalls gets all the calls that were made to GetAlert.
// Check the length with:
//
//	len(mockedRepository.GetAlertCalls())
func (mock *RepositoryMock) GetAlertCalls() []struct {
	Ctx     context.Context
	AlertID types.AlertID
} {
	var calls []struct {
		Ctx     context.Context
		AlertID types.AlertID
	}
	mock.lockGetAlert.RLock()
	calls = mock.calls.GetAlert
	mock.lockGetAlert.RUnlock()
	return calls
}

// GetAlertByThread calls GetAlertByThreadFunc.
func (mock *RepositoryMock) GetAlertByThread(ctx context.Context, thread modelslack.Thread) (*alert.Alert, error) {
	callInfo := struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}{
		Ctx:    ctx,
		Thread: thread,
	}
	mock.lockGetAlertByThread.Lock()
	mock.calls.GetAlertByThread = append(mock.calls.GetAlertByThread, callInfo)
	mock.lockGetAlertByThread.Unlock()
	if mock.GetAlertByThreadFunc == nil {
		var (
			alertOut *alert.Alert
			errOut   error
		)
		return alertOut, errOut
	}
	return mock.GetAlertByThreadFunc(ctx, thread)
}

// GetAlertByThreadCalls gets all the calls that were made to GetAlertByThread.
// Check the length with:
//
//	len(mockedRepository.GetAlertByThreadCalls())
func (mock *RepositoryMock) GetAlertByThreadCalls() []struct {
	Ctx    context.Context
	Thread modelslack.Thread
} {
	var calls []struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}
	mock.lockGetAlertByThread.RLock()
	calls = mock.calls.GetAlertByThread
	mock.lockGetAlertByThread.RUnlock()
	return calls
}

// GetAlertComments calls GetAlertCommentsFunc.
func (mock *RepositoryMock) GetAlertComments(ctx context.Context, alertID types.AlertID) ([]alert.AlertComment, error) {
	callInfo := struct {
		Ctx     context.Context
		AlertID types.AlertID
	}{
		Ctx:     ctx,
		AlertID: alertID,
	}
	mock.lockGetAlertComments.Lock()
	mock.calls.GetAlertComments = append(mock.calls.GetAlertComments, callInfo)
	mock.lockGetAlertComments.Unlock()
	if mock.GetAlertCommentsFunc == nil {
		var (
			alertCommentsOut []alert.AlertComment
			errOut           error
		)
		return alertCommentsOut, errOut
	}
	return mock.GetAlertCommentsFunc(ctx, alertID)
}

// GetAlertCommentsCalls gets all the calls that were made to GetAlertComments.
// Check the length with:
//
//	len(mockedRepository.GetAlertCommentsCalls())
func (mock *RepositoryMock) GetAlertCommentsCalls() []struct {
	Ctx     context.Context
	AlertID types.AlertID
} {
	var calls []struct {
		Ctx     context.Context
		AlertID types.AlertID
	}
	mock.lockGetAlertComments.RLock()
	calls = mock.calls.GetAlertComments
	mock.lockGetAlertComments.RUnlock()
	return calls
}

// GetAlertList calls GetAlertListFunc.
func (mock *RepositoryMock) GetAlertList(ctx context.Context, listID types.AlertListID) (*alert.List, error) {
	callInfo := struct {
		Ctx    context.Context
		ListID types.AlertListID
	}{
		Ctx:    ctx,
		ListID: listID,
	}
	mock.lockGetAlertList.Lock()
	mock.calls.GetAlertList = append(mock.calls.GetAlertList, callInfo)
	mock.lockGetAlertList.Unlock()
	if mock.GetAlertListFunc == nil {
		var (
			listOut *alert.List
			errOut  error
		)
		return listOut, errOut
	}
	return mock.GetAlertListFunc(ctx, listID)
}

// GetAlertListCalls gets all the calls that were made to GetAlertList.
// Check the length with:
//
//	len(mockedRepository.GetAlertListCalls())
func (mock *RepositoryMock) GetAlertListCalls() []struct {
	Ctx    context.Context
	ListID types.AlertListID
} {
	var calls []struct {
		Ctx    context.Context
		ListID types.AlertListID
	}
	mock.lockGetAlertList.RLock()
	calls = mock.calls.GetAlertList
	mock.lockGetAlertList.RUnlock()
	return calls
}

// GetAlertListByThread calls GetAlertListByThreadFunc.
func (mock *RepositoryMock) GetAlertListByThread(ctx context.Context, thread modelslack.Thread) (*alert.List, error) {
	callInfo := struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}{
		Ctx:    ctx,
		Thread: thread,
	}
	mock.lockGetAlertListByThread.Lock()
	mock.calls.GetAlertListByThread = append(mock.calls.GetAlertListByThread, callInfo)
	mock.lockGetAlertListByThread.Unlock()
	if mock.GetAlertListByThreadFunc == nil {
		var (
			listOut *alert.List
			errOut  error
		)
		return listOut, errOut
	}
	return mock.GetAlertListByThreadFunc(ctx, thread)
}

// GetAlertListByThreadCalls gets all the calls that were made to GetAlertListByThread.
// Check the length with:
//
//	len(mockedRepository.GetAlertListByThreadCalls())
func (mock *RepositoryMock) GetAlertListByThreadCalls() []struct {
	Ctx    context.Context
	Thread modelslack.Thread
} {
	var calls []struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}
	mock.lockGetAlertListByThread.RLock()
	calls = mock.calls.GetAlertListByThread
	mock.lockGetAlertListByThread.RUnlock()
	return calls
}

// GetAlertsBySpan calls GetAlertsBySpanFunc.
func (mock *RepositoryMock) GetAlertsBySpan(ctx context.Context, begin time.Time, end time.Time) (alert.Alerts, error) {
	callInfo := struct {
		Ctx   context.Context
		Begin time.Time
		End   time.Time
	}{
		Ctx:   ctx,
		Begin: begin,
		End:   end,
	}
	mock.lockGetAlertsBySpan.Lock()
	mock.calls.GetAlertsBySpan = append(mock.calls.GetAlertsBySpan, callInfo)
	mock.lockGetAlertsBySpan.Unlock()
	if mock.GetAlertsBySpanFunc == nil {
		var (
			alertsOut alert.Alerts
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.GetAlertsBySpanFunc(ctx, begin, end)
}

// GetAlertsBySpanCalls gets all the calls that were made to GetAlertsBySpan.
// Check the length with:
//
//	len(mockedRepository.GetAlertsBySpanCalls())
func (mock *RepositoryMock) GetAlertsBySpanCalls() []struct {
	Ctx   context.Context
	Begin time.Time
	End   time.Time
} {
	var calls []struct {
		Ctx   context.Context
		Begin time.Time
		End   time.Time
	}
	mock.lockGetAlertsBySpan.RLock()
	calls = mock.calls.GetAlertsBySpan
	mock.lockGetAlertsBySpan.RUnlock()
	return calls
}

// GetAlertsByStatus calls GetAlertsByStatusFunc.
func (mock *RepositoryMock) GetAlertsByStatus(ctx context.Context, status ...types.AlertStatus) (alert.Alerts, error) {
	callInfo := struct {
		Ctx    context.Context
		Status []types.AlertStatus
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockGetAlertsByStatus.Lock()
	mock.calls.GetAlertsByStatus = append(mock.calls.GetAlertsByStatus, callInfo)
	mock.lockGetAlertsByStatus.Unlock()
	if mock.GetAlertsByStatusFunc == nil {
		var (
			alertsOut alert.Alerts
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.GetAlertsByStatusFunc(ctx, status...)
}

// GetAlertsByStatusCalls gets all the calls that were made to GetAlertsByStatus.
// Check the length with:
//
//	len(mockedRepository.GetAlertsByStatusCalls())
func (mock *RepositoryMock) GetAlertsByStatusCalls() []struct {
	Ctx    context.Context
	Status []types.AlertStatus
} {
	var calls []struct {
		Ctx    context.Context
		Status []types.AlertStatus
	}
	mock.lockGetAlertsByStatus.RLock()
	calls = mock.calls.GetAlertsByStatus
	mock.lockGetAlertsByStatus.RUnlock()
	return calls
}

// GetAlertsWithoutStatus calls GetAlertsWithoutStatusFunc.
func (mock *RepositoryMock) GetAlertsWithoutStatus(ctx context.Context, status types.AlertStatus) (alert.Alerts, error) {
	callInfo := struct {
		Ctx    context.Context
		Status types.AlertStatus
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockGetAlertsWithoutStatus.Lock()
	mock.calls.GetAlertsWithoutStatus = append(mock.calls.GetAlertsWithoutStatus, callInfo)
	mock.lockGetAlertsWithoutStatus.Unlock()
	if mock.GetAlertsWithoutStatusFunc == nil {
		var (
			alertsOut alert.Alerts
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.GetAlertsWithoutStatusFunc(ctx, status)
}

// GetAlertsWithoutStatusCalls gets all the calls that were made to GetAlertsWithoutStatus.
// Check the length with:
//
//	len(mockedRepository.GetAlertsWithoutStatusCalls())
func (mock *RepositoryMock) GetAlertsWithoutStatusCalls() []struct {
	Ctx    context.Context
	Status types.AlertStatus
} {
	var calls []struct {
		Ctx    context.Context
		Status types.AlertStatus
	}
	mock.lockGetAlertsWithoutStatus.RLock()
	calls = mock.calls.GetAlertsWithoutStatus
	mock.lockGetAlertsWithoutStatus.RUnlock()
	return calls
}

// GetLatestAlertListInThread calls GetLatestAlertListInThreadFunc.
func (mock *RepositoryMock) GetLatestAlertListInThread(ctx context.Context, thread modelslack.Thread) (*alert.List, error) {
	callInfo := struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}{
		Ctx:    ctx,
		Thread: thread,
	}
	mock.lockGetLatestAlertListInThread.Lock()
	mock.calls.GetLatestAlertListInThread = append(mock.calls.GetLatestAlertListInThread, callInfo)
	mock.lockGetLatestAlertListInThread.Unlock()
	if mock.GetLatestAlertListInThreadFunc == nil {
		var (
			listOut *alert.List
			errOut  error
		)
		return listOut, errOut
	}
	return mock.GetLatestAlertListInThreadFunc(ctx, thread)
}

// GetLatestAlertListInThreadCalls gets all the calls that were made to GetLatestAlertListInThread.
// Check the length with:
//
//	len(mockedRepository.GetLatestAlertListInThreadCalls())
func (mock *RepositoryMock) GetLatestAlertListInThreadCalls() []struct {
	Ctx    context.Context
	Thread modelslack.Thread
} {
	var calls []struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}
	mock.lockGetLatestAlertListInThread.RLock()
	calls = mock.calls.GetLatestAlertListInThread
	mock.lockGetLatestAlertListInThread.RUnlock()
	return calls
}

// GetLatestHistory calls GetLatestHistoryFunc.
func (mock *RepositoryMock) GetLatestHistory(ctx context.Context, sessionID types.SessionID) (*session.History, error) {
	callInfo := struct {
		Ctx       context.Context
		SessionID types.SessionID
	}{
		Ctx:       ctx,
		SessionID: sessionID,
	}
	mock.lockGetLatestHistory.Lock()
	mock.calls.GetLatestHistory = append(mock.calls.GetLatestHistory, callInfo)
	mock.lockGetLatestHistory.Unlock()
	if mock.GetLatestHistoryFunc == nil {
		var (
			historyOut *session.History
			errOut     error
		)
		return historyOut, errOut
	}
	return mock.GetLatestHistoryFunc(ctx, sessionID)
}

// GetLatestHistoryCalls gets all the calls that were made to GetLatestHistory.
// Check the length with:
//
//	len(mockedRepository.GetLatestHistoryCalls())
func (mock *RepositoryMock) GetLatestHistoryCalls() []struct {
	Ctx       context.Context
	SessionID types.SessionID
} {
	var calls []struct {
		Ctx       context.Context
		SessionID types.SessionID
	}
	mock.lockGetLatestHistory.RLock()
	calls = mock.calls.GetLatestHistory
	mock.lockGetLatestHistory.RUnlock()
	return calls
}

// GetNotes calls GetNotesFunc.
func (mock *RepositoryMock) GetNotes(ctx context.Context, sessionID types.SessionID) ([]*session.Note, error) {
	callInfo := struct {
		Ctx       context.Context
		SessionID types.SessionID
	}{
		Ctx:       ctx,
		SessionID: sessionID,
	}
	mock.lockGetNotes.Lock()
	mock.calls.GetNotes = append(mock.calls.GetNotes, callInfo)
	mock.lockGetNotes.Unlock()
	if mock.GetNotesFunc == nil {
		var (
			notesOut []*session.Note
			errOut   error
		)
		return notesOut, errOut
	}
	return mock.GetNotesFunc(ctx, sessionID)
}

// GetNotesCalls gets all the calls that were made to GetNotes.
// Check the length with:
//
//	len(mockedRepository.GetNotesCalls())
func (mock *RepositoryMock) GetNotesCalls() []struct {
	Ctx       context.Context
	SessionID types.SessionID
} {
	var calls []struct {
		Ctx       context.Context
		SessionID types.SessionID
	}
	mock.lockGetNotes.RLock()
	calls = mock.calls.GetNotes
	mock.lockGetNotes.RUnlock()
	return calls
}

// GetPolicyDiff calls GetPolicyDiffFunc.
func (mock *RepositoryMock) GetPolicyDiff(ctx context.Context, id types.PolicyDiffID) (*policy.Diff, error) {
	callInfo := struct {
		Ctx context.Context
		ID  types.PolicyDiffID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetPolicyDiff.Lock()
	mock.calls.GetPolicyDiff = append(mock.calls.GetPolicyDiff, callInfo)
	mock.lockGetPolicyDiff.Unlock()
	if mock.GetPolicyDiffFunc == nil {
		var (
			diffOut *policy.Diff
			errOut  error
		)
		return diffOut, errOut
	}
	return mock.GetPolicyDiffFunc(ctx, id)
}

// GetPolicyDiffCalls gets all the calls that were made to GetPolicyDiff.
// Check the length with:
//
//	len(mockedRepository.GetPolicyDiffCalls())
func (mock *RepositoryMock) GetPolicyDiffCalls() []struct {
	Ctx context.Context
	ID  types.PolicyDiffID
} {
	var calls []struct {
		Ctx context.Context
		ID  types.PolicyDiffID
	}
	mock.lockGetPolicyDiff.RLock()
	calls = mock.calls.GetPolicyDiff
	mock.lockGetPolicyDiff.RUnlock()
	return calls
}

// GetSession calls GetSessionFunc.
func (mock *RepositoryMock) GetSession(ctx context.Context, id types.SessionID) (*session.Session, error) {
	callInfo := struct {
		Ctx context.Context
		ID  types.SessionID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetSession.Lock()
	mock.calls.GetSession = append(mock.calls.GetSession, callInfo)
	mock.lockGetSession.Unlock()
	if mock.GetSessionFunc == nil {
		var (
			sessionOut *session.Session
			errOut     error
		)
		return sessionOut, errOut
	}
	return mock.GetSessionFunc(ctx, id)
}

// GetSessionCalls gets all the calls that were made to GetSession.
// Check the length with:
//
//	len(mockedRepository.GetSessionCalls())
func (mock *RepositoryMock) GetSessionCalls() []struct {
	Ctx context.Context
	ID  types.SessionID
} {
	var calls []struct {
		Ctx context.Context
		ID  types.SessionID
	}
	mock.lockGetSession.RLock()
	calls = mock.calls.GetSession
	mock.lockGetSession.RUnlock()
	return calls
}

// GetSessionByThread calls GetSessionByThreadFunc.
func (mock *RepositoryMock) GetSessionByThread(ctx context.Context, thread modelslack.Thread) (*session.Session, error) {
	callInfo := struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}{
		Ctx:    ctx,
		Thread: thread,
	}
	mock.lockGetSessionByThread.Lock()
	mock.calls.GetSessionByThread = append(mock.calls.GetSessionByThread, callInfo)
	mock.lockGetSessionByThread.Unlock()
	if mock.GetSessionByThreadFunc == nil {
		var (
			sessionOut *session.Session
			errOut     error
		)
		return sessionOut, errOut
	}
	return mock.GetSessionByThreadFunc(ctx, thread)
}

// GetSessionByThreadCalls gets all the calls that were made to GetSessionByThread.
// Check the length with:
//
//	len(mockedRepository.GetSessionByThreadCalls())
func (mock *RepositoryMock) GetSessionByThreadCalls() []struct {
	Ctx    context.Context
	Thread modelslack.Thread
} {
	var calls []struct {
		Ctx    context.Context
		Thread modelslack.Thread
	}
	mock.lockGetSessionByThread.RLock()
	calls = mock.calls.GetSessionByThread
	mock.lockGetSessionByThread.RUnlock()
	return calls
}

// PutAlert calls PutAlertFunc.
func (mock *RepositoryMock) PutAlert(ctx context.Context, alertMoqParam alert.Alert) error {
	callInfo := struct {
		Ctx           context.Context
		AlertMoqParam alert.Alert
	}{
		Ctx:           ctx,
		AlertMoqParam: alertMoqParam,
	}
	mock.lockPutAlert.Lock()
	mock.calls.PutAlert = append(mock.calls.PutAlert, callInfo)
	mock.lockPutAlert.Unlock()
	if mock.PutAlertFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutAlertFunc(ctx, alertMoqParam)
}

// PutAlertCalls gets all the calls that were made to PutAlert.
// Check the length with:
//
//	len(mockedRepository.PutAlertCalls())
func (mock *RepositoryMock) PutAlertCalls() []struct {
	Ctx           context.Context
	AlertMoqParam alert.Alert
} {
	var calls []struct {
		Ctx           context.Context
		AlertMoqParam alert.Alert
	}
	mock.lockPutAlert.RLock()
	calls = mock.calls.PutAlert
	mock.lockPutAlert.RUnlock()
	return calls
}

// PutAlertComment calls PutAlertCommentFunc.
func (mock *RepositoryMock) PutAlertComment(ctx context.Context, comment alert.AlertComment) error {
	callInfo := struct {
		Ctx     context.Context
		Comment alert.AlertComment
	}{
		Ctx:     ctx,
		Comment: comment,
	}
	mock.lockPutAlertComment.Lock()
	mock.calls.PutAlertComment = append(mock.calls.PutAlertComment, callInfo)
	mock.lockPutAlertComment.Unlock()
	if mock.PutAlertCommentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutAlertCommentFunc(ctx, comment)
}

// PutAlertCommentCalls gets all the calls that were made to PutAlertComment.
// Check the length with:
//
//	len(mockedRepository.PutAlertCommentCalls())
func (mock *RepositoryMock) PutAlertCommentCalls() []struct {
	Ctx     context.Context
	Comment alert.AlertComment
} {
	var calls []struct {
		Ctx     context.Context
		Comment alert.AlertComment
	}
	mock.lockPutAlertComment.RLock()
	calls = mock.calls.PutAlertComment
	mock.lockPutAlertComment.RUnlock()
	return calls
}

// PutAlertList calls PutAlertListFunc.
func (mock *RepositoryMock) PutAlertList(ctx context.Context, list alert.List) error {
	callInfo := struct {
		Ctx  context.Context
		List alert.List
	}{
		Ctx:  ctx,
		List: list,
	}
	mock.lockPutAlertList.Lock()
	mock.calls.PutAlertList = append(mock.calls.PutAlertList, callInfo)
	mock.lockPutAlertList.Unlock()
	if mock.PutAlertListFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutAlertListFunc(ctx, list)
}

// PutAlertListCalls gets all the calls that were made to PutAlertList.
// Check the length with:
//
//	len(mockedRepository.PutAlertListCalls())
func (mock *RepositoryMock) PutAlertListCalls() []struct {
	Ctx  context.Context
	List alert.List
} {
	var calls []struct {
		Ctx  context.Context
		List alert.List
	}
	mock.lockPutAlertList.RLock()
	calls = mock.calls.PutAlertList
	mock.lockPutAlertList.RUnlock()
	return calls
}

// PutHistory calls PutHistoryFunc.
func (mock *RepositoryMock) PutHistory(ctx context.Context, sessionID types.SessionID, history *session.History) error {
	callInfo := struct {
		Ctx       context.Context
		SessionID types.SessionID
		History   *session.History
	}{
		Ctx:       ctx,
		SessionID: sessionID,
		History:   history,
	}
	mock.lockPutHistory.Lock()
	mock.calls.PutHistory = append(mock.calls.PutHistory, callInfo)
	mock.lockPutHistory.Unlock()
	if mock.PutHistoryFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutHistoryFunc(ctx, sessionID, history)
}

// PutHistoryCalls gets all the calls that were made to PutHistory.
// Check the length with:
//
//	len(mockedRepository.PutHistoryCalls())
func (mock *RepositoryMock) PutHistoryCalls() []struct {
	Ctx       context.Context
	SessionID types.SessionID
	History   *session.History
} {
	var calls []struct {
		Ctx       context.Context
		SessionID types.SessionID
		History   *session.History
	}
	mock.lockPutHistory.RLock()
	calls = mock.calls.PutHistory
	mock.lockPutHistory.RUnlock()
	return calls
}

// PutNote calls PutNoteFunc.
func (mock *RepositoryMock) PutNote(ctx context.Context, note *session.Note) error {
	callInfo := struct {
		Ctx  context.Context
		Note *session.Note
	}{
		Ctx:  ctx,
		Note: note,
	}
	mock.lockPutNote.Lock()
	mock.calls.PutNote = append(mock.calls.PutNote, callInfo)
	mock.lockPutNote.Unlock()
	if mock.PutNoteFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutNoteFunc(ctx, note)
}

// PutNoteCalls gets all the calls that were made to PutNote.
// Check the length with:
//
//	len(mockedRepository.PutNoteCalls())
func (mock *RepositoryMock) PutNoteCalls() []struct {
	Ctx  context.Context
	Note *session.Note
} {
	var calls []struct {
		Ctx  context.Context
		Note *session.Note
	}
	mock.lockPutNote.RLock()
	calls = mock.calls.PutNote
	mock.lockPutNote.RUnlock()
	return calls
}

// PutPolicyDiff calls PutPolicyDiffFunc.
func (mock *RepositoryMock) PutPolicyDiff(ctx context.Context, diff *policy.Diff) error {
	callInfo := struct {
		Ctx  context.Context
		Diff *policy.Diff
	}{
		Ctx:  ctx,
		Diff: diff,
	}
	mock.lockPutPolicyDiff.Lock()
	mock.calls.PutPolicyDiff = append(mock.calls.PutPolicyDiff, callInfo)
	mock.lockPutPolicyDiff.Unlock()
	if mock.PutPolicyDiffFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutPolicyDiffFunc(ctx, diff)
}

// PutPolicyDiffCalls gets all the calls that were made to PutPolicyDiff.
// Check the length with:
//
//	len(mockedRepository.PutPolicyDiffCalls())
func (mock *RepositoryMock) PutPolicyDiffCalls() []struct {
	Ctx  context.Context
	Diff *policy.Diff
} {
	var calls []struct {
		Ctx  context.Context
		Diff *policy.Diff
	}
	mock.lockPutPolicyDiff.RLock()
	calls = mock.calls.PutPolicyDiff
	mock.lockPutPolicyDiff.RUnlock()
	return calls
}

// PutSession calls PutSessionFunc.
func (mock *RepositoryMock) PutSession(ctx context.Context, sessionMoqParam session.Session) error {
	callInfo := struct {
		Ctx             context.Context
		SessionMoqParam session.Session
	}{
		Ctx:             ctx,
		SessionMoqParam: sessionMoqParam,
	}
	mock.lockPutSession.Lock()
	mock.calls.PutSession = append(mock.calls.PutSession, callInfo)
	mock.lockPutSession.Unlock()
	if mock.PutSessionFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutSessionFunc(ctx, sessionMoqParam)
}

// PutSessionCalls gets all the calls that were made to PutSession.
// Check the length with:
//
//	len(mockedRepository.PutSessionCalls())
func (mock *RepositoryMock) PutSessionCalls() []struct {
	Ctx             context.Context
	SessionMoqParam session.Session
} {
	var calls []struct {
		Ctx             context.Context
		SessionMoqParam session.Session
	}
	mock.lockPutSession.RLock()
	calls = mock.calls.PutSession
	mock.lockPutSession.RUnlock()
	return calls
}

// SearchAlerts calls SearchAlertsFunc.
func (mock *RepositoryMock) SearchAlerts(ctx context.Context, path string, op string, value any) (alert.Alerts, error) {
	callInfo := struct {
		Ctx   context.Context
		Path  string
		Op    string
		Value any
	}{
		Ctx:   ctx,
		Path:  path,
		Op:    op,
		Value: value,
	}
	mock.lockSearchAlerts.Lock()
	mock.calls.SearchAlerts = append(mock.calls.SearchAlerts, callInfo)
	mock.lockSearchAlerts.Unlock()
	if mock.SearchAlertsFunc == nil {
		var (
			alertsOut alert.Alerts
			errOut    error
		)
		return alertsOut, errOut
	}
	return mock.SearchAlertsFunc(ctx, path, op, value)
}

// SearchAlertsCalls gets all the calls that were made to SearchAlerts.
// Check the length with:
//
//	len(mockedRepository.SearchAlertsCalls())
func (mock *RepositoryMock) SearchAlertsCalls() []struct {
	Ctx   context.Context
	Path  string
	Op    string
	Value any
} {
	var calls []struct {
		Ctx   context.Context
		Path  string
		Op    string
		Value any
	}
	mock.lockSearchAlerts.RLock()
	calls = mock.calls.SearchAlerts
	mock.lockSearchAlerts.RUnlock()
	return calls
}

// PolicyClientMock is a mock implementation of PolicyClient.
//
//	func TestSomethingThatUsesPolicyClient(t *testing.T) {
//
//		// make and configure a mocked PolicyClient
//		mockedPolicyClient := &PolicyClientMock{
//			QueryFunc: func(contextMoqParam context.Context, s string, v1 any, v2 any, queryOptions ...opaq.QueryOption) error {
//				panic("mock out the Query method")
//			},
//			SourcesFunc: func() map[string]string {
//				panic("mock out the Sources method")
//			},
//		}
//
//		// use mockedPolicyClient in code that requires PolicyClient
//		// and then make assertions.
//
//	}
type PolicyClientMock struct {
	// QueryFunc mocks the Query method.
	QueryFunc func(contextMoqParam context.Context, s string, v1 any, v2 any, queryOptions ...opaq.QueryOption) error

	// SourcesFunc mocks the Sources method.
	SourcesFunc func() map[string]string

	// calls tracks calls to the methods.
	calls struct {
		// Query holds details about calls to the Query method.
		Query []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// V1 is the v1 argument value.
			V1 any
			// V2 is the v2 argument value.
			V2 any
			// QueryOptions is the queryOptions argument value.
			QueryOptions []opaq.QueryOption
		}
		// Sources holds details about calls to the Sources method.
		Sources []struct {
		}
	}
	lockQuery   sync.RWMutex
	lockSources sync.RWMutex
}

// Query calls QueryFunc.
func (mock *PolicyClientMock) Query(contextMoqParam context.Context, s string, v1 any, v2 any, queryOptions ...opaq.QueryOption) error {
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
		V1              any
		V2              any
		QueryOptions    []opaq.QueryOption
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
		V1:              v1,
		V2:              v2,
		QueryOptions:    queryOptions,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	if mock.QueryFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.QueryFunc(contextMoqParam, s, v1, v2, queryOptions...)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedPolicyClient.QueryCalls())
func (mock *PolicyClientMock) QueryCalls() []struct {
	ContextMoqParam context.Context
	S               string
	V1              any
	V2              any
	QueryOptions    []opaq.QueryOption
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
		V1              any
		V2              any
		QueryOptions    []opaq.QueryOption
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// Sources calls SourcesFunc.
func (mock *PolicyClientMock) Sources() map[string]string {
	callInfo := struct {
	}{}
	mock.lockSources.Lock()
	mock.calls.Sources = append(mock.calls.Sources, callInfo)
	mock.lockSources.Unlock()
	if mock.SourcesFunc == nil {
		var (
			stringToStringOut map[string]string
		)
		return stringToStringOut
	}
	return mock.SourcesFunc()
}

// SourcesCalls gets all the calls that were made to Sources.
// Check the length with:
//
//	len(mockedPolicyClient.SourcesCalls())
func (mock *PolicyClientMock) SourcesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSources.RLock()
	calls = mock.calls.Sources
	mock.lockSources.RUnlock()
	return calls
}

// EmbeddingClientMock is a mock implementation of EmbeddingClient.
//
//	func TestSomethingThatUsesEmbeddingClient(t *testing.T) {
//
//		// make and configure a mocked EmbeddingClient
//		mockedEmbeddingClient := &EmbeddingClientMock{
//			EmbeddingsFunc: func(ctx context.Context, texts []string, dimensionality int) ([][]float32, error) {
//				panic("mock out the Embeddings method")
//			},
//		}
//
//		// use mockedEmbeddingClient in code that requires EmbeddingClient
//		// and then make assertions.
//
//	}
type EmbeddingClientMock struct {
	// EmbeddingsFunc mocks the Embeddings method.
	EmbeddingsFunc func(ctx context.Context, texts []string, dimensionality int) ([][]float32, error)

	// calls tracks calls to the methods.
	calls struct {
		// Embeddings holds details about calls to the Embeddings method.
		Embeddings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Texts is the texts argument value.
			Texts []string
			// Dimensionality is the dimensionality argument value.
			Dimensionality int
		}
	}
	lockEmbeddings sync.RWMutex
}

// Embeddings calls EmbeddingsFunc.
func (mock *EmbeddingClientMock) Embeddings(ctx context.Context, texts []string, dimensionality int) ([][]float32, error) {
	callInfo := struct {
		Ctx            context.Context
		Texts          []string
		Dimensionality int
	}{
		Ctx:            ctx,
		Texts:          texts,
		Dimensionality: dimensionality,
	}
	mock.lockEmbeddings.Lock()
	mock.calls.Embeddings = append(mock.calls.Embeddings, callInfo)
	mock.lockEmbeddings.Unlock()
	if mock.EmbeddingsFunc == nil {
		var (
			float32ssOut [][]float32
			errOut       error
		)
		return float32ssOut, errOut
	}
	return mock.EmbeddingsFunc(ctx, texts, dimensionality)
}

// EmbeddingsCalls gets all the calls that were made to Embeddings.
// Check the length with:
//
//	len(mockedEmbeddingClient.EmbeddingsCalls())
func (mock *EmbeddingClientMock) EmbeddingsCalls() []struct {
	Ctx            context.Context
	Texts          []string
	Dimensionality int
} {
	var calls []struct {
		Ctx            context.Context
		Texts          []string
		Dimensionality int
	}
	mock.lockEmbeddings.RLock()
	calls = mock.calls.Embeddings
	mock.lockEmbeddings.RUnlock()
	return calls
}
