// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/secmon-lab/warren/pkg/domain/model/alert"
	"github.com/secmon-lab/warren/pkg/domain/model/ticket"
)

type ActivitiesResponse struct {
	Activities []*Activity `json:"activities"`
	TotalCount int         `json:"totalCount"`
}

type Activity struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	UserID    *string        `json:"userID,omitempty"`
	AlertID   *string        `json:"alertID,omitempty"`
	TicketID  *string        `json:"ticketID,omitempty"`
	CommentID *string        `json:"commentID,omitempty"`
	CreatedAt string         `json:"createdAt"`
	Metadata  *string        `json:"metadata,omitempty"`
	User      *User          `json:"user,omitempty"`
	Alert     *alert.Alert   `json:"alert,omitempty"`
	Ticket    *ticket.Ticket `json:"ticket,omitempty"`
}

type AgentMemoriesResponse struct {
	Memories   []*AgentMemory `json:"memories"`
	TotalCount int            `json:"totalCount"`
}

type AgentMemory struct {
	ID         string  `json:"id"`
	AgentID    string  `json:"agentID"`
	Query      string  `json:"query"`
	Claim      string  `json:"claim"`
	Score      float64 `json:"score"`
	CreatedAt  string  `json:"createdAt"`
	LastUsedAt *string `json:"lastUsedAt,omitempty"`
}

type AgentSummariesResponse struct {
	Agents     []*AgentSummary `json:"agents"`
	TotalCount int             `json:"totalCount"`
}

type AgentSummary struct {
	AgentID        string  `json:"agentID"`
	MemoriesCount  int     `json:"memoriesCount"`
	LatestMemoryAt *string `json:"latestMemoryAt,omitempty"`
}

type AlertAttribute struct {
	Key   string  `json:"key"`
	Value string  `json:"value"`
	Link  *string `json:"link,omitempty"`
	Auto  bool    `json:"auto"`
}

type AlertsResponse struct {
	Alerts     []*alert.Alert `json:"alerts"`
	TotalCount int            `json:"totalCount"`
}

type CommentsResponse struct {
	Comments   []*ticket.Comment `json:"comments"`
	TotalCount int               `json:"totalCount"`
}

type CreateKnowledgeInput struct {
	Topic   string `json:"topic"`
	Slug    string `json:"slug"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type DashboardStats struct {
	OpenTicketsCount    int              `json:"openTicketsCount"`
	UnboundAlertsCount  int              `json:"unboundAlertsCount"`
	DeclinedAlertsCount int              `json:"declinedAlertsCount"`
	OpenTickets         []*ticket.Ticket `json:"openTickets"`
	UnboundAlerts       []*alert.Alert   `json:"unboundAlerts"`
}

type Knowledge struct {
	Slug      string `json:"slug"`
	Name      string `json:"name"`
	Topic     string `json:"topic"`
	Content   string `json:"content"`
	CommitID  string `json:"commitID"`
	AuthorID  string `json:"authorID"`
	Author    *User  `json:"author"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	State     string `json:"state"`
}

type Mutation struct {
}

type Query struct {
}

type Session struct {
	ID        string  `json:"id"`
	TicketID  string  `json:"ticketID"`
	Status    string  `json:"status"`
	UserID    *string `json:"userID,omitempty"`
	User      *User   `json:"user,omitempty"`
	Query     *string `json:"query,omitempty"`
	SlackURL  *string `json:"slackURL,omitempty"`
	Intent    *string `json:"intent,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type SessionMessage struct {
	ID        string `json:"id"`
	SessionID string `json:"sessionID"`
	Type      string `json:"type"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type TagMetadata struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Color       string  `json:"color"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type TagObject struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type TicketsResponse struct {
	Tickets    []*ticket.Ticket `json:"tickets"`
	TotalCount int              `json:"totalCount"`
}

type TopicSummary struct {
	Topic string `json:"topic"`
	Count int    `json:"count"`
}

type UpdateKnowledgeInput struct {
	Topic   string `json:"topic"`
	Slug    string `json:"slug"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type UpdateTagInput struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Color       string  `json:"color"`
	Description *string `json:"description,omitempty"`
}

type User struct {
	ID   string  `json:"id"`
	Name string  `json:"name"`
	Icon *string `json:"icon,omitempty"`
}

type MemorySortField string

const (
	MemorySortFieldScore      MemorySortField = "SCORE"
	MemorySortFieldCreatedAt  MemorySortField = "CREATED_AT"
	MemorySortFieldLastUsedAt MemorySortField = "LAST_USED_AT"
)

var AllMemorySortField = []MemorySortField{
	MemorySortFieldScore,
	MemorySortFieldCreatedAt,
	MemorySortFieldLastUsedAt,
}

func (e MemorySortField) IsValid() bool {
	switch e {
	case MemorySortFieldScore, MemorySortFieldCreatedAt, MemorySortFieldLastUsedAt:
		return true
	}
	return false
}

func (e MemorySortField) String() string {
	return string(e)
}

func (e *MemorySortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MemorySortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MemorySortField", str)
	}
	return nil
}

func (e MemorySortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MemorySortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MemorySortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
