// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/secmon-lab/warren/pkg/domain/model/alert"
	"github.com/secmon-lab/warren/pkg/domain/model/ticket"
)

type ActivitiesResponse struct {
	Activities []*Activity `json:"activities"`
	TotalCount int         `json:"totalCount"`
}

type Activity struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	UserID    *string        `json:"userID,omitempty"`
	AlertID   *string        `json:"alertID,omitempty"`
	TicketID  *string        `json:"ticketID,omitempty"`
	CommentID *string        `json:"commentID,omitempty"`
	CreatedAt string         `json:"createdAt"`
	Metadata  *string        `json:"metadata,omitempty"`
	User      *User          `json:"user,omitempty"`
	Alert     *alert.Alert   `json:"alert,omitempty"`
	Ticket    *ticket.Ticket `json:"ticket,omitempty"`
}

type AlertAttribute struct {
	Key   string  `json:"key"`
	Value string  `json:"value"`
	Link  *string `json:"link,omitempty"`
	Auto  bool    `json:"auto"`
}

type AlertsResponse struct {
	Alerts     []*alert.Alert `json:"alerts"`
	TotalCount int            `json:"totalCount"`
}

type CommentsResponse struct {
	Comments   []*ticket.Comment `json:"comments"`
	TotalCount int               `json:"totalCount"`
}

type CreateKnowledgeInput struct {
	Category string   `json:"category"`
	Title    string   `json:"title"`
	Claim    string   `json:"claim"`
	Tags     []string `json:"tags"`
	Message  string   `json:"message"`
	TicketID *string  `json:"ticketID,omitempty"`
}

type CreateKnowledgeTagInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type DashboardStats struct {
	OpenTicketsCount    int              `json:"openTicketsCount"`
	UnboundAlertsCount  int              `json:"unboundAlertsCount"`
	DeclinedAlertsCount int              `json:"declinedAlertsCount"`
	QueuedAlertsCount   int              `json:"queuedAlertsCount"`
	OpenTickets         []*ticket.Ticket `json:"openTickets"`
	UnboundAlerts       []*alert.Alert   `json:"unboundAlerts"`
}

type DiagnosesResponse struct {
	Diagnoses  []*Diagnosis `json:"diagnoses"`
	TotalCount int          `json:"totalCount"`
}

type Diagnosis struct {
	ID           string `json:"id"`
	Status       string `json:"status"`
	TotalCount   int    `json:"totalCount"`
	PendingCount int    `json:"pendingCount"`
	FixedCount   int    `json:"fixedCount"`
	FailedCount  int    `json:"failedCount"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type DiagnosisIssue struct {
	ID          string  `json:"id"`
	DiagnosisID string  `json:"diagnosisID"`
	RuleID      string  `json:"ruleID"`
	TargetID    string  `json:"targetID"`
	Description string  `json:"description"`
	Status      string  `json:"status"`
	FixedAt     *string `json:"fixedAt,omitempty"`
	FailReason  *string `json:"failReason,omitempty"`
	CreatedAt   string  `json:"createdAt"`
}

type DiagnosisIssuesResponse struct {
	Issues     []*DiagnosisIssue `json:"issues"`
	TotalCount int               `json:"totalCount"`
}

type Knowledge struct {
	ID        string          `json:"id"`
	Category  string          `json:"category"`
	Title     string          `json:"title"`
	Claim     string          `json:"claim"`
	Tags      []*KnowledgeTag `json:"tags"`
	AuthorID  string          `json:"authorID"`
	Author    *User           `json:"author"`
	CreatedAt string          `json:"createdAt"`
	UpdatedAt string          `json:"updatedAt"`
}

type KnowledgeLog struct {
	ID          string  `json:"id"`
	KnowledgeID string  `json:"knowledgeID"`
	Title       string  `json:"title"`
	Claim       string  `json:"claim"`
	AuthorID    string  `json:"authorID"`
	Author      *User   `json:"author"`
	TicketID    *string `json:"ticketID,omitempty"`
	Message     string  `json:"message"`
	CreatedAt   string  `json:"createdAt"`
}

type KnowledgeTag struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Mutation struct {
}

type Query struct {
}

type QueuedAlertsResponse struct {
	Alerts     []*alert.QueuedAlert `json:"alerts"`
	TotalCount int                  `json:"totalCount"`
}

type Session struct {
	ID        string  `json:"id"`
	TicketID  string  `json:"ticketID"`
	Status    string  `json:"status"`
	UserID    *string `json:"userID,omitempty"`
	User      *User   `json:"user,omitempty"`
	Query     *string `json:"query,omitempty"`
	SlackURL  *string `json:"slackURL,omitempty"`
	Intent    *string `json:"intent,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type SessionMessage struct {
	ID        string `json:"id"`
	SessionID string `json:"sessionID"`
	Type      string `json:"type"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type TagMetadata struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Color       string  `json:"color"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type TagObject struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type TicketsResponse struct {
	Tickets    []*ticket.Ticket `json:"tickets"`
	TotalCount int              `json:"totalCount"`
}

type UpdateKnowledgeInput struct {
	ID       string   `json:"id"`
	Title    string   `json:"title"`
	Claim    string   `json:"claim"`
	Tags     []string `json:"tags"`
	Message  string   `json:"message"`
	TicketID *string  `json:"ticketID,omitempty"`
}

type UpdateKnowledgeTagInput struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type UpdateTagInput struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Color       string  `json:"color"`
	Description *string `json:"description,omitempty"`
}

type User struct {
	ID   string  `json:"id"`
	Name string  `json:"name"`
	Icon *string `json:"icon,omitempty"`
}

type ReprocessJobStatus string

const (
	ReprocessJobStatusPending   ReprocessJobStatus = "PENDING"
	ReprocessJobStatusRunning   ReprocessJobStatus = "RUNNING"
	ReprocessJobStatusCompleted ReprocessJobStatus = "COMPLETED"
	ReprocessJobStatusFailed    ReprocessJobStatus = "FAILED"
)

var AllReprocessJobStatus = []ReprocessJobStatus{
	ReprocessJobStatusPending,
	ReprocessJobStatusRunning,
	ReprocessJobStatusCompleted,
	ReprocessJobStatusFailed,
}

func (e ReprocessJobStatus) IsValid() bool {
	switch e {
	case ReprocessJobStatusPending, ReprocessJobStatusRunning, ReprocessJobStatusCompleted, ReprocessJobStatusFailed:
		return true
	}
	return false
}

func (e ReprocessJobStatus) String() string {
	return string(e)
}

func (e *ReprocessJobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReprocessJobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReprocessJobStatus", str)
	}
	return nil
}

func (e ReprocessJobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReprocessJobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReprocessJobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
