name: Lint
on:
  push:
    paths:
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'

jobs:
  golangci:
    name: lint
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: go.sum

      # Cache Go modules for faster dependency resolution
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 10m ./...
          # Skip downloading if cache is available
          skip-cache: false
