name: release

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/warren

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract tag
        id: tag
        run: |
          TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.GITHUB_IMAGE_REPO }}:${{ steps.tag.outputs.tag }}
            ${{ env.GITHUB_IMAGE_REPO }}:latest
          build-args: |
            BUILD_VERSION=${{ steps.tag.outputs.tag }}
          cache-from: |
            type=gha
            type=registry,ref=${{ env.GITHUB_IMAGE_REPO }}:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ env.GITHUB_IMAGE_REPO }}:buildcache,mode=max
          platforms: linux/amd64,linux/arm64