name: trivy

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ github.head_ref }}

      - id: scan
        name: Run Trivy vulnerability scanner (SARIF)
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.34.1
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: 1
          version: "v0.69.2"
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db

      - name: Display vulnerabilities (table)
        if: always() && steps.scan.outcome != 'skipped'
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.34.1
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"
          exit-code: 0
          version: "v0.69.2"
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db

      - name: Upload Trivy scan results to GitHub Security tab
        if: failure() && steps.scan.outcome == 'failure'
        uses: github/codeql-action/upload-sarif@45580472a5bb82c4681c4ac726cfdb60060c2ee1 # v3.32.4
        with:
          sarif_file: "trivy-results.sarif"
